# -*- coding: utf-8 -*-
# Copyright 2026 Pradyumna Revur — CC BY 4.0 (see LICENSE)
# Bhagavad Gītā, chapter 9 (Rājavidyārājaguhya Yoga), with Śaṅkara's bhāṣya. The Sanskrit
# (mūla and bhāṣya, both public domain) is converted from the text layer of
# the Ramakrishna Math, Hyderabad edition (2013), whose legacy Telugu font was
# mapped to Unicode glyph by glyph; its Telugu translation is not used. Collated
# against Sanskrit Wikisource and the Pullela Śrīrāmacandruḍu edition; every
# correction is logged in SOURCES §7.4. The English of the verses and of the
# bhāṣya is original, made from the Sanskrit. Generated from the collated text — edit here, not
# upstream.


def _v(padas, num, gloss, bhashya=None, words=None):
    d = {"padas": padas, "num": num, "gloss": gloss}
    if bhashya:
        d["bhashya"] = bhashya
    if words:
        d["words"] = words
    return d


STOTRA = {
    "deity": "gita",
    "doc_title": "Bhagavad Gītā 9 · Rājavidyārājaguhya Yoga · Śaṅkara Bhāṣya",
    "app_title": "Gītā 9",
    "h1": "Bhagavad Gītā · Chapter 9",
    "subtitle": "Rājavidyārājaguhya Yoga · the royal knowledge, the royal secret · with Śaṅkara's bhāṣya",
    "note": "The 'royal knowledge, the royal secret': all beings rest in the Lord while he rests in none; he sends forth and withdraws the worlds, yet remains unbound. The chapter closes with the promise that even a leaf, a flower, fruit or water offered in devotion is accepted.",
    "footer": "Source: Śrīmad Bhagavadgītā Śaṅkarabhāṣyamu (Ramakrishna Math, Hyderabad, 2013), Sanskrit mūla and bhāṣya only, collated with Sanskrit Wikisource and the Pullela Śrīrāmacandruḍu edition; translations original. See SOURCES §7.4.",
    "nav": [('‹ chapter 8', 'gita-bhashya-08-iast.html'), ('all chapters', '../../index.html#gita'), ('chapter 10 ›', 'gita-bhashya-10-iast.html')],
    "sections": [
        {"bhashya": [
            {"text": "aṣṭame nāḍidvāreṇa dhāraṇāyogaḥ saguṇaḥ uktaḥ tasya phalaṃ agnyarcirādikrameṇa kālāntare brahmaprāptilakṣaṇaṃ eva anāvṛttirūpaṃ nirdiṣṭam. tatra “anenaiva prakāreṇa mokṣaprāptiḥ phalaṃ adhigamyate, na anyathā” iti tadāśaṅkāvyāvivartayiṣayā śrībhagavān", "tr": "In the eighth chapter the yoga of holding with attributes, by way of the channel, was taught; and its fruit was declared to be non-return, consisting in the attainment of Brahman in course of time by the stages of fire, flame and the rest. Wishing to remove the doubt that 'the attainment of liberation comes by this means alone and not otherwise', the Blessed Lord [said]:"},
        ], "summary": "bhāṣya · the chapter's opening"},
        {"speaker": "śrī bhagavānuvāca"},
        _v([
            "idaṃ tu te guhyatamaṃ pravakṣyāmyanasūyave |",
            "jñānaṃ vijñānasahitaṃ yad jñātvā mokṣyase'śubhāt",
        ], "|| 1 ||",
           "The Blessed Lord said: To you, who do not cavil, I will declare this most secret knowledge together with realisation, knowing which you will be freed from evil.",
           bhashya=[
               {"text": "idaṃ iti. idaṃ brahmajñānaṃ, vakṣyamāṇaṃ, uktaṃ ca pūrveṣu adhyāyeṣu. tat buddhau sannidhīkṛtya “idaṃ” ityāha. “tu” śabdo viśeṣanirdhāraṇārthaḥ – idameva tu samyak jñānaṃ sākṣāt mokṣaprāptisādhanaṃ “vāsudevaḥ sarvamiti” (7.19) “ātmaivedaṃ sarvaṃ” (chāṃ.u. 7.25.2) “ekamevādvitīyaṃ” (chāṃ.u.6.2.1) ityādi śrutismṛtibhyaḥ, nānyat, “atha te ye'nyathā'to viduḥ anyarājānaḥ te kṣayyalokā bhavanti” (chāṃ.u.7.25.2) ityādi śrutibhyaśca. te tubhyaṃ guhyatamaṃ gopyatamaṃ pravakṣyāmi kathayiṣyāmi anasūyave asūyārahitāya. kiṃ tat? jñānaṃ – kiṃ viśiṣṭaṃ? vijñānasahitaṃ anubhavayuktaṃ, yat jñānaṃ jñātvā prāpya mokṣyase aśubhāt saṃsārabandhanāt.", "tr": "'But this most secret…' This: the knowledge of Brahman, which is about to be told and has been told in the earlier chapters; holding it present to the mind he says 'this'. The word 'but' is to single it out: this alone is right knowledge, the direct means of attaining liberation — according to the śrutis and smṛtis 'Vāsudeva is all' (7.19), 'the Self alone is all this' (Chāndogya 7.25.2), 'one only, without a second' (Chāndogya 6.2.1) — and nothing else, according to śrutis such as 'but those who know otherwise than this have others for their rulers and go to perishable worlds' (Chāndogya 7.25.2). I will declare, tell, to you, who are without envy, this most secret, most to be guarded. What is it? Knowledge. Of what kind? Together with realisation, joined with experience — knowing, attaining, which knowledge, you will be freed from evil, from the bondage of saṃsāra."},
           ],
           words=[
               ["idam", "this"],
               ["tu", "but"],
               ["te", "to you"],
               ["guhya-tamam", "most secret"],
               ["pravakṣyāmi", "I will declare"],
               ["anasūyave", "who do not carp"],
               ["jñānam", "knowledge"],
               ["vijñāna-sahitam", "together with realisation"],
               ["yat", "which"],
               ["jñātvā", "knowing"],
               ["mokṣyase", "you will be freed"],
               ["aśubhāt", "from evil"],
           ]),
        _v([
            "rājavidyā rājaguhyaṃ pavitramidamuttamam |",
            "pratyakṣāvagamaṃ dharmyaṃ susukhaṃ kartumavyayam",
        ], "|| 2 ||",
           "It is the royal knowledge, the royal secret, the supreme purifier, directly perceived, in keeping with dharma, easy to practise, and imperishable.",
           bhashya=[
               {"text": "rājavidyā iti. rājavidyā vidyānāṃ rājā, dīptyatiśayavattvāt, dīpyate hi iyaṃ atiśayena brahmavidyā sarvavidyānām. tathā rājaguhyaṃ guhyānāṃ rājā. pavitraṃ pāvanaṃ idaṃ uttamaṃ, sarveṣāṃ pāvanānāṃ śuddhikāraṇaṃ idaṃ brahmajñānaṃ utkṛṣṭatamam. aneka janmasahasrasañcitaṃ api dharmādharmādi samūlaṃ karma kṣaṇamātrāt eva bhasmīkaroti ityataḥ kiṃ tasya pāvanatvaṃ vaktavyam. kiñca – pratyakṣāvagamaṃ pratyakṣeṇa sukhādeḥ iva avagamaḥ yasya tat pratyakṣāvagamam. anekaguṇavato'pi dharmaviruddhatvaṃ dṛṣṭaṃ, na tathā ātmajñānaṃ dharmavirodhi, kintu dharmyaṃ dharmāt anapetam. evamapi syāt duḥkhasampādyaṃ ityata āha – susukhaṃ kartuṃ yathā ratnavivekavijñānam. tatra alpāyāsānāṃ anyeṣāṃ karmaṇāṃ sukhasampādyānāṃ alpaphalatvaṃ, duṣkarāṇāṃ ca mahāphalatvaṃ dṛṣṭamiti, idaṃ tu sukhasampādyatvāt phalakṣayāt vyeti iti prāpte āha – avyayaṃ iti. na asya phalataḥ karmavat vyayaḥ astīti avyayam. ataḥ śraddheyaṃ ātmajñānam.", "tr": "'The royal knowledge…' The royal knowledge: the king of knowledges, because of its surpassing radiance; for this knowledge of Brahman shines exceedingly among all knowledges. Likewise the royal secret, the king of secrets. Purifying, this highest — this knowledge of Brahman is the most excellent of all purifiers, the cause of purification. It burns to ashes in a moment even the action, merit and demerit with their root, accumulated over many thousands of births; what need is there to speak of its purifying power? Moreover it is known directly — it is understood directly, like pleasure and the rest. Something with many virtues may be seen to be against dharma; the knowledge of the Self is not opposed to dharma, but righteous, not departing from dharma. Even so it might be hard to achieve; so he says: very easy to do, like the discerning knowledge of gems. Other actions that take little effort and are easy to accomplish are seen to have small fruit, and those hard to do great fruit; so one might think that this, being easy to achieve, passes away when its fruit is exhausted. So he says: imperishable — it does not perish through its fruit as action does. Therefore the knowledge of the Self is worthy of faith."},
           ],
           words=[
               ["rāja-vidyā", "the royal knowledge"],
               ["rāja-guhyam", "the royal secret"],
               ["pavitram", "purifier"],
               ["idam", "this"],
               ["uttamam", "the highest"],
               ["pratyakṣa-avagamam", "known directly"],
               ["dharmyam", "righteous"],
               ["su-sukham", "very easy"],
               ["kartum", "to practise"],
               ["avyayam", "imperishable"],
           ]),
        _v([
            "aśraddadhānāḥ puruṣā dharmasyāsya parantapa |",
            "aprāpya māṃ nivartante mṛtyusaṃsāravartmani",
        ], "|| 3 ||",
           "Men without faith in this dharma, O scorcher of foes, do not reach me, but return to the path of death and rebirth.",
           bhashya=[
               {"text": "aśraddadhānāḥ iti. aśraddadhānāḥ śraddhāvirahitāḥ ātmajñānasya dharmasya asya svarūpe tatphale ca nāstikāḥ pāpakāriṇaḥ asurāṇāṃ upaniṣadaṃ dehamātrātmadarśanameva pratipannāḥ, asutṛpaḥ pāpāḥ puruṣāḥ aśraddadhānāḥ parantapa! aprāpya māṃ parameśvaraṃ – matprāptau naiva āśaṅkā iti matprāptimārgasādhanabhedabhakti mātramapi aprāpya ityarthaḥ – nivartante niścayena vartante – kva? mṛtyusaṃsāravartmani mṛtyuyuktaḥ saṃsāraḥ mṛtyusaṃsāra, tasya vartma narakatiryagādiprāptimārgaḥ tasminneva vartate ityarthaḥ.", "tr": "'Men without faith…' Men without faith — devoid of faith in this dharma, the knowledge of the Self, in its nature and its fruit; unbelievers, evil-doers, who have adopted the doctrine of the asuras, seeing the body alone as the Self, sinful men who gratify their life-breaths — those men without faith, scorcher of foes, not attaining me, the supreme Lord — there is no question of their attaining me; not attaining even mere devotion, a distinct means on the path to attaining me, that is — return, abide with certainty — where? On the path of mortal saṃsāra: saṃsāra joined with death is mortal saṃsāra, and its path is the way to hell, animal births and the like; they abide on that alone, that is."},
           ],
           words=[
               ["aśraddadhānāḥ", "without faith"],
               ["puruṣāḥ", "men"],
               ["dharmasya", "in dharma"],
               ["asya", "this"],
               ["parantapa", "O scorcher of foes"],
               ["aprāpya", "not attaining"],
               ["mām", "me"],
               ["nivartante", "return"],
               ["mṛtyu-saṃsāra-vartmani", "to the path of mortal saṃsāra"],
           ]),
        _v([
            "mayā tatamidaṃ sarvaṃ jagadavyaktamūrtinā |",
            "matsthāni sarvabhūtāni na cāhaṃ teṣvavasthitaḥ",
        ], "|| 4 ||",
           "This whole world is pervaded by me in my unmanifest form. All beings abide in me, but I do not abide in them.",
           bhashya=[
               {"text": "stutyā arjunaṃ abhimukhīkṛtya āha –", "intro": True, "tr": "Having made Arjuna attentive by praise, he says:"},
               {"text": "mayā iti. mayā mama yaḥ parobhāvaḥ tena tataṃ vyāptam sarvaṃ idaṃ jagat avyaktamūrtinā na vyaktā mūrtiḥ svarūpaṃ yasya mama saḥ ahaṃ avyaktamūrtiḥ tena mayā avyaktamūrtinā, karaṇāgocara svarūpeṇa ityarthaḥ. tasmin mayi avyaktamūrtau sthitāni matsthāni, sarvabhūtāni brahmādīni stambaparyantāni. na hi nirātmakaṃ kiñcit bhūtaṃ vyavahārāya avakalpate. ataḥ matsthāni mayā ātmanā ātmavattvena sthitāni, ataḥ mayi sthitāni iti ucyante. teṣāṃ bhūtānāṃ ahameva ātmā ityataḥ teṣu sthitaḥ, mūrtavat saṃśleṣābhāvena ākāśasyāpi antaratamo hi aham. na hi asaṃsargi vastu kvacit ādheyabhāvena avasthitaṃ bhavati.", "tr": "'By me all this world is pervaded…' By me, by my supreme state, all this world is pervaded, filled; by me of unmanifest form — I whose form, whose nature, is not manifest, by me of unmanifest form, that is, of a nature beyond the reach of the senses. In me of unmanifest form abide all beings, from Brahmā down to a clump of grass. For no being without a Self is fit for empirical dealings. So they abide in me — they abide through me, the Self, by having a Self — and are therefore said to abide in me. Since I alone am the Self of those beings, it might be thought that I abide in them; so he says: and I do not abide in them — since I have no contact as embodied things do, I am innermost even of space. For a thing without contact never stands as something contained."},
           ],
           words=[
               ["mayā", "by me"],
               ["tatam", "is pervaded"],
               ["idam", "this"],
               ["sarvam", "whole"],
               ["jagat", "world"],
               ["avyakta-mūrtinā", "of unmanifest form"],
               ["mat-sthāni", "abide in me"],
               ["sarva-bhūtāni", "all beings"],
               ["na", "not"],
               ["ca", "and"],
               ["aham", "I"],
               ["teṣu", "in them"],
               ["avasthitaḥ", "abide"],
           ]),
        _v([
            "na ca matsthāni bhūtāni paśya me yogamaiśvaram |",
            "bhūtabhṛnna ca bhūtastho mamātmā bhūtabhāvanaḥ",
        ], "|| 5 ||",
           "And yet beings do not abide in me — behold my divine yoga! Sustaining beings but not abiding in them, my Self brings beings into being.",
           bhashya=[
               {"text": "ata eva asaṃsargitvāt mama –", "intro": True, "tr": "For this very reason, because I am without contact —"},
               {"text": "na ca iti. na ca matsthāni bhūtāni brahmādīni, paśya me yogaṃ yuktiṃ ghaṭanaṃ me mama aiśvaraṃ īśvarasyemaṃ aiśvaraṃ yogaṃ, ātmano yāthātmyaṃ ityarthaḥ. tathā ca śrutiḥ asaṃsargitvāt asaṅgatāṃ darśayati – “asaṅgo na hi sajjate” (bṛ.u.3.9.26) idaṃ ca āścaryaṃ anyat paśya – bhūtabhṛt, asaṅgo'pi san bhūtāni bibharti, na ca bhūtasthaḥ yathoktena nyāyena darśitatvāt bhūtasthatvānupapatteḥ. kathaṃ tu punaḥ ucyate “asau mama ātmā” iti? vibhajya dehādisaṅghātaṃ, tasmin ahaṅkāraṃ adhyāropya, lokabuddhiṃ anusaran vyapadiśati “mama ātmā” iti, na punaḥ ātmanaḥ ātmā anyaḥ iti lokavat ajānan. tathā bhūtabhāvanaḥ bhūtāni bhāvayati'utpādayati'vardhayati iti bhūtabhāvanaḥ.", "tr": "'And beings do not abide in me…' And beings, Brahmā and the rest, do not abide in me. See my divine yoga — my connecting, my contrivance; my lordly yoga, belonging to the Lord: the true nature of the Self, that is. And so the śruti shows non-attachment through absence of contact: 'unattached, for it is not attached' (Bṛhadāraṇyaka 3.9.26). And see this other wonder: sustaining beings — though unattached, he sustains beings — and not abiding in beings, since by the reasoning shown, abiding in beings is impossible. How then is it said 'my Self'? Separating out the aggregate of body and the rest and superimposing egoism on it, following the worldly way of thinking, he speaks of 'my Self' — not as one who, like worldly people, does not know, as if the Self had another self. Likewise the source of beings: he who brings beings into being, produces them, makes them grow."},
           ],
           words=[
               ["na", "not"],
               ["ca", "and"],
               ["mat-sthāni", "abide in me"],
               ["bhūtāni", "beings"],
               ["paśya", "behold"],
               ["me", "my"],
               ["yogam", "yoga"],
               ["aiśvaram", "lordly"],
               ["bhūta-bhṛt", "sustaining beings"],
               ["na", "not"],
               ["ca", "and"],
               ["bhūta-sthaḥ", "abiding in beings"],
               ["mama", "my"],
               ["ātmā", "Self"],
               ["bhūta-bhāvanaḥ", "the source of beings"],
           ]),
        _v([
            "yathā''kāśasthito nityaṃ vāyuḥ sarvatrago mahān |",
            "tathā sarvāṇi bhūtāni matsthānītyupadhāraya",
        ], "|| 6 ||",
           "As the mighty wind, moving everywhere, ever abides in space, so know that all beings abide in me.",
           bhashya=[
               {"text": "yathoktena ślokadvayena uktaṃ arthaṃ dṛṣṭāntena upapādayan āha–", "intro": True, "tr": "Establishing by an illustration the meaning stated in the two verses above, he says:"},
               {"text": "yatheti. yathā loke ākāśasthitaḥ ākāśe sthito nityaṃ sadā vāyuḥ sarvatra gacchatīti sarvatrago mahān parimāṇataḥ, tathā ākāśavat sarvagate mayi asaṃśleṣeva sthitāni ityevamupadhāraya vijānīhi.", "tr": "'As the mighty wind…' As in the world the wind, abiding in space, always, at all times, going everywhere, great in extent — so understand, know, that all beings abide in me, all-pervading like space, without contact."},
           ],
           words=[
               ["yathā", "as"],
               ["ākāśa-sthitaḥ", "abiding in space"],
               ["nityam", "always"],
               ["vāyuḥ", "the wind"],
               ["sarvatra-gaḥ", "going everywhere"],
               ["mahān", "mighty"],
               ["tathā", "so"],
               ["sarvāṇi", "all"],
               ["bhūtāni", "beings"],
               ["mat-sthāni", "abide in me"],
               ["iti", "thus"],
               ["upadhāraya", "understand"],
           ]),
        _v([
            "sarvabhūtāni kaunteya prakṛtiṃ yānti māmikām |",
            "kalpakṣaye punastāni kalpādau visṛjāmyaham",
        ], "|| 7 ||",
           "All beings, son of Kuntī, pass into my nature at the end of an aeon; at the beginning of an aeon I send them forth again.",
           bhashya=[
               {"text": "evaṃ vāyurākāśa iva mayi sthitāni sarvabhūtāni sthitikāle, tāni", "intro": True, "tr": "Thus all beings abide in me, like the wind in space, at the time of their continuance; they —"},
               {"text": "sarveti. sarvabhūtāni kaunteya prakṛtiṃ triguṇātmikāṃ aparāṃ nikṛṣṭāṃ yānti māmikāṃ madīyāṃ, kalpakṣaye pralayakāle, punarbhūyastāni bhūtāni utpattikāle kalpādau visṛjāmi utpādayāmyahaṃ. pūrvavat.", "tr": "'All beings, Kaunteya, pass into my nature…' All beings, Kaunteya, pass into my nature, made of the three guṇas, the lower, the inferior, mine, at the end of the aeon, at the time of dissolution; and again, at the beginning of the aeon, at the time of arising, I send them forth, produce them — as before."},
           ],
           words=[
               ["sarva-bhūtāni", "all beings"],
               ["kaunteya", "O son of Kuntī"],
               ["prakṛtim", "nature"],
               ["yānti", "pass into"],
               ["māmikām", "my"],
               ["kalpa-kṣaye", "at the end of an aeon"],
               ["punaḥ", "again"],
               ["tāni", "them"],
               ["kalpa-ādau", "at the beginning of an aeon"],
               ["visṛjāmi", "send forth"],
               ["aham", "I"],
           ]),
        _v([
            "prakṛtiṃ svāmavaṣṭabhya visṛjāmi punaḥ punaḥ |",
            "bhūtagrāmamimaṃ kṛtsnamavaśaṃ prakṛtervaśāt",
        ], "|| 8 ||",
           "Resting on my own nature, I send forth again and again this whole multitude of beings, helpless under the sway of nature.",
           bhashya=[
               {"text": "evamavidyālakṣaṇām –", "intro": True, "tr": "Thus, [resorting to] this nature, which is ignorance —"},
               {"text": "prakṛtimiti. prakṛtiṃ svāṃ svīyāmavaṣṭabhya vaśīkṛtya visṛjāmi punaḥ punaḥ, prakṛtito jātaṃ bhūtagrāmaṃ bhūtasamudāyaṃ imaṃ vartamānaṃ, kṛtsnaṃ samastaṃ, avaśaṃ asvatantraṃ avidyādidoṣaiḥ paravaśīkṛtaṃ, prakṛtervaśāt, svabhāvavaśāt–", "tr": "'Resorting to my own nature…' Resorting to, bringing under control, my own nature, I send forth again and again this present host of beings born of nature, the whole, entire, multitude of beings, helpless, without freedom, made subject by ignorance and the other faults, by the power of nature, the power of their own being."},
           ],
           words=[
               ["prakṛtim", "nature"],
               ["svām", "my own"],
               ["avaṣṭabhya", "resorting to"],
               ["visṛjāmi", "I send forth"],
               ["punaḥ punaḥ", "again and again"],
               ["bhūta-grāmam", "host of beings"],
               ["imam", "this"],
               ["kṛtsnam", "whole"],
               ["avaśam", "helpless"],
               ["prakṛteḥ", "of nature"],
               ["vaśāt", "by the power"],
           ]),
        _v([
            "na ca māṃ tāni karmāṇi nibadhnanti dhanañjaya |",
            "udāsīnavadāsīnamasaktaṃ teṣu karmasu",
        ], "|| 9 ||",
           "Nor do these actions bind me, Dhanañjaya; I sit as one indifferent, unattached to those actions.",
           bhashya=[
               {"text": "tarhi tasya te parameśvarasya bhūtagrāmamimaṃ viṣamaṃ vidadhataḥ, tannimittābhyāṃ dharmādharmābhyāṃ sambandhassyāditi, idamāha bhagavān –", "intro": True, "tr": "Then, since you, the supreme Lord, create this unequal host of beings, you would be connected with the merit and demerit that arise from it. To this the Blessed Lord says:"},
           ],
           words=[
               ["na", "not"],
               ["ca", "and"],
               ["mām", "me"],
               ["tāni", "those"],
               ["karmāṇi", "actions"],
               ["nibadhnanti", "bind"],
               ["dhanañjaya", "O Dhanañjaya"],
               ["udāsīna-vat", "as one indifferent"],
               ["āsīnam", "sitting"],
               ["asaktam", "unattached"],
               ["teṣu", "to those"],
               ["karmasu", "actions"],
           ]),
        _v([
            "mayā'dhyakṣeṇa prakṛtissūyate sacarācaram |",
            "hetunā'nena kaunteya jagadviparivartate",
        ], "|| 10 ||",
           "With me as overseer, nature gives birth to the moving and the unmoving; for this reason, son of Kuntī, the world revolves.",
           bhashya=[
               {"text": "neti. na ca māmīśvaraṃ tāni bhūtagrāmasya viṣamasarganimittāni karmāṇi nibadhnanti dhanañjaya. tatra karmaṇām asambandhitve kāraṇamaha – udāsīnavat āsīnaṃ yathā udāsīnaḥ upekṣakaḥ kaścit tadvādāsīnaṃ, ātmano'vikriyatvāt asaktaṃ phalāsaṅgarahitam abhimānavarjitam, “ahaṃ karomi” iti teṣu karmasu. ato'nyasyāpi kartṛtvābhimānābhāvaḥ phalāsaṅgābhāvaścāsambandha kāraṇaṃ anyathā karmabhirbadhyate mūḍhaḥ kośakāravadityabhiprāyaḥ.", "intro": True, "tr": "'And those actions do not bind me…' And those actions, the causes of the unequal creation of the host of beings, do not bind me, the Lord, Dhanañjaya. He states the reason why actions are unconnected with him: sitting as one indifferent — as some indifferent onlooker, so sitting, since the Self is changeless — unattached, free of attachment to fruit, free of the conceit 'I act' in those actions. So for anyone else too, the absence of the conceit of agency and of attachment to fruit is the reason for non-connection; otherwise the deluded man is bound by actions like a silkworm — that is the purport."},
               {"text": "tatra “bhūtagrāmamimaṃ visṛjāmi”, “udāsīnavadāsīnam” iti ca viruddhamucyate iti tatparihārārthamāha –", "intro": True, "tr": "Here 'I send forth this host of beings' and 'sitting as one indifferent' seem contradictory; to remove this he says:"},
               {"text": "mayeti. mayā adhyakṣeṇa sarvato dṛśimātrasvarūpeṇāvikriyātma nādhyakṣeṇa mayā, mama māyā triguṇātmikā'vidyālakṣaṇā prakṛtiḥ sūyate utpādayati sa carācaraṃ jagat – tathā ca mantravarṇaḥ “eko deva ssarvabhūteṣu gūḍhassarvavyāpī sarvabhūtāntarātmā, karmādhyakṣassarvabhūtādhivāsassākṣī cetā kevalo nirguṇaśce”ti (śve.u.6.11) hetunā nimittenānena adhyakṣatvena, kaunteya, jagatsacarācaraṃ vyaktāvyaktātmakaṃ viparivartate sarvāvasthāsu. dṛśikarmatvāpattinimittā hi jagatassarvā pravṛttiḥ “ahamidaṃ bhokṣye” “paśyāmīdaṃ”, “śṛṇomīdaṃ” “sukhamanubhavāmi duḥkhamanubhavāmi” “tadarthamidaṃ kariṣye”, “idaṃ jñāsyāmi” ityādyā avagatiniṣṭhā avagatyavasānaiva, “yo asyādhyakṣaḥ parame vyoman” (tai.brā.2.8.9) ityādayaśca mantrāḥ etamarthaṃ darśayanti. tataścaikasya devasya sarvādhyakṣa bhūtacaitanyamātrasya paramārthataḥ sarvabhogā nabhisambandhinaḥ anyasya cetanāntarasyābhāve bhokturanyasya abhāvāt. kiṃ nimittā iyaṃ sṛṣṭirityatra praśna prativacane anupapanne. “ko addhā veda ka iha pravocat. kuta ājātā kuta iyaṃ visṛṣṭiḥ” ityādi mantravarṇebhyaḥ. darśitaṃ ca bhagavatā – “ajñānenāvṛtaṃ jñānaṃ tena muhyanti jantavaḥ” iti.", "tr": "'With me as overseer…' With me as overseer — me, whose nature is mere seeing on every side, unchanging — nature, my māyā, made of the three guṇas, which is ignorance, gives birth to, produces, the world of moving and unmoving things. And so says the mantra: 'The one God, hidden in all beings, all-pervading, the inner Self of all beings, the overseer of actions, dwelling in all beings, the witness, the knower, alone, without qualities' (Śvetāśvatara 6.11). By this reason, this cause — being the overseer — Kaunteya, the world, moving and unmoving, manifest and unmanifest, revolves in all its states. For all the activity of the world arises from its becoming an object of seeing: 'I shall enjoy this', 'I see this', 'I hear this', 'I feel pleasure, I feel pain', 'for that I shall do this', 'I shall know this' — all of it is grounded in awareness and ends in awareness. Mantras such as 'he who is its overseer in the highest heaven' (Taittirīya Brāhmaṇa 2.8.9) show this meaning. Hence, since there is in truth one God, the overseer of all, mere consciousness, unconnected with any enjoyment, and since there is no other conscious being, there being no other enjoyer, the question 'for what purpose is this creation?' and any answer to it are out of place, according to mantras such as 'who truly knows, who here can declare, whence it was born, whence this creation?' And the Lord has shown: 'knowledge is covered by ignorance; by that creatures are deluded' (5.15)."},
           ],
           words=[
               ["mayā", "with me"],
               ["adhyakṣeṇa", "as overseer"],
               ["prakṛtiḥ", "nature"],
               ["sūyate", "gives birth to"],
               ["sa-cara-acaram", "the moving and the unmoving"],
               ["hetunā", "for reason"],
               ["anena", "this"],
               ["kaunteya", "O son of Kuntī"],
               ["jagat", "the world"],
               ["viparivartate", "revolves"],
           ]),
        _v([
            "avajānanti māṃ mūḍhā mānuṣīṃ tanumāsthitam |",
            "paraṃ bhāvamajānanto mama bhūtamaheśvaram",
        ], "|| 11 ||",
           "The deluded disregard me when I take a human body, not knowing my higher being as the great lord of beings.",
           bhashya=[
               {"text": "evaṃ māṃ nityaśuddhabuddhamuktasvabhāvaṃ sarvajñaṃ sarvajantūnāmātmānamapi santam.", "intro": True, "tr": "Thus me — eternally pure, awake and free by nature, all-knowing, though I am the Self of all creatures —"},
               {"text": "avajānantīti. avajānanti avajñāṃ paribhavaṃ kurvanti māṃ, mūḍhāḥ avivekinaḥ mānuṣīṃ manuṣyasambandhinīṃ tanuṃ dehamāśritaṃ, manuṣyadehena vyavaharaṃ tamityetat, paraṃ prakṛṣṭaṃ bhāvaṃ, paramātmatattvaṃ ākāśakalpaṃ ākāśādapyantara tamamajānanto mama bhūtamaheśvaraṃ sarvabhūtānāṃ mahāntamīśvaraṃ svāttmānaṃ. tataśca mama avajñābhāvanenā''hatāḥ te varākāḥ katham –", "tr": "'The deluded disregard me…' The deluded, the undiscriminating, disregard me, treat me with contempt, as having taken on a human body — dealing with the world through a human body, that is — not knowing my supreme, highest, state, the reality of the supreme Self, like space, more inward even than space, the great Lord of beings, the great Lord of all beings, their own Self. And then, struck down by their contempt for me, those wretched ones — how are they?"},
           ],
           words=[
               ["avajānanti", "disregard"],
               ["mām", "me"],
               ["mūḍhāḥ", "the deluded"],
               ["mānuṣīm", "human"],
               ["tanum", "body"],
               ["āsthitam", "having taken on"],
               ["param", "supreme"],
               ["bhāvam", "state"],
               ["ajānantaḥ", "not knowing"],
               ["mama", "my"],
               ["bhūta-mahā-īśvaram", "as the great Lord of beings"],
           ]),
        _v([
            "moghāśāḥ moghakarmāṇo moghajñānā vicetasaḥ |",
            "rākṣasīmāsurīṃ caiva prakṛtiṃ mohinīṃ śritāḥ",
        ], "|| 12 ||",
           "Vain in their hopes, vain in their actions, vain in their knowledge, senseless, they are given to the deluding nature of fiends and demons.",
           bhashya=[
               {"text": "mogheti. moghāśāḥ vṛthā āśāḥ āśiṣo yeṣāṃ te moghāśāḥ, tathā mogha karmāṇaḥ yāni cāgniho trādīni tairanuṣṭhīyamānāni karmāṇi tāni ca teṣāṃ bhagavatparibhavāt, svātmabhūtasya cājñānāt, moghānyeva niṣphalāni karmāṇi bhavantīti moghakarmāṇaḥ, tathā moghajñānāḥ moghaṃ niṣphalaṃ jñānaṃ yeṣāṃ te moghajñānāḥ jñānamapi teṣāṃ niṣphalameva syāt, vicetasaḥ vigatavivekāśca te bhavanti ityabhiprāyaḥ. kiñca, te bhavanti rākṣasīṃ rakṣasāṃ prakṛtiṃ svabhāvaṃ āsurīṃ asurāṇāṃ ca prakṛtiṃ mohinīṃ mohakarīṃ dehātmavādinīṃ śritāḥ āśritāḥ chindhi, bhindi, khāda, parasvamapahara, ityevaṃ vadanaśīlāḥ krūrakarmāṇo bhavantītyarthaḥ “asuryā nāma te lokāḥ” (ī.u.3) iti śruteḥ.", "tr": "'Vain in hopes, vain in actions…' Vain in hopes: whose hopes, whose wishes, are in vain. Likewise vain in actions: the agnihotra and other actions they perform become vain, fruitless, because of their contempt for the Lord and their ignorance of him who is their own Self. Likewise vain in knowledge: whose knowledge is vain, fruitless — even their knowledge would be fruitless; and senseless, they are devoid of discrimination — that is the purport. Moreover, they take to, resort to, the deluding nature of rākṣasas and of asuras, which holds the body to be the Self — given to saying 'cut, pierce, eat, steal others' goods', they become cruel in their deeds, that is, according to the śruti 'those worlds are called sunless' (Īśa 3)."},
           ],
           words=[
               ["mogha-āśāḥ", "vain in hopes"],
               ["mogha-karmāṇaḥ", "vain in actions"],
               ["mogha-jñānāḥ", "vain in knowledge"],
               ["vicetasaḥ", "senseless"],
               ["rākṣasīm", "of rākṣasas"],
               ["āsurīm", "of asuras"],
               ["ca", "and"],
               ["eva", "indeed"],
               ["prakṛtim", "nature"],
               ["mohinīm", "deluding"],
               ["śritāḥ", "they resort to"],
           ]),
        _v([
            "mahātmānastu māṃ pārtha daivīṃ prakṛtimāśritāḥ |",
            "bhajantyananyamanaso jñātvā bhūtādimavyayam",
        ], "|| 13 ||",
           "But the great souls, Pārtha, resorting to the divine nature, worship me with undistracted minds, knowing me as the imperishable origin of beings.",
           bhashya=[
               {"text": "ye punaḥ śraddadhānāḥ bhagavadbhaktilakṣaṇe mokṣamārge pravṛttāḥ –", "intro": True, "tr": "But those who have faith and have set out on the path to liberation consisting in devotion to the Lord —"},
               {"text": "mahātmānaḥ akṣudracittāḥ māmīśvaraṃ pārtha daivānāṃ prakṛtiṃ śamadamadayā śraddhādilakṣaṇāṃ āśritāssanto bhajanti ananyamanasaḥ ananyacittāḥ jñātvā bhūtādiṃ bhūtānāṃ viyadādīnāṃ prāṇināṃ ca ādiṃ kāraṇamavyayam. katham?", "tr": "Great souls, of no petty mind, Pārtha, resorting to the divine nature — the nature of the gods, marked by calm, self-control, compassion, faith and the like — worship me, the Lord, with minds turned to nothing else, knowing me as the origin of beings — the beginning, the cause, of the elements, space and the rest, and of living beings — imperishable. How?"},
           ],
           words=[
               ["mahā-ātmānaḥ", "great souls"],
               ["tu", "but"],
               ["mām", "me"],
               ["pārtha", "O Pārtha"],
               ["daivīm", "divine"],
               ["prakṛtim", "nature"],
               ["āśritāḥ", "resorting to"],
               ["bhajanti", "worship"],
               ["ananya-manasaḥ", "with minds on nothing else"],
               ["jñātvā", "knowing"],
               ["bhūta-ādim", "the origin of beings"],
               ["avyayam", "imperishable"],
           ]),
        _v([
            "satataṃ kīrtayanto māṃ yatantaśca dṛḍhavratāḥ |",
            "namasyantaśca māṃ bhaktyā nityayuktā upāsate",
        ], "|| 14 ||",
           "Ever glorifying me, striving, firm in their vows, bowing to me in devotion, ever disciplined, they worship me.",
           bhashya=[
               {"text": "satataṃ sarvadā bhagavantaṃ brahmasvarūpaṃ māṃ kīrtayantaḥ, yatantaśca indriyopasaṃhāra śamadamadayā'hiṃsādilakṣaṇaiḥ dharmaiḥ prayatantaśca, dṛḍhavratāḥ dṛḍhaṃ sthiramacālyaṃ vrataṃ yeṣāṃ te dṛḍhavratāḥ namasyantaśca māṃ hṛdayeśayaṃ ātmānaṃ bhaktyā nityayuktāssantaḥ, upāsate sevante.", "tr": "Always, at all times, glorifying me, the Lord whose nature is Brahman; and striving — making effort through such dharmas as withdrawal of the senses, calm, self-control, compassion and non-violence; firm in their vows — whose vows are firm, steady, unshakeable; and bowing down to me, the Self dwelling in the heart, with devotion, ever disciplined, they worship, serve, me."},
           ],
           words=[
               ["satatam", "always"],
               ["kīrtayantaḥ", "glorifying"],
               ["mām", "me"],
               ["yatantaḥ", "striving"],
               ["ca", "and"],
               ["dṛḍha-vratāḥ", "firm in their vows"],
               ["namasyantaḥ", "bowing down"],
               ["ca", "and"],
               ["mām", "to me"],
               ["bhaktyā", "with devotion"],
               ["nitya-yuktāḥ", "ever disciplined"],
               ["upāsate", "they worship"],
           ]),
        _v([
            "jñānayajñena cāpyanye yajanto māmupāsate |",
            "ekatvena pṛthaktvena bahudhā viśvatomukham",
        ], "|| 15 ||",
           "Others, offering the sacrifice of knowledge, worship me as one, as distinct, and in many ways, as facing in every direction.",
           bhashya=[
               {"text": "te kena kena prakāreṇa upāsate ityucyate –", "intro": True, "tr": "In what ways do they worship? It is said:"},
               {"text": "jñānayajñena jñānameva bhagavadviṣayaṃ yajñaḥ tena jñānayajñena, yajantaḥ pūjayantaḥ māmīśvaraṃ cāpyanye anyāmupāsanāṃ parityajya upāsate. tacca jñānam – ekatvena “ekameva paraṃ brahma” iti paramārthadarśanena yajantaḥ upāsate. kecicca pṛthaktvena “ādityacandrādibhedena sa eva bhagavān viṣṇuravasthitaḥ” iti upāsate. “kecit bahudhā avasthitaḥ sa eva bhagavān viśvatomukhaḥ sarvatomukhaḥ viśvarūpaḥ” iti taṃ viśvarūpaṃ sarvatomukhaṃ bahudhā bahuprakāreṇopāsate.", "tr": "And others too, sacrificing with the sacrifice of knowledge — knowledge itself, concerning the Lord, is the sacrifice — worshipping me, the Lord, worship me, giving up other forms of worship. And that knowledge: some worship sacrificing in oneness, with the vision of the supreme truth, 'the supreme Brahman is one only'. Some worship in separateness: 'that same Blessed Lord Viṣṇu abides as the sun, the moon and the rest'. Some: 'that same Blessed Lord abides in many forms, facing everywhere, facing all directions, having all forms' — so they worship him, of all forms, facing everywhere, in many ways."},
           ],
           words=[
               ["jñāna-yajñena", "with the sacrifice of knowledge"],
               ["ca", "and"],
               ["api", "also"],
               ["anye", "others"],
               ["yajantaḥ", "sacrificing"],
               ["mām", "me"],
               ["upāsate", "worship"],
               ["ekatvena", "as one"],
               ["pṛthaktvena", "as distinct"],
               ["bahudhā", "in many ways"],
               ["viśvataḥ-mukham", "facing everywhere"],
           ]),
        _v([
            "ahaṃ kraturahaṃ yajñaḥ svadhā'hamahamauṣadham |",
            "mantro'hamahamevājyamahamagnirahaṃ hutam",
        ], "|| 16 ||",
           "I am the ritual, I am the sacrifice, I am the offering to the ancestors, I am the healing herb; I am the mantra, I am the clarified butter, I am the fire, I am the oblation.",
           bhashya=[
               {"text": "yadi bahubhiḥ prakāraiḥ upāsate, kathaṃ tvāmevopāsate iti ata āha–", "intro": True, "tr": "If they worship in many ways, how do they worship you alone? So he says:"},
               {"text": "ahaṃ kratuḥ śrautakarma bhedaḥ ahameva. ahaṃ yajñaḥ smārtaḥ, kiñca svadhā annamahaṃ, pitṛbhyo yaddīyate. ahamauṣadhaṃ sarvaprāṇibhiryadadyate tadauṣadhaśabdaśabditaṃ vrīhiyavādisādhāraṇaṃ. athavā svadheti sarvaprāṇisādhāraṇamannam, auṣadhamiti vyādhyupaśamanārthaṃ bheṣajaṃ. mantro'haṃ, yena pitṛbhyo devatābhyaśca havirdīyate. ahamevājyaṃ haviśca. ahamagniḥ, yasmin hūyate haviḥ so'gnirahaṃ. ahaṃ hutaṃ havanakarma ca. kiñca –", "tr": "I am the kratu, a kind of Vedic rite; I am the yajña, the sacrifice taught in smṛti; moreover I am svadhā, the food offered to the ancestors; I am the auṣadha — what all living beings eat, called by the word auṣadha, food plants common to all, such as rice and barley; or else svadhā is food common to all living beings, and auṣadha the medicine that relieves disease. I am the mantra with which the oblation is given to ancestors and gods. I am the clarified butter, the oblation. I am the fire — the fire into which the oblation is offered am I. I am the offering, the act of oblation. Moreover —"},
           ],
           words=[
               ["aham", "I"],
               ["kratuḥ", "the rite"],
               ["aham", "I"],
               ["yajñaḥ", "the sacrifice"],
               ["svadhā", "the offering to ancestors"],
               ["aham", "I"],
               ["aham", "I"],
               ["auṣadham", "the herb"],
               ["mantraḥ", "the mantra"],
               ["aham", "I"],
               ["aham", "I"],
               ["eva", "alone"],
               ["ājyam", "the ghee"],
               ["aham", "I"],
               ["agniḥ", "the fire"],
               ["aham", "I"],
               ["hutam", "the offering"],
           ]),
        _v([
            "pitā'hamasya jagato mātā dhātā pitāmahaḥ |",
            "vedyaṃ pavitramoṅkāra ṛksāma yajureva ca",
        ], "|| 17 ||",
           "I am the father of this world, the mother, the sustainer, the grandsire; the object of knowledge, the purifier, the syllable Om, and the Ṛk, Sāman and Yajus.",
           bhashya=[
               {"text": "pitā janayitā ahamasya jagataḥ, mātā janayitrī, dhātā karmaphalasya prāṇibhyo vidhātā, pitāmahaḥ pituḥ pitā, vedyaṃ veditavyaṃ, pavitraṃ pāvanaṃ oṅkāraḥ, ṛksāma yajurevaca. kiñca –", "tr": "I am the father, the begetter, of this world; the mother, she who gives birth; the ordainer, who apportions to living beings the fruit of action; the grandfather, the father's father; what is to be known; the purifier; the syllable om; the Ṛk, the Sāman and the Yajus. Moreover —"},
           ],
           words=[
               ["pitā", "the father"],
               ["aham", "I"],
               ["asya", "of this"],
               ["jagataḥ", "world"],
               ["mātā", "the mother"],
               ["dhātā", "the ordainer"],
               ["pitāmahaḥ", "the grandfather"],
               ["vedyam", "what is to be known"],
               ["pavitram", "the purifier"],
               ["oṅkāraḥ", "the syllable om"],
               ["ṛk", "the Ṛk"],
               ["sāma", "the Sāman"],
               ["yajuḥ", "the Yajus"],
               ["eva ca", "and also"],
           ]),
        _v([
            "gatirbhartā prabhuḥ sākṣī nivāsaśśaraṇaṃ suhṛt |",
            "prabhavaḥ pralayaḥ sthānaṃ nidhānaṃ bījamavyayam",
        ], "|| 18 ||",
           "The goal, the supporter, the lord, the witness, the abode, the refuge, the friend; the origin, the dissolution, the foundation, the treasure-house, and the imperishable seed.",
           bhashya=[
               {"text": "gatiḥ karmaphalaṃ, bhartā poṣṭā, prabhuḥ svāmī, sākṣī prāṇināṃ kṛtākṛtasya, nivāsaḥ yasmin prāṇino nivasanti, śaraṇamārtānāṃ prapannānāmārtiharaḥ, suhṛt pratyupakāra napekṣassan upakārī, prabhavaḥ, utpattirjagataḥ, pralayaḥ pralīyate asminniti tathā sthānaṃ tiṣṭhatyasminniti, nidhānaṃ nikṣepaḥ kālāntaropabhogyaṃ prāṇināṃ, bījaṃ prarohakāraṇaṃ prarohadharmiṇāṃ, avyayaṃ yāvatsaṃsārabhāvitvādavyayaṃ, na hyabījaṃ kiñcitprarohati, nityaṃ ca prarohadarśanāt bījasantatiḥ na vyeti iti gamyate.", "tr": "The goal: the fruit of action. The supporter: the nourisher. The lord: the master. The witness of what living beings do and leave undone. The abode, in which living beings dwell. The refuge: the remover of the distress of the distressed who take refuge. The friend, who helps without expecting a return. The origin, the arising of the world; the dissolution, that in which it dissolves; likewise the resting place, in which it stands; the storehouse, the deposit for living beings to enjoy at a later time; the seed, the cause of sprouting for all that sprouts; imperishable, because it lasts as long as saṃsāra — for nothing sprouts without a seed, and since sprouting is always seen, it is understood that the line of seeds does not cease."},
           ],
           words=[
               ["gatiḥ", "the goal"],
               ["bhartā", "the supporter"],
               ["prabhuḥ", "the lord"],
               ["sākṣī", "the witness"],
               ["nivāsaḥ", "the abode"],
               ["śaraṇam", "the refuge"],
               ["suhṛt", "the friend"],
               ["prabhavaḥ", "the origin"],
               ["pralayaḥ", "the dissolution"],
               ["sthānam", "the resting place"],
               ["nidhānam", "the storehouse"],
               ["bījam", "the seed"],
               ["avyayam", "imperishable"],
           ]),
        _v([
            "tapāmyahamahaṃ varṣaṃ nigṛhṇāmyutsṛjāmi ca |",
            "amṛtaṃ caiva mṛtyuśca sadasaccāhamarjuna",
        ], "|| 19 ||",
           "I give heat; I hold back and send forth the rain. I am immortality and death, Arjuna, being and non-being.",
           bhashya=[
               {"text": "tapāmyahaṃ ādityo bhūtvā kaiścit raśmibhiḥ ulbaṇaiḥ. ahaṃ varṣaṃ kaiścidraśmibhiḥ utsṛjāmi, utsṛjya punaḥ nigṛhṇāmi kaiścidraśmibhiraṣṭabhirmāsaiḥ, punarutsṛjāmi prāvṛṣi. amṛtaṃ caiva devānāṃ, mṛtyuśca martyānāṃ, sat yasya yatsambandhitayā vidyamānaṃ tat, tadviparītamasacca evamahaṃ arjuna na punaratyantamevāsadbhagavān svayaṃ. kāryakāraṇe vā sadasatī.", "tr": "I give heat, becoming the sun, with some of my intense rays. I send forth rain with some rays, and having sent it forth, I withhold it again with some rays for eight months, and send it forth again in the rainy season. I am the nectar of the gods and the death of mortals; being — what exists in relation to something — and its opposite, non-being: so am I, Arjuna. But the Lord himself is not absolute non-being. Or, being and non-being are effect and cause."},
               {"text": "ye pūrvoktairnivṛttiprakāraiḥ ekatvapṛthaktvādi vijñānairyajñairmāṃ pūjayantaḥ upāsate jñānavidaḥ, te yathāvijñānaṃ māmeva prāpnuvanti ye punarajñāḥ kāmakāmāḥ –", "tr": "Those knowers who worship me, honouring me with the sacrifices described above, the forms of withdrawal — the knowledge of oneness, of separateness and the rest — attain me alone according to their knowledge. But the ignorant, who desire desires —"},
           ],
           words=[
               ["tapāmi", "give heat"],
               ["aham", "I"],
               ["aham", "I"],
               ["varṣam", "rain"],
               ["nigṛhṇāmi", "withhold"],
               ["utsṛjāmi", "send forth"],
               ["ca", "and"],
               ["amṛtam", "immortality"],
               ["ca", "and"],
               ["eva", "also"],
               ["mṛtyuḥ", "death"],
               ["ca", "and"],
               ["sat", "being"],
               ["asat", "non-being"],
               ["ca", "and"],
               ["aham", "I"],
               ["arjuna", "O Arjuna"],
           ]),
        _v([
            "traividyā māṃ somapāḥ pūtapāpāḥ yajñai riṣṭvā svargatiṃ prārthayante |",
            "te puṇyamāsādya surendraloka maśnanti divyān divi devabhogān",
        ], "|| 20 ||",
           "Knowers of the three Vedas, drinkers of soma, purified of sin, worship me with sacrifices and pray for the way to heaven. Reaching the holy world of the lord of the gods, they enjoy in heaven the divine pleasures of the gods.",
           bhashya=[
               {"text": "traividyāḥ ṛgyajussāmavidaḥ māṃ vasvādi devarūpiṇaṃ somapāḥ somaṃ pibantīti somapāḥ, tenaiva somapānena pūtapāpāḥ śuddhakilbiṣāḥ, yajñai ragniṣṭomādibhi riṣṭvā pūjayitvā, svargatim svargagamanaṃ svareva gatiḥ svargatiḥ tāṃ, prārthayante, te ca puṇyaṃ puṇyaphalamāsādya samprāpya surendralokaṃ śatakratoḥ sthānaṃ aśnanti bhuñjate divyān divi bhavān aprākṛtān devabhogān devānāṃ bhogaḥ devabhogaḥ tān.", "tr": "Knowers of the three Vedas — the Ṛk, Yajus and Sāman — having worshipped me, in the form of the Vasus and other gods, with sacrifices such as the agniṣṭoma; soma-drinkers — those who drink soma — their sins purified by that soma-drinking, their stain cleansed; they pray for the way to heaven — going to heaven, heaven itself being the way. And they, reaching, attaining, merit, the fruit of merit, the world of the lord of the gods, the abode of Indra of a hundred sacrifices, enjoy, partake of, the divine — heavenly, not of this world — enjoyments of the gods."},
           ],
           words=[
               ["trai-vidyāḥ", "knowers of the three Vedas"],
               ["mām", "me"],
               ["soma-pāḥ", "soma-drinkers"],
               ["pūta-pāpāḥ", "purified of sin"],
               ["yajñaiḥ", "with sacrifices"],
               ["iṣṭvā", "having worshipped"],
               ["svaḥ-gatim", "the way to heaven"],
               ["prārthayante", "pray for"],
               ["te", "they"],
               ["puṇyam", "the meritorious"],
               ["āsādya", "reaching"],
               ["sura-indra-lokam", "world of the lord of the gods"],
               ["aśnanti", "enjoy"],
               ["divyān", "divine"],
               ["divi", "in heaven"],
               ["deva-bhogān", "the enjoyments of the gods"],
           ]),
        _v([
            "te taṃ bhuktvā svargalokaṃ viśālaṃ kṣīṇe puṇye martyalokaṃ viśanti |",
            "evaṃ trayīdharmamanuprapannā gatāgataṃ kāmakāmā labhante",
        ], "|| 21 ||",
           "Having enjoyed that vast world of heaven, their merit exhausted, they enter the world of mortals. Thus following the dharma of the three Vedas and desiring desires, they gain what comes and goes.",
           bhashya=[
               {"text": "te taṃ bhuktvā svargalokaṃ viśālaṃ vistīrṇaṃ kṣīṇe puṇye martyalokaṃ viśanti āviśanti. evaṃ yathoktena prakāreṇa, trayīdharmaṃ kevalaṃ vaidikaṃ karma anuprapannāḥ gatāgataṃ gataṃ ca āgataṃ ca gatāgataṃ gamanāgamanaṃ kāmakāmāḥ kāmān kāmayante iti kāmakāmāḥ labhante gatāgatameva, na tu svātantryaṃ kvacillabhante ityarthaḥ.", "tr": "Having enjoyed that vast, wide, world of heaven, when their merit is exhausted they enter the world of mortals. Thus, in the way described, following the dharma of the three Vedas — mere Vedic ritual — men who desire desires obtain going and coming; they obtain only going and coming, never independence anywhere — that is the meaning."},
           ],
           words=[
               ["te", "they"],
               ["tam", "that"],
               ["bhuktvā", "having enjoyed"],
               ["svarga-lokam", "world of heaven"],
               ["viśālam", "vast"],
               ["kṣīṇe", "when is exhausted"],
               ["puṇye", "merit"],
               ["martya-lokam", "the world of mortals"],
               ["viśanti", "they enter"],
               ["evam", "thus"],
               ["trayī-dharmam", "the dharma of the three Vedas"],
               ["anuprapannāḥ", "following"],
               ["gata-āgatam", "going and coming"],
               ["kāma-kāmāḥ", "desiring desires"],
               ["labhante", "they obtain"],
           ]),
        _v([
            "ananyāścintayanto māṃ ye janāḥ paryupāsate |",
            "teṣāṃ nityābhiyuktānāṃ yogakṣemaṃ vahāmyaham",
        ], "|| 22 ||",
           "Those who worship me, thinking of no other, ever disciplined — their welfare I carry.",
           bhashya=[
               {"text": "ye punarniṣkāmāssamyagdarśinaḥ –", "intro": True, "tr": "But those free from desire, with right vision —"},
               {"text": "ananyāḥ apṛthagbhūtāḥ paraṃ devaṃ nārāyaṇaṃ ātmatvena gatāssantaścintayanto māṃ ye janāḥ sannyāsinaḥ paryupāsate, teṣāṃ paramārthadarśināṃ nityābhiyuktānāṃ, satatābhiyogināṃ yogakṣemaṃ yogaḥ aprāptasya prāpaṇaṃ, kṣemaḥ tadrakṣaṇaṃ, tadubhayaṃ vahāmi prāpayāmyahaṃ, jñānī tvātmaiva me matam “sa ca me priyaḥ” (7.17.18) yasmāt tasmāt te mamātmabhūtāḥ priyāśca iti. nanu anyeṣāmapi bhaktānāṃ yogakṣemaṃ vahatyeva bhagavān. satyaṃ vahatyeva, kiṃ tvaṃ viśeṣaḥ – anye ye bhaktāste ātmārthaṃ svayamapi yogakṣemaṃ īhante, ananyadarśinastu nātmārthaṃ yogakṣemamīhante, na hi te jīvite maraṇe vā ātmano gṛddhiṃ kurvanti, kevalameva bhagavaccharaṇāḥ te, ataḥ bhagavāneva yogakṣemaṃ vahatīti.", "tr": "The people, the renouncers, who, not other — not separate from the supreme god Nārāyaṇa, having come to him as their Self — meditating on me, worship me — of those seers of the supreme truth, ever steadfast, continually devoted, I bring the yoga and kṣema: yoga is the gaining of what one lacks, kṣema the preserving of it; both of these I bring, procure. Since 'the man of knowledge is my very Self' and 'he is dear to me' (7.17–18), they are my Self and dear to me. Objection: but the Lord surely brings yoga and kṣema to other devotees too. True, he does; but this is the difference: other devotees also seek yoga and kṣema for themselves, but those who see nothing other do not seek yoga and kṣema for themselves, for they have no craving for their own life or death; they have the Lord alone as their refuge. So the Lord himself brings them yoga and kṣema."},
           ],
           words=[
               ["ananyāḥ", "with no other"],
               ["cintayantaḥ", "thinking of"],
               ["mām", "me"],
               ["ye", "which"],
               ["janāḥ", "people"],
               ["paryupāsate", "worship"],
               ["teṣām", "of them"],
               ["nitya-abhiyuktānām", "ever steadfast"],
               ["yoga-kṣemam", "the gaining and keeping"],
               ["vahāmi", "bring"],
               ["aham", "I"],
           ]),
        _v([
            "ye'pyanyadevatābhaktā yajante śraddhayā'nvitāḥ |",
            "te'pi māmeva kaunteya yajantyavidhipūrvakam",
        ], "|| 23 ||",
           "Even those devotees who worship other gods with faith worship me alone, son of Kuntī, though not according to the rule.",
           bhashya=[
               {"text": "nanu anyā api devatāḥ tvameva cet, tadbhaktāśca tvāmeva bhajante satyaṃ evaṃ –", "intro": True, "tr": "If other deities too are you yourself, then their devotees too worship you alone. True, it is so —"},
               {"text": "ye'pi anyadevatābhaktāḥ anyāsu devatāsu bhaktāḥ anyadevatābhaktāḥ santaḥ yajante pūjayanti śraddhayā āstikyabuddhyā, anvitāḥ anugatāḥ, te'pi māmeva kaunteya yajanti avidhipūrvakaṃ, avidhiḥ ajñānaṃ tatpūrvakaṃ yajante ityarthaḥ.", "tr": "Even those who, devoted to other deities, worship, honour, them, endowed with, accompanied by, faith, belief in the unseen — they too worship me alone, Kaunteya, but not according to the rule: not according to rule means in ignorance; they worship preceded by ignorance, that is."},
           ],
           words=[
               ["ye", "who"],
               ["api", "even"],
               ["anya-devatā-bhaktāḥ", "devoted to other deities"],
               ["yajante", "worship"],
               ["śraddhayā", "with faith"],
               ["anvitāḥ", "endowed"],
               ["te", "they"],
               ["api", "too"],
               ["mām", "me"],
               ["eva", "alone"],
               ["kaunteya", "O son of Kuntī"],
               ["yajanti", "worship"],
               ["avidhi-pūrvakam", "not according to rule"],
           ]),
        _v([
            "ahaṃ hi sarvayajñānāṃ bhoktā ca prabhureva ca |",
            "na tu māmabhijānanti tattvenātaścyavanti te",
        ], "|| 24 ||",
           "For I am the enjoyer and the lord of all sacrifices. But they do not know me in truth, and so they fall.",
           bhashya=[
               {"text": "kasmāt te avidhipūrvakaṃ yajante ityucyate, yasmāt –", "intro": True, "tr": "Why do they worship not according to rule? It is said: because —"},
               {"text": "ahiṃ hi sarvayajñānāṃ śrautānāṃ smārtānāṃ ca sarveṣāṃ devatātmatvena bhoktā ca prabhureva ca. matsvāmiko yajñaḥ, “adhiyajño'hamevātra” (8.4) iti hyuktaṃ tathā na tu māmabhijānanti tattvena yathāvat. ataśca avidhipūrvakamiṣṭvā yāgaphalāt cyavanti pracyavante te.", "tr": "For I am the enjoyer of all sacrifices, those of śruti and smṛti, all of them, as the self of the deities, and the lord too: the sacrifice has me as its lord, for it has been said, 'I myself am the adhiyajña here' (8.4). But they do not know me in truth, as I am; and therefore, having sacrificed not according to rule, they fall, drop away, from the fruit of the sacrifice."},
           ],
           words=[
               ["aham", "I"],
               ["hi", "for"],
               ["sarva-yajñānām", "of all sacrifices"],
               ["bhoktā", "the enjoyer"],
               ["ca", "and"],
               ["prabhuḥ", "the lord"],
               ["eva ca", "and also"],
               ["na", "not"],
               ["tu", "but"],
               ["mām", "me"],
               ["abhijānanti", "they know"],
               ["tattvena", "in truth"],
               ["ataḥ", "therefore"],
               ["cyavanti", "fall"],
               ["te", "they"],
           ]),
        _v([
            "yānti devavratā devān pitṝn yānti pitṛvratāḥ |",
            "bhūtāni yānti bhūtejyāḥ yānti madyājino'pi mām",
        ], "|| 25 ||",
           "Those devoted to the gods go to the gods; those devoted to the ancestors go to the ancestors; those who sacrifice to spirits go to the spirits; and those who worship me come to me.",
           bhashya=[
               {"text": "ye'pyanyadevatābhaktimatvenāvidhipūrvakaṃ yajante teṣāmapi yāgaphala mavaśyambhāvi. kathaṃ?", "intro": True, "tr": "Even for those who, devoted to other deities, worship not according to rule, the fruit of the sacrifice is certain. How?"},
               {"text": "yānti gacchanti devavratāḥ deveṣu vrataṃ niyamo bhaktiśca yeṣāṃ te devavratāḥ devān. yānti pitṝn agniṣvāttādīn yānti pitṛvratāḥ śrāddhādikriyāparāḥ pitṛbhaktāḥ. bhūtāni vināyaka mātṛgaṇa caturbhaginyādīni yānti bhūtejyāḥ bhūtānāṃ pūjakāḥ. yānti madyājinaḥ madyajanaśīlāḥ vaiṣṇavāḥ māmeva yānti, samāne'pyāyāse māmeva na bhajante ajñānāt, tena te alpaphalabhājaḥ bhavanti ityarthaḥ.", "tr": "Those vowed to the gods — whose vow, observance and devotion are directed to the gods — go to the gods. Those vowed to the ancestors — devoted to the ancestors, intent on śrāddha and other rites — go to the ancestors, the Agniṣvāttas and the rest. Worshippers of spirits go to the spirits, Vināyaka, the hosts of Mothers, the Four Sisters and the like. Those who sacrifice to me — given to worshipping me, Vaiṣṇavas — come to me alone. Though the effort is the same, out of ignorance they do not worship me alone, and so they gain a small fruit — that is the meaning."},
           ],
           words=[
               ["yānti", "go"],
               ["deva-vratāḥ", "those vowed to the gods"],
               ["devān", "to the gods"],
               ["pitṝn", "to the ancestors"],
               ["yānti", "go"],
               ["pitṛ-vratāḥ", "those vowed to the ancestors"],
               ["bhūtāni", "to the spirits"],
               ["yānti", "go"],
               ["bhūta-ijyāḥ", "worshippers of spirits"],
               ["yānti", "come"],
               ["mat-yājinaḥ", "those who sacrifice to me"],
               ["api", "too"],
               ["mām", "to me"],
           ]),
        _v([
            "patraṃ puṣpaṃ phalaṃ toyaṃ yo me bhaktyā prayacchati |",
            "tadahaṃ bhaktyupahṛtamaśnāmi prayatātmanaḥ",
        ], "|| 26 ||",
           "Whoever offers me with devotion a leaf, a flower, a fruit or water — that offering of devotion from one pure of heart I accept.",
           bhashya=[
               {"text": "na kevalaṃ madbhaktānāmanāvṛttilakṣaṇamanantaphalaṃ, sukhārādhanaścāhaṃ, kathaṃ?", "intro": True, "tr": "Not only is the fruit of my devotees endless, consisting in non-return; I am also easy to worship. How?"},
               {"text": "patraṃ puṣpaṃ phalaṃ toyamudakaṃ yaḥ me mahyaṃ bhaktyā prayacchati, tadahaṃ patrādi upahṛtaṃ bhaktipūrvakaṃ prāpitaṃ bhaktyupahṛtaṃ, aśnāmi gṛhṇāmi, prayatātmanaḥ śuddhabuddheḥ. yata evaṃ ataḥ –", "tr": "Whoever offers me with devotion a leaf, a flower, a fruit, water — that leaf or other thing, offered with devotion, brought to me with devotion, I accept, receive, from one whose self is pure, whose understanding is pure. Since this is so —"},
           ],
           words=[
               ["patram", "a leaf"],
               ["puṣpam", "a flower"],
               ["phalam", "a fruit"],
               ["toyam", "water"],
               ["yaḥ", "who"],
               ["me", "to me"],
               ["bhaktyā", "with devotion"],
               ["prayacchati", "offers"],
               ["tat", "that"],
               ["aham", "I"],
               ["bhakti-upahṛtam", "offered with devotion"],
               ["aśnāmi", "accept"],
               ["prayata-ātmanaḥ", "from the pure of heart"],
           ]),
        _v([
            "yatkaroṣi yadaśnāsi yajjuhoṣi dadāsi yat |",
            "yattapasyasi kaunteya tatkuruṣva madarpaṇam",
        ], "|| 27 ||",
           "Whatever you do, whatever you eat, whatever you offer in sacrifice, whatever you give, whatever austerity you practise, son of Kuntī — do it as an offering to me.",
           bhashya=[
               {"text": "yatkaroṣi, svataḥ prāptaṃ, yadaśnāsi, yacca juhoṣi havanaṃ nirvartayasi śrautaṃ smārtaṃ vā, yaddadāsi prayacchasi brāhmaṇādibhyaḥ hiraṇyānnājyādi, yattapasyasi tapaḥ carasi, kaunteya, tatkuruṣva madarpaṇaṃ matsamarpaṇam.", "tr": "Whatever you do of your own accord, whatever you eat, whatever you offer in sacrifice — the oblation you perform, Vedic or smārta — whatever you give, gold, food, ghee and the like to brāhmaṇas and others, whatever austerity you practise, Kaunteya — do that as an offering to me, dedicated to me."},
           ],
           words=[
               ["yat", "whatever"],
               ["karoṣi", "you do"],
               ["yat", "whatever"],
               ["aśnāsi", "you eat"],
               ["yat", "whatever"],
               ["juhoṣi", "you offer in sacrifice"],
               ["dadāsi", "you give"],
               ["yat", "whatever"],
               ["yat", "whatever"],
               ["tapasyasi", "austerity you practise"],
               ["kaunteya", "O son of Kuntī"],
               ["tat", "that"],
               ["kuruṣva", "do"],
               ["mat-arpaṇam", "as an offering to me"],
           ]),
        _v([
            "śubhāśubhaphalairevaṃ mokṣyase karmabandhanaiḥ |",
            "sannyāsayogayuktātmā vimukto māmupaiṣyasi",
        ], "|| 28 ||",
           "Thus you will be freed from the bonds of action, with their good and evil fruits. With your self disciplined in the yoga of renunciation, released, you will come to me.",
           bhashya=[
               {"text": "evaṃ kurvatastava yadbhavati, tacchṛṇu –", "intro": True, "tr": "Hear what comes to you when you do so:"},
               {"text": "śubhāśubhaphalaiḥ śubhāśubhe iṣṭāniṣṭe phale yeṣāṃ tāni śubhāśubhaphalāni karmāṇi taiḥ śubhāśubhaphalaiḥ karmabandhanaiḥ karmāṇyeva bandhanāni karmabandhanāni taiḥ karmabandhanaiḥ evaṃ madarpaṇaṃ kurvan mokṣyase. so'yaṃ sannyāsayogo nāma, sannyāsaśca asau matsamarpaṇatayā karmatvādyogaśca asau iti, tena sannyāsayogena yuktaḥ ātmā antaḥ karaṇaṃ yasya tava saḥ tvaṃ sannyāsayogayuktātmā san, vimukto karmabandhanaiḥ jīvanneva patite cāsmin śarīre māmupaiṣyasi āgamiṣyasi.", "tr": "From good and evil fruits: actions whose fruits are good and evil, desired and undesired — from those bonds of action, actions themselves being bonds — you will be freed, doing thus the offering to me. This is called the yoga of renunciation: it is renunciation, being dedication to me, and it is yoga, being action. You, whose self, inner organ, is joined with that yoga of renunciation, freed from the bonds of action while still living, will come to me when this body falls."},
           ],
           words=[
               ["śubha-aśubha-phalaiḥ", "with good and evil fruits"],
               ["evam", "thus"],
               ["mokṣyase", "you will be freed"],
               ["karma-bandhanaiḥ", "from the bonds of action"],
               ["sannyāsa-yoga-yukta-ātmā", "with the self joined to the yoga of renunciation"],
               ["vimuktaḥ", "freed"],
               ["mām", "to me"],
               ["upaiṣyasi", "you will come"],
           ]),
        _v([
            "samo'haṃ sarvabhūteṣu na me dveṣyo'sti na priyaḥ |",
            "ye bhajanti tu māṃ bhaktyā mayi te teṣu cā'pyaham",
        ], "|| 29 ||",
           "I am the same in all beings; none is hateful to me and none dear. But those who worship me with devotion are in me, and I too am in them.",
           bhashya=[
               {"text": "rāgadveṣavān tarhi bhagavān, yato bhaktān anugṛhṇāti, netarāniti. tanna.", "intro": True, "tr": "Then the Lord has attachment and aversion, since he favours his devotees and not others. That is not so."},
               {"text": "samaḥ tulyaḥ ahaṃ sarvabhūteṣu, na me dveṣyo'sti na priyaḥ agnivadahaṃ dūrasthānāṃ yathāgniḥ śītaṃ nāpanayati, samīpamupasarpatāmapanayati, tathāhaṃ bhaktānanugṛhṇāmi, netarān, ye bhajanti tu māmīśvaraṃ bhaktyā, mayi te svabhāvata eva, na mama rāganimittaṃ vartante. teṣu cāpyahaṃ svabhāvata eva varte, netareṣu, naitāvatā teṣu dveṣo mama.", "tr": "I am the same, equal, in all beings; there is none hateful to me, none dear. I am like fire: as fire does not remove the cold of those who stay far off but removes it for those who come near, so I favour my devotees and not others. But those who worship me, the Lord, with devotion are in me by their very nature, not through any attachment of mine; and I too am in them by nature, not in others. Not for that is there aversion in me towards them."},
           ],
           words=[
               ["samaḥ", "the same"],
               ["aham", "I"],
               ["sarva-bhūteṣu", "in all beings"],
               ["na", "not"],
               ["me", "to me"],
               ["dveṣyaḥ", "hateful"],
               ["asti", "is"],
               ["na", "nor"],
               ["priyaḥ", "dear"],
               ["ye", "who"],
               ["bhajanti", "worship"],
               ["tu", "but"],
               ["mām", "me"],
               ["bhaktyā", "with devotion"],
               ["mayi", "in me"],
               ["te", "they"],
               ["teṣu", "in them"],
               ["ca", "and"],
               ["api", "also"],
               ["aham", "I"],
           ]),
        _v([
            "api cetsudurācāro bhajate māmananyabhāk |",
            "sādhureva sa mantavyaḥ samyagvyavasito hi saḥ",
        ], "|| 30 ||",
           "Even if a man of very wicked conduct worships me with undivided devotion, he must be regarded as good, for he has resolved rightly.",
           bhashya=[
               {"text": "śṛṇu madbhaktermāhātmyam –", "intro": True, "tr": "Hear the greatness of devotion to me:"},
               {"text": "api cet yadyapi sudurācāraḥ suṣṭhu durācāraḥ atīva kutsitācāropi, bhajate māmananyabhāk. ananyabhaktissan, sādhureva samyagvṛtta eva saḥ mantavyaḥ, jñātavyaḥ, samyak yathāvat vyavasito hi saḥ, yasmātsādhuniścayassaḥ.", "tr": "Even if one of very bad conduct — of exceedingly bad, utterly contemptible conduct — worships me with undivided devotion, being devoted to no other, he must be regarded, known, as good, of right conduct; for he has resolved rightly, as he should — since his resolve is good."},
           ],
           words=[
               ["api cet", "even if"],
               ["su-durācāraḥ", "one of very bad conduct"],
               ["bhajate", "worships"],
               ["mām", "me"],
               ["ananya-bhāk", "with undivided devotion"],
               ["sādhuḥ", "good"],
               ["eva", "indeed"],
               ["saḥ", "he"],
               ["mantavyaḥ", "must be regarded"],
               ["samyak", "rightly"],
               ["vyavasitaḥ", "resolved"],
               ["hi", "for"],
               ["saḥ", "he"],
           ]),
        _v([
            "kṣipraṃ bhavati dharmātmā śaśvacchāntiṃ nigacchati |",
            "kaunteya pratijānīhi na me bhaktaḥ praṇaśyati",
        ], "|| 31 ||",
           "Quickly he becomes righteous and attains lasting peace. Son of Kuntī, know for certain that my devotee does not perish.",
           bhashya=[
               {"text": "utsṛjya bāhyāṃ durācāratāṃ antassamyagvyavasāyasāmarthyāt–", "intro": True, "tr": "Giving up his outer bad conduct by the strength of his right inner resolve —"},
               {"text": "kṣipraṃ śīghraṃ bhavati dharmātmā dharmacittaḥ eva. śaśvannityaṃ śāntiṃ ca upaśamaṃ nigacchati, prāpnoti. śṛṇu paramārthaṃ, he kaunteya pratijānīhi niścitāṃ pratijñāṃ kuru, na me mama bhaktaḥ mayi samarpitāntarātmā madbhaktaḥ na praṇaśyati iti. kiñca–", "tr": "Quickly, soon, he becomes righteous, of righteous mind, and attains, reaches, lasting, perpetual, peace, quietude. Hear the supreme truth: Kaunteya, declare it — make a firm promise — that my devotee, whose inner self is dedicated to me, does not perish. Moreover —"},
           ],
           words=[
               ["kṣipram", "quickly"],
               ["bhavati", "he becomes"],
               ["dharma-ātmā", "righteous"],
               ["śaśvat", "lasting"],
               ["śāntim", "peace"],
               ["nigacchati", "attains"],
               ["kaunteya", "O son of Kuntī"],
               ["pratijānīhi", "declare"],
               ["na", "not"],
               ["me", "my"],
               ["bhaktaḥ", "devotee"],
               ["praṇaśyati", "perishes"],
           ]),
        _v([
            "māṃ hi pārtha vyapāśritya ye'pi syuḥ pāpayonayaḥ |",
            "striyo vaiśyāstathā śūdrāste'pi yānti parāṃ gatim",
        ], "|| 32 ||",
           "For those who take refuge in me, Pārtha, even those of low birth — women, vaiśyas and śūdras — also reach the highest goal.",
           bhashya=[
               {"text": "māṃ hi yasmāt pārtha vyapāśritya mamāśrayatvena gṛhītvā ye'pi syuḥ bhaveyuḥ pāpayonayaḥ pāpayoniḥ yeṣāṃ te pāpayonayaḥ pāpajanmānaḥ ke te iti, āha striyaḥ vaiśyāḥ tathā śūdrāḥ te'pi yānti gacchanti parāṃ prakṛṣṭāṃ gatim.", "tr": "For, Pārtha, taking refuge in me — taking me as their refuge — even those who may be of sinful birth — whose womb is sinful, born in sin — who are they? He says: women, vaiśyas, likewise śūdras — even they go to the supreme, the highest, goal."},
           ],
           words=[
               ["mām", "in me"],
               ["hi", "for"],
               ["pārtha", "O Pārtha"],
               ["vyapāśritya", "taking refuge"],
               ["ye", "who"],
               ["api", "even"],
               ["syuḥ", "may be"],
               ["pāpa-yonayaḥ", "of sinful birth"],
               ["striyaḥ", "women"],
               ["vaiśyāḥ", "vaiśyas"],
               ["tathā", "likewise"],
               ["śūdrāḥ", "śūdras"],
               ["te", "they"],
               ["api", "too"],
               ["yānti", "go"],
               ["parām", "to the supreme"],
               ["gatim", "goal"],
           ]),
        _v([
            "kiṃ punarbrāhmaṇāḥ puṇyā bhaktā rājarṣayastathā |",
            "anityamasukhaṃ lokamimaṃ prāpya bhajasva mām",
        ], "|| 33 ||",
           "How much more, then, holy brāhmaṇas and devoted royal sages! Having come into this transient, joyless world, worship me.",
           bhashya=[
               {"text": "kiṃ punaḥ brāhmaṇāḥ puṇyāḥ puṇyayonayaḥ bhaktā rājarṣayaḥ tathā rājānaśca te ṛṣayaśca rājarṣayaḥ. yataḥ evam ataḥ anityaṃ kṣaṇabhaṅguraṃ asukhaṃ ca sukhavarjitamimaṃ lokaṃ manuṣyalokaṃ prāpya puruṣārthasādhanaṃ durlabhaṃ manuṣyatvaṃ labdhvā bhajasva sevasva mām. katham?", "tr": "How much more, then, holy brāhmaṇas, of holy birth, and devoted royal sages — those who are kings and sages. Since this is so, having come to this world, the world of men, impermanent, perishing in a moment, and joyless, devoid of happiness — having gained the human birth so hard to obtain, the means of the human ends — worship, serve, me. How?"},
           ],
           words=[
               ["kim punaḥ", "how much more"],
               ["brāhmaṇāḥ", "brāhmaṇas"],
               ["puṇyāḥ", "holy"],
               ["bhaktāḥ", "devoted"],
               ["rāja-ṛṣayaḥ", "royal sages"],
               ["tathā", "likewise"],
               ["anityam", "impermanent"],
               ["asukham", "joyless"],
               ["lokam", "world"],
               ["imam", "this"],
               ["prāpya", "having come to"],
               ["bhajasva", "worship"],
               ["mām", "me"],
           ]),
        _v([
            "manmanā bhava madbhakto madyājī māṃ namaskuru |",
            "māmevaiṣyasi yuktvaivamātmānaṃ matparāyaṇaḥ",
        ], "|| 34 ||",
           "Fix your mind on me, be devoted to me, sacrifice to me, bow down to me. Thus disciplining yourself, with me as your highest goal, you will come to me.",
           bhashya=[
               {"text": "manmanā yiti. mayi vāsudeve manaḥ yasya tava sa tvaṃ manmanāḥ bhava. tathā madbhaktaḥ bhava. madyājī madyajanaśīlaḥ bhava. māṃ eva namaskuru. māṃ eva īśvaraṃ eṣyasi āgamiṣyasi yuktvā samādhāya cittaṃ, evaṃ ātmānaṃ māṃ – ahaṃ hi sarveṣāṃ bhūtānāṃ ātmā, parā ca gatiḥ, paraṃ ayanam. taṃ māṃ evaṃ bhūtaṃ eṣyasi yiti atītena sambandhaḥ matparāyaṇaḥ san ityarthaḥ.", "tr": "'Fix your mind on me…' Be one whose mind is on me, Vāsudeva; likewise be devoted to me; be one who sacrifices to me, given to worshipping me; bow down to me alone. You will come to me alone, the Lord, having disciplined, collected, your mind thus — to me, the Self: for I am the Self of all beings and the supreme goal, the highest resort. To me, being such, you will come — it connects with what went before — being intent on me, that is."},
           ],
           words=[
               ["mat-manāḥ", "with mind on me"],
               ["bhava", "be"],
               ["mat-bhaktaḥ", "devoted to me"],
               ["mat-yājī", "sacrificing to me"],
               ["mām", "to me"],
               ["namaskuru", "bow down"],
               ["mām", "to me"],
               ["eva", "alone"],
               ["eṣyasi", "you will come"],
               ["yuktvā", "having disciplined"],
               ["evam", "thus"],
               ["ātmānam", "yourself"],
               ["mat-parāyaṇaḥ", "intent on me"],
           ]),
        "ornament",
        {"colophon": "iti śrīmahābhārate śatasāhasryāṃ saṃhitāyāṃ vaiyāsikyāṃ bhīṣmaparvaṇi śrīmadbhagavadgītā – sūpaniṣatsu brahmavidyāyāṃ yogaśāstre śrīkṛṣṇārjunasaṃvāde rājavidyā rājaguhyayogo nāma navamo'dhyāyaḥ.", "gloss": "Thus, in the Bhagavad Gītā — the Upaniṣad, the knowledge of Brahman, the scripture of yoga, the dialogue of Śrī Kṛṣṇa and Arjuna — within the Bhīṣma Parva of the Mahābhārata, the collection of a hundred thousand verses by Vyāsa, ends the ninth chapter, Rājavidyārājaguhya Yoga."},
        {"colophon": "iti śrīmatparamahaṃsaparivrājakācārya govindabhagavatpūjyapādaśiṣya śrīmacchaṅkarabhagavataḥ kṛtau śrīmadbhagavadgītābhāṣye rājavidyā 'rājaguhyayogo nāma navamo'dhyāyaḥ.", "gloss": "Thus ends the ninth chapter, Rājavidyārājaguhya Yoga, of the commentary on the Bhagavad Gītā composed by Śrī Śaṅkara Bhagavat, wandering ascetic of the highest order and disciple of Śrī Govinda Bhagavatpāda."},
    ],
}
