# -*- coding: utf-8 -*-
# Copyright 2026 Pradyumna Revur — CC BY 4.0 (see LICENSE)
# Bhagavad Gītā, chapter 7 (Jñānavijñāna Yoga), with Śaṅkara's bhāṣya. The Sanskrit
# (mūla and bhāṣya, both public domain) is converted from the text layer of
# the Ramakrishna Math, Hyderabad edition (2013), whose legacy Telugu font was
# mapped to Unicode glyph by glyph; its Telugu translation is not used. Collated
# against Sanskrit Wikisource and the Pullela Śrīrāmacandruḍu edition; every
# correction is logged in SOURCES §7.4. The English of the verses and of the
# bhāṣya is original, made from the Sanskrit. Generated from the collated text — edit here, not
# upstream.


def _v(padas, num, gloss, bhashya=None, words=None):
    d = {"padas": padas, "num": num, "gloss": gloss}
    if bhashya:
        d["bhashya"] = bhashya
    if words:
        d["words"] = words
    return d


STOTRA = {
    "deity": "gita",
    "doc_title": "Bhagavad Gītā 7 · Jñānavijñāna Yoga · Śaṅkara Bhāṣya",
    "app_title": "Gītā 7",
    "h1": "Bhagavad Gītā · Chapter 7",
    "subtitle": "Jñānavijñāna Yoga · knowledge and realisation · with Śaṅkara's bhāṣya",
    "note": "Kṛṣṇa speaks of his two natures, the lower eightfold prakṛti and the higher, the life-principle; of himself as the essence in all things; of māyā, hard to cross; and of the four kinds of devotees, among whom the knower is his very Self.",
    "footer": "Source: Śrīmad Bhagavadgītā Śaṅkarabhāṣyamu (Ramakrishna Math, Hyderabad, 2013), Sanskrit mūla and bhāṣya only, collated with Sanskrit Wikisource and the Pullela Śrīrāmacandruḍu edition; translations original. See SOURCES §7.4.",
    "nav": [('‹ chapter 6', 'gita-bhashya-06-iast.html'), ('all chapters', '../../index.html#gita'), ('chapter 8 ›', 'gita-bhashya-08-iast.html')],
    "sections": [
        {"bhashya": [
            {"text": "“yogināmapi sarveṣāṃ madgatenāntarātmanā. śraddhāvān bhajate yo māṃ sa me yuktatamo mataḥ” (6.47) iti praśnabījaṃ upanyasya svayameva “īdṛśaṃ madīyaṃ tattvaṃ, evaṃ madgatāntarātmā syāt” ityetat vivakṣuḥ śrībhagavān uvāca–", "tr": "Having set down the seed of a question with 'and of all yogins, he who, full of faith, worships me with his inner self gone to me, him I hold the most disciplined' (6.47), the Blessed Lord, wishing to tell of his own accord 'such is my reality, and thus should one's inner self be gone to me', said:"},
        ], "summary": "bhāṣya · the chapter's opening"},
        _v([
            "mayyāsaktamanāḥ pārtha yogaṃ yuñjan madāśrayaḥ |",
            "asaṃśayaṃ samagraṃ māṃ yathā jñāsyasi tacchṛṇu",
        ], "|| 1 ||",
           "The Blessed Lord said: Hear, Pārtha, how, with your mind attached to me, practising yoga and taking refuge in me, you will know me fully and without doubt.",
           bhashya=[
               {"text": "mayyāsaktamanā iti. mayi vakṣyamāṇa viśeṣaṇe parameśvare āsaktaṃ mano yasya sa mayyāsaktamanāḥ, he pārtha! yogaṃ yuñjan manaḥ samādhānaṃ kurvan madāśrayaḥ ahameva parameśvaraḥ āśrayaḥ yasya sa madāśrayaḥ. yo hi kaścit puruṣārthena kenacit, arthī bhavati sa tatsādhanaṃ karma agnihotrādi tapaḥ dānaṃ vā kiñcit āśrayaṃ pratipadyate, ayaṃ tu yogī māmeva āśrayaṃ pratipadyate, hitvā anyat sādhanāntaraṃ mayyeva āsaktamanāḥ bhavati. yaḥ tvaṃ evambhūtaḥ san asaṃśayaṃ samagraṃ samasta vibhūti balaśakyaiśvaryādi guṇasampannaṃ māṃ yathā yena prakāreṇa jñāsyasi saṃśayamantareṇa “evameva bhagavān” iti tat śṛṇu ucyamānaṃ mayā.", "tr": "'With your mind attached to me…' He whose mind is attached to me, the supreme Lord with the attributes to be described, Pārtha; practising yoga, collecting the mind; taking refuge in me — he whose refuge is I alone, the supreme Lord. Whoever seeks some human end takes as his refuge some action that is its means, the agnihotra, austerity or charity; but this yogin takes me alone as his refuge, and giving up every other means, his mind is attached to me alone. Hear, as I tell it, how you, being such, will know me without doubt and entirely — endowed with all the qualities, glory, strength, power, sovereignty and the rest — free of doubt, knowing 'the Lord is just so'."},
           ],
           words=[
               ["mayi", "to me"],
               ["āsakta-manāḥ", "with mind attached"],
               ["pārtha", "O Pārtha"],
               ["yogam", "yoga"],
               ["yuñjan", "practising"],
               ["mat-āśrayaḥ", "taking refuge in me"],
               ["asaṃśayam", "without doubt"],
               ["samagram", "entirely"],
               ["mām", "me"],
               ["yathā", "how"],
               ["jñāsyasi", "you will know"],
               ["tat", "that"],
               ["śṛṇu", "hear"],
           ]),
        _v([
            "jñānaṃ te'haṃ savijñānamidaṃ vakṣyāmyaśeṣataḥ |",
            "yad jñātvā neha bhūyo'nyat jñātavyamavaśiṣyate",
        ], "|| 2 ||",
           "I will teach you this knowledge together with realisation, without remainder; knowing it, nothing further remains here to be known.",
           bhashya=[
               {"text": "tacca madviṣayam–", "intro": True, "tr": "And that concerning me —"},
               {"text": "jñānaṃ iti. jñānaṃ te tubhyaṃ ahaṃ savijñānaṃ vijñānasahitaṃ svānubhavayuktaṃ idaṃ vakṣyāmi kathayiṣyāmi aśeṣataḥ kārtsnyena. tat jñānaṃ vivakṣitaṃ stauti śrotuḥ abhimukhīkaraṇāya– yat jñātvā yat jñānaṃ jñātvā na iha bhūyaḥ punaḥ anyat jñātavyaṃ puruṣārthasādhanaṃ avaśiṣyate na avaśiṣṭaṃ bhavati – iti mattattvajño yaḥ, sa sarvajño bhavatītyarthaḥ. ato viśiṣṭaphalatvāt durlabhataraṃ jñānam.", "tr": "'I will tell you this knowledge together with realisation…' I will tell you, declare to you, this knowledge together with realisation — joined with one's own experience — entirely, in full. He praises the knowledge he intends to tell, to make the hearer attentive: knowing which, having known which knowledge, nothing else remains here, again, to be known as a means to a human end. One who knows my reality becomes all-knowing — that is the meaning. So, having a superior fruit, this knowledge is very hard to gain."},
           ],
           words=[
               ["jñānam", "knowledge"],
               ["te", "to you"],
               ["aham", "I"],
               ["sa-vijñānam", "together with realisation"],
               ["idam", "this"],
               ["vakṣyāmi", "will tell"],
               ["aśeṣataḥ", "in full"],
               ["yat", "which"],
               ["jñātvā", "knowing"],
               ["na", "not"],
               ["iha", "here"],
               ["bhūyaḥ", "further"],
               ["anyat", "anything else"],
               ["jñātavyam", "to be known"],
               ["avaśiṣyate", "remains"],
           ]),
        _v([
            "manuṣyāṇāṃ sahasreṣu kaścidyatati siddhaye |",
            "yatatāmapi siddhānāṃ kaścinmāṃ vetti tattvataḥ",
        ], "|| 3 ||",
           "Among thousands of men, hardly one strives for perfection; and among those who strive and are perfected, hardly one knows me in truth.",
           bhashya=[
               {"text": "kathaṃ iti? ucyate –", "intro": True, "tr": "How? It is said:"},
               {"text": "manuṣyāṇāṃ iti. manuṣyāṇāṃ madhye sahasreṣu anekeṣu kaścit yatati prayatnaṃ karoti siddhaye siddhyartham. teṣāṃ yatatām api siddhānāṃ – siddhāḥ eva hi te ye mokṣāya yatante, teṣāṃ – kaścit eva hi māṃ vetti tattvataḥ yathāvat.", "tr": "'Among thousands of men…' Among men, in many thousands, someone strives, makes effort, for perfection, for the sake of perfection. Even among those who strive and are perfected — those who strive for liberation are indeed the perfected ones — of them only someone knows me in truth, as I am."},
           ],
           words=[
               ["manuṣyāṇām", "of men"],
               ["sahasreṣu", "among thousands"],
               ["kaścit", "someone"],
               ["yatati", "strives"],
               ["siddhaye", "for perfection"],
               ["yatatām", "of those who strive"],
               ["api", "even"],
               ["siddhānām", "and are perfected"],
               ["kaścit", "someone"],
               ["mām", "me"],
               ["vetti", "knows"],
               ["tattvataḥ", "in truth"],
           ]),
        _v([
            "bhūmirāpo'nalo vāyuḥ khaṃ mano buddhireva ca |",
            "ahaṅkāra itīyaṃ me bhinnā prakṛtiraṣṭadhā",
        ], "|| 4 ||",
           "Earth, water, fire, air, space, mind, understanding and ego — this is my nature, divided eightfold.",
           bhashya=[
               {"text": "śrotāraṃ prarocanena abhimukhīkṛtyāha –", "intro": True, "tr": "Having made the hearer attentive by kindling his interest, he says:"},
               {"text": "bhūmiḥ iti. “bhūmiḥ” iti pṛthivī tanmātraṃ ucyate. na sthūlā, “bhinnā prakṛtiraṣṭadhā” iti vacanāt. tathā abādayo'pi tanmātrāṇyeva ucyante – āpaḥ, analaḥ, vāyuḥ, kham. manaḥ iti manasaḥ kāraṇaṃ ahaṅkāro gṛhyate. buddhiḥ iti ahaṅkārakāraṇam mahattattvam. ahaṅkāraḥ iti avidyā saṃyuktaṃ avyaktam. yathā viṣasaṃyuktaṃ annaṃ viṣam iti ucyate, evaṃ ahaṅkāravāsanāvat avyaktaṃ mūlakāraṇaṃ ahaṅkāraḥ ityucyate, pravartakatvāt ahaṅkārasya. ahaṅkāraḥ eva hi sarvasva pravṛttibījaṃ dṛṣṭaṃ loke. itīyaṃ yathoktā prakṛtiḥ me mama aiśvarī māyāśaktiḥ aṣṭadhā bhinnā bhedaṃ āgatā.", "tr": "'Earth, water, fire, air…' 'Earth' means the subtle element of earth, not the gross, because of the words 'my nature divided eightfold'. Likewise water and the rest also mean only the subtle elements: water, fire, air, space. 'Mind' means egoism, the cause of the mind. 'Understanding' means the great principle, mahat, the cause of egoism. 'Egoism' means the unmanifest joined with ignorance: just as food mixed with poison is called poison, so the unmanifest root cause, which carries the impressions of egoism, is called egoism, because egoism impels; for egoism is seen in the world to be the seed of all activity. This nature as described is mine — my divine power of māyā — divided eightfold, come to division."},
           ],
           words=[
               ["bhūmiḥ", "earth"],
               ["āpaḥ", "water"],
               ["analaḥ", "fire"],
               ["vāyuḥ", "air"],
               ["kham", "space"],
               ["manaḥ", "mind"],
               ["buddhiḥ", "understanding"],
               ["eva ca", "and also"],
               ["ahaṅkāraḥ", "egoism"],
               ["iti", "thus"],
               ["iyam", "this"],
               ["me", "my"],
               ["bhinnā", "divided"],
               ["prakṛtiḥ", "nature"],
               ["aṣṭadhā", "eightfold"],
           ]),
        _v([
            "apareyamitastvanyāṃ prakṛtiṃ viddhi me parām |",
            "jīvabhūtāṃ mahābāho yayedaṃ dhāryate jagat",
        ], "|| 5 ||",
           "This is my lower nature. But know my other, higher nature, mighty-armed one: the life-principle by which this world is sustained.",
           bhashya=[
               {"text": "aparā iti. aparā na parā nikṛṣṭā aśuddhā anarthakarī saṃsāra bandhanātmikā iyam. itaḥ asyāḥ yathoktāyāḥ tu anyāṃ viśuddhāṃ prakṛtiṃ mama ātmabhūtāṃ viddhi me parāṃ prakṛṣṭāṃ jīvabhūtāṃ kṣetrajñalakṣaṇāṃ prāṇadhāraṇanimittabhūtāṃ he mahābāho yayā prakṛtyā idaṃ dhāryate jagat antaḥ praviṣṭayā.", "tr": "'This is the lower…' This is the lower, not the higher — inferior, impure, harmful, of the nature of the bondage of saṃsāra. But other than this nature as described, know my higher nature — pure, my own very self, superior — which has become the living being, consisting of the knower of the field, the cause that sustains life, O mighty-armed, by which nature, having entered within it, this world is sustained."},
           ],
           words=[
               ["aparā", "lower"],
               ["iyam", "this"],
               ["itaḥ", "than this"],
               ["tu", "but"],
               ["anyām", "other"],
               ["prakṛtim", "nature"],
               ["viddhi", "know"],
               ["me", "my"],
               ["parām", "higher"],
               ["jīva-bhūtām", "which has become the living being"],
               ["mahā-bāho", "O mighty-armed"],
               ["yayā", "by which"],
               ["idam", "this"],
               ["dhāryate", "is sustained"],
               ["jagat", "world"],
           ]),
        _v([
            "etadyonīni bhūtāni sarvāṇītyupadhāraya |",
            "ahaṃ kṛtsnasya jagataḥ prabhavaḥ pralayastathā",
        ], "|| 6 ||",
           "Know that all beings have these two as their womb. I am the origin and the dissolution of the whole world.",
           bhashya=[
               {"text": "etat iti. etadyonīni ete parāpare kṣetrakṣetrajña lakṣaṇe prakṛtī yoniḥ yeṣāṃ bhūtānāṃ tāni etadyonīni bhūtāni sarvāṇi iti evaṃ upadhāraya jānīhi. yasmāt mama prakṛtī yoniḥ kāraṇaṃ sarvabhūtānāṃ, ataḥ ahaṃ kṛtsnasya samastasya jagataḥ prabhavaḥ utpattiḥ, pralayaḥ vināśaḥ tathā. prakṛtidvayadvāreṇa ahaṃ sarvajñaḥ īśvaraḥ jagataḥ kāraṇaṃ ityarthaḥ. yasmāt evaṃ tasmāt–", "tr": "'All beings have these as their womb…' Know, understand, that all beings have these as their womb: beings whose womb is these two natures, the higher and the lower, the field and the knower of the field. Since my two natures are the womb, the cause, of all beings, I am the origin, the arising, of the whole, entire, world, and likewise its dissolution, its destruction. Through the two natures I, the all-knowing Lord, am the cause of the world — that is the meaning. Since this is so, therefore —"},
           ],
           words=[
               ["etat-yonīni", "having these as their womb"],
               ["bhūtāni", "beings"],
               ["sarvāṇi", "all"],
               ["iti", "thus"],
               ["upadhāraya", "understand"],
               ["aham", "I"],
               ["kṛtsnasya", "of the whole"],
               ["jagataḥ", "world"],
               ["prabhavaḥ", "the origin"],
               ["pralayaḥ", "the dissolution"],
               ["tathā", "likewise"],
           ]),
        _v([
            "mattaḥ parataraṃ nānyatkiñcidasti dhanañjaya |",
            "mayi sarvamidaṃ protaṃ sūtre maṇigaṇā iva",
        ], "|| 7 ||",
           "There is nothing whatever higher than I, Dhanañjaya. All this is strung on me like clusters of pearls on a thread.",
           bhashya=[
               {"text": "mattaḥ iti. mattaḥ parameśvarāt parataraṃ anyat kāraṇāntaraṃ kiñcit na asti na vidyate, ahameva jagatkāraṇaṃ ityarthaḥ, he dhanañjaya, yasmāt evaṃ tasmāt mayi parameśvare sarvāṇi bhūtāni sarvaṃ idaṃ jagat protaṃ anusyūtaṃ anugataṃ (anuviddhaṃ) grathitaṃ ityarthaḥ, dīrghatantuṣu paṭavat, sūtre ca maṇigaṇāḥ iva.", "tr": "'There is nothing whatever higher than me…' There is nothing else whatever, no other cause, higher than me, the supreme Lord; I alone am the cause of the world, that is, Dhanañjaya. Since this is so, all beings, this whole world, is strung on me, the supreme Lord — threaded, permeated, woven, that is — like cloth on its long threads, and like clusters of gems on a thread."},
           ],
           words=[
               ["mattaḥ", "than me"],
               ["para-taram", "higher"],
               ["na", "not"],
               ["anyat", "other"],
               ["kiñcit", "anything"],
               ["asti", "is"],
               ["dhanañjaya", "O Dhanañjaya"],
               ["mayi", "on me"],
               ["sarvam", "all"],
               ["idam", "this"],
               ["protam", "is strung"],
               ["sūtre", "on a thread"],
               ["maṇi-gaṇāḥ", "clusters of gems"],
               ["iva", "like"],
           ]),
        _v([
            "raso'hamapsu kaunteya prabhā'smi śaśisūryayoḥ |",
            "praṇavaḥ sarvavedeṣu śabdaḥ khe pauruṣaṃ nṛṣu",
        ], "|| 8 ||",
           "I am the taste in water, son of Kuntī; I am the light in the moon and the sun; the syllable Om in all the Vedas, sound in space, and manhood in men.",
           bhashya=[
               {"text": "kena kena dharmeṇa viśiṣṭe tvayi sarvamidaṃ protaṃ ityucyate?–", "intro": True, "tr": "Endowed with what attributes are you, in whom all this is said to be strung?"},
               {"text": "rasaḥ iti. rasaḥ ahaṃ apāṃ yaḥ sāraḥ saḥ rasaḥ, tasmin rasabhūte mayi āpaḥ protāḥ ityarthaḥ. evaṃ sarvatra. yathā ahaṃ apsu rasaḥ, evaṃ prabhā asmi śaśisūryayoḥ.praṇavaḥ oṅkāraḥ sarvavedeṣu, tasmin praṇavabhūte mayi sarve vedāḥ protāḥ. tathā khe ākāśe śabdaḥ sārabhūtaḥ, tasmin mayi khaṃ protam. tathā pauruṣaṃ puruṣasya bhāvaḥ pauruṣaṃ – yataḥ pumbuddhiḥ – nṛṣu tasmin mayi puruṣāḥ protāḥ–", "tr": "'I am the taste in water…' I am the taste in water: the essence of water is its taste; on me, who am that taste, the waters are strung — that is the meaning. So in every case. As I am the taste in water, so I am the radiance in moon and sun; the praṇava, the syllable om, in all the Vedas — on me, who am the praṇava, all the Vedas are strung; likewise sound, the essence of space — on me, as that, space is strung; likewise manhood, the quality of being a man, from which comes the notion 'man', in men — on me, as that, men are strung."},
           ],
           words=[
               ["rasaḥ", "the taste"],
               ["aham", "I"],
               ["apsu", "in water"],
               ["kaunteya", "O son of Kuntī"],
               ["prabhā", "the radiance"],
               ["asmi", "I am"],
               ["śaśi-sūryayoḥ", "in moon and sun"],
               ["praṇavaḥ", "the syllable om"],
               ["sarva-vedeṣu", "in all the Vedas"],
               ["śabdaḥ", "sound"],
               ["khe", "in space"],
               ["pauruṣam", "manhood"],
               ["nṛṣu", "in men"],
           ]),
        _v([
            "puṇyo gandhaḥ pṛthivyāṃ ca tejaścāsmi vibhāvasau |",
            "jīvanaṃ sarvabhūteṣu tapaścāsmi tapasviṣu",
        ], "|| 9 ||",
           "I am the pure fragrance in the earth and the brilliance in fire; I am the life in all beings and the austerity in ascetics.",
           bhashya=[
               {"text": "puṇyaḥ iti – puṇyaḥ surabhiḥ gandhaḥ pṛthivyāṃ ca aham, tasmin mayi gandhabhūte pṛthivī protā. puṇyatvaṃ gandhasya svabhāvataḥ eva pṛthivyāṃ darśitaṃ abādiṣu rasādeḥ puṇyatvopalakṣaṇārtham. apuṇyatvaṃ tu gandhādīnāṃ avidyādharmādyapekṣaṃ saṃsāriṇāṃ bhūtaviśeṣasaṃsarganimittaṃ bhavati. tejaḥ dīptiḥ ca asmi vibhāvasau agnau. tathā jīvanaṃ sarvabhūteṣu, yena jīvanti sarvāṇi bhūtāni tat jīvanam. tapaḥ ca asmi tapasviṣu, tasmin tapasi mayi tapasvinaḥ protāḥ–", "tr": "'The pure fragrance in the earth…' I am the pure, sweet, fragrance in the earth; on me, as fragrance, the earth is strung. Purity is shown to be natural to fragrance in earth in order to indicate the purity of taste and the rest in water and the other elements; the impurity of fragrance and the rest is due to contact with particular elements, depending on the ignorance, demerit and so on of those in saṃsāra. I am the brilliance, the radiance, in fire; and likewise life in all beings — that by which all beings live is life. And I am the austerity in ascetics; on me, as that austerity, ascetics are strung."},
           ],
           words=[
               ["puṇyaḥ", "pure"],
               ["gandhaḥ", "fragrance"],
               ["pṛthivyām", "in the earth"],
               ["ca", "and"],
               ["tejaḥ", "brilliance"],
               ["ca", "and"],
               ["asmi", "I am"],
               ["vibhāvasau", "in fire"],
               ["jīvanam", "life"],
               ["sarva-bhūteṣu", "in all beings"],
               ["tapaḥ", "austerity"],
               ["ca", "and"],
               ["asmi", "I am"],
               ["tapasviṣu", "in ascetics"],
           ]),
        _v([
            "bījaṃ māṃ sarvabhūtānāṃ viddhi pārtha sanātanam |",
            "buddhirbuddhimatāmasmi tejastejasvināmaham",
        ], "|| 10 ||",
           "Know me, Pārtha, as the eternal seed of all beings. I am the understanding of the intelligent and the splendour of the splendid.",
           bhashya=[
               {"text": "bījaṃ iti. bījaṃ prarohakāraṇaṃ māṃ viddhi sarvabhūtānāṃ he pārtha sanātanaṃ cirantanam. kiñca – buddhiḥ vivekaśaktiḥ antaḥkaraṇasya buddhimatāṃ vivekaśaktimatāṃ asmi, tejaḥ prāgalbhyaṃ tadvatāṃ tejasvināṃ aham.", "tr": "'Know me as the eternal seed of all beings…' Know me as the seed, the cause of sprouting, of all beings, Pārtha, eternal, ancient. Moreover, I am the understanding — the discriminating power of the inner organ — of those who have understanding, the power of discrimination; I am the vigour, boldness, of the vigorous, those who have it."},
           ],
           words=[
               ["bījam", "the seed"],
               ["mām", "me"],
               ["sarva-bhūtānām", "of all beings"],
               ["viddhi", "know"],
               ["pārtha", "O Pārtha"],
               ["sanātanam", "eternal"],
               ["buddhiḥ", "the understanding"],
               ["buddhimatām", "of the intelligent"],
               ["asmi", "I am"],
               ["tejaḥ", "the vigour"],
               ["tejasvinām", "of the vigorous"],
               ["aham", "I"],
           ]),
        _v([
            "balaṃ balavatāṃ cāhaṃ kāmarāgavivarjitam |",
            "dharmāviruddho bhūteṣu kāmo'smi bharatarṣabha",
        ], "|| 11 ||",
           "Of the strong I am the strength that is free from desire and passion; in beings I am desire that is not contrary to dharma, O best of the Bhāratas.",
           bhashya=[
               {"text": "balaṃ iti. balaṃ sāmarthyaṃ ojaḥ balavatāṃ ahaṃ, tat ca balaṃ kāmarāga vivarjitaṃ, kāmaśca rāgaśca kāmarāgau – kāmaḥ tṛṣṇā asannikṛṣṭeṣu viṣayeṣu, rāgaḥ rañjanā prāpteṣu viṣayeṣu – tābhyāṃ kāmarāgābhyāṃ vivarjitaṃ dehādidhāraṇamātrārthaṃ balaṃ sattvaṃ ahaṃ asmi, na tu saṃsāriṇāṃ tṛṣṇārāga kāraṇam. kiñca – dharmāviruddhaḥ dharmeṇa śāstrerthena aviruddhaḥ yaḥ prāṇiṣu bhūteṣu kāmaḥ, yathā dehadhāraṇamātrādyarthaḥ aśanapānādi viṣayaḥ, saḥ kāmaḥ asmi he bharatarṣabha! kiñca–", "tr": "'And I am the strength of the strong…' I am the strength — capacity, vigour — of the strong; and that strength free of desire and passion. Desire and passion: desire is thirst for objects not present; passion is attachment to objects obtained. I am the strength, the vitality, free from these two, serving only to sustain the body and the rest, not that which causes thirst and passion in those in saṃsāra. Moreover, the desire in beings, in living creatures, that is not opposed to dharma, to the meaning of scripture — such as desire for food and drink serving only to sustain the body — that desire am I, bull of the Bharatas. Moreover —"},
           ],
           words=[
               ["balam", "the strength"],
               ["balavatām", "of the strong"],
               ["ca", "and"],
               ["aham", "I"],
               ["kāma-rāga-vivarjitam", "free of desire and passion"],
               ["dharma-aviruddhaḥ", "not opposed to dharma"],
               ["bhūteṣu", "in beings"],
               ["kāmaḥ", "desire"],
               ["asmi", "I am"],
               ["bharata-ṛṣabha", "O bull of the Bharatas"],
           ]),
        _v([
            "ye caiva sāttvikā bhāvā rājasāstāmasāśca ye |",
            "matta eveti tānviddhi na tvahaṃ teṣu te mayi",
        ], "|| 12 ||",
           "And whatever states there are of sattva, rajas and tamas, know that they come from me alone; yet I am not in them — they are in me.",
           bhashya=[
               {"text": "ye iti. ye ca eva sāttvikāḥ sattvanirvṛttāḥ bhāvāḥ padārthāḥ, rājasāḥ rajonirvṛttāḥ, tāmasāḥ tamo nirvṛttāśca, ye kecit prāṇināṃ svakarmavaśāt jāyante bhāvāḥ tān mattaḥ eva jāyamānān iti evaṃ viddhi sarvān samastān eva. yadyapi te mattaḥ jāyante tathāpi na tu ahaṃ teṣu tadadhīnaḥ tadvaśaḥ, yathā saṃsāriṇaḥ. te punaḥ mayi madvaśāḥ madadhīnāḥ.", "tr": "'Whatever states are sāttvika…' Whatever states, things, are sāttvika, produced by sattva, and rājasa, produced by rajas, and tāmasa, produced by tamas — whatever states arise for living beings according to their own actions — know them all, entirely, to arise from me alone. Although they arise from me, I am not in them, not dependent on them, not in their power, as those in saṃsāra are; but they are in me, in my power, dependent on me."},
           ],
           words=[
               ["ye", "whatever"],
               ["ca", "and"],
               ["eva", "indeed"],
               ["sāttvikāḥ", "of sattva"],
               ["bhāvāḥ", "states"],
               ["rājasāḥ", "of rajas"],
               ["tāmasāḥ", "of tamas"],
               ["ca", "and"],
               ["ye", "whatever"],
               ["mattaḥ", "from me"],
               ["eva", "alone"],
               ["iti", "thus"],
               ["tān", "them"],
               ["viddhi", "know"],
               ["na", "not"],
               ["tu", "but"],
               ["aham", "I"],
               ["teṣu", "in them"],
               ["te", "they"],
               ["mayi", "in me"],
           ]),
        _v([
            "tribhirguṇamayairbhāvairebhiḥ sarvamidaṃ jagat |",
            "mohitaṃ nābhijānāti māmebhyaḥ paramavyayam",
        ], "|| 13 ||",
           "Deluded by these states made of the three guṇas, this whole world does not recognise me, who am beyond them and imperishable.",
           bhashya=[
               {"text": "evambhūtamapi parameśvaraṃ nityaśuddhabuddhamuktasvabhāvaṃ sarvabhūtātmānaṃ nirguṇaṃ saṃsāradoṣabījapradāhakāraṇaṃ māṃ nābhijānāti jagat iti anukrośaṃ darśayati bhagavān. tacca kiṃ nimittaṃ jagataḥ ajñānamiti? ucyate –", "intro": True, "tr": "The Blessed Lord shows his compassion: 'the world does not know me, the supreme Lord, even though I am such — eternally pure, awake and free by nature, the Self of all beings, without qualities, the cause that burns up the seed of the faults of saṃsāra.' What is the cause of the world's ignorance? It is said:"},
               {"text": "tribhiḥ iti. tribhiḥ guṇamayaiḥ guṇavikāraiḥ rāgadveṣamohādi prakāraiḥ bhāvaiḥ padārthaiḥ ebhiḥ yathoktaiḥ idaṃ prāṇijātaṃ jagat mohitaṃ avivekitāṃ āpāditaṃ sat na abhijānāti māṃ ebhyaḥ yathoktebhyaḥ guṇebhyaḥ paraṃ vyatiriktaṃ vilakṣaṇaṃ ca avyayaṃ vyayarahitaṃ janmādisarvabhāvavikāravarjitaṃ ityarthaḥ.", "tr": "'By these three states made of the guṇas…' Deluded — brought to lack of discrimination — by these three states, things, made of the guṇas, modifications of the guṇas such as attachment, aversion and delusion, as described, this world, the host of living beings, does not know me, who am beyond these guṇas as described, distinct and different from them, and imperishable, without decay — free of all the modifications of being, birth and the rest, that is."},
           ],
           words=[
               ["tribhiḥ", "by the three"],
               ["guṇa-mayaiḥ", "made of the guṇas"],
               ["bhāvaiḥ", "states"],
               ["ebhiḥ", "these"],
               ["sarvam", "whole"],
               ["idam", "this"],
               ["jagat", "world"],
               ["mohitam", "deluded"],
               ["na", "not"],
               ["abhijānāti", "knows"],
               ["mām", "me"],
               ["ebhyaḥ", "than these"],
               ["param", "beyond"],
               ["avyayam", "imperishable"],
           ]),
        _v([
            "daivī hyeṣā guṇamayī mama māyā duratyayā |",
            "māmeva ye prapadyante māyāmetāṃ taranti te",
        ], "|| 14 ||",
           "For this divine māyā of mine, made of the guṇas, is hard to cross; those who take refuge in me alone cross over this māyā.",
           bhashya=[
               {"text": "kathaṃ punaḥ daivīṃ etāṃ triguṇātmikāṃ vaiṣṇavīṃ māyāṃ atikrāmanti iti? ucyate–", "intro": True, "tr": "How, then, do they cross over this divine māyā of Viṣṇu, made of the three guṇas? It is said:"},
               {"text": "daivī iti. daivī devasya mama īśvarasya viṣṇoḥ svabhāvabhūtā hi yasmāt eṣā yathoktā guṇamayī mama māyā duratyayā duḥkhena atyayaḥ atikramaṇaṃ yasyāḥ sā duratyayā. tatra evaṃ sati sarvadharmān parityajya māṃ eva māyāvinaṃ svātmabhūtaṃ sarvātmanā ye prapadyante te māyāṃ etāṃ sarvabhūtamohinīṃ taranti atikrāmanti, te saṃsāra bandhanāt mucyante ityarthaḥ.", "tr": "'For this divine māyā of mine…' Divine: belonging to me, the god, the Lord Viṣṇu, my own nature; for this māyā of mine as described, made of the guṇas, is hard to cross — its crossing is difficult. This being so, those who, giving up all dharmas, take refuge with their whole being in me alone, the possessor of māyā, their own Self — they cross over this māyā that deludes all beings; they are freed from the bondage of saṃsāra, that is."},
           ],
           words=[
               ["daivī", "divine"],
               ["hi", "for"],
               ["eṣā", "this"],
               ["guṇa-mayī", "made of the guṇas"],
               ["mama", "my"],
               ["māyā", "māyā"],
               ["duratyayā", "is hard to cross"],
               ["mām", "in me"],
               ["eva", "alone"],
               ["ye", "who"],
               ["prapadyante", "take refuge"],
               ["māyām", "māyā"],
               ["etām", "this"],
               ["taranti", "cross over"],
               ["te", "they"],
           ]),
        _v([
            "na māṃ duṣkṛtino mūḍhāḥ prapadyante narādhamāḥ |",
            "māyayā'pahṛtajñānā āsuraṃ bhāvamāśritāḥ",
        ], "|| 15 ||",
           "Evildoers, deluded and the lowest of men, do not take refuge in me — their knowledge carried away by māyā, resorting to the demonic state.",
           bhashya=[
               {"text": "yadi tvāṃ prapannāḥ māyāṃ etāṃ taranti, kasmāt tvām eva sarve na prapadyante iti? ucyate–", "intro": True, "tr": "If those who take refuge in you cross over this māyā, why do not all take refuge in you alone? It is said:"},
               {"text": "na māṃ iti. na māṃ parameśvaraṃ nārāyaṇaṃ duṣkṛtinaḥ pāpakāriṇaḥ mūḍhāḥ prapadyante narādhamāḥ narāṇāṃ madhye adhamāḥ nikṛṣṭāḥ te ca māyayā apahṛtajñānāḥ sammuṣitajñānāḥ āsuraṃ bhāvaṃ hiṃsānṛtādilakṣaṇaṃ āśritāḥ", "tr": "'Evil-doers do not take refuge in me…' Evil-doers, those who do sinful deeds, the deluded, do not take refuge in me, the supreme Lord Nārāyaṇa — the lowest of men, the vilest among men; and they, their knowledge stolen by māyā, robbed of their knowledge, have taken to the demonic state, marked by violence, falsehood and the like."},
           ],
           words=[
               ["na", "not"],
               ["mām", "in me"],
               ["duṣkṛtinaḥ", "evil-doers"],
               ["mūḍhāḥ", "the deluded"],
               ["prapadyante", "take refuge"],
               ["nara-adhamāḥ", "the lowest of men"],
               ["māyayā", "by māyā"],
               ["apahṛta-jñānāḥ", "robbed of knowledge"],
               ["āsuram", "demonic"],
               ["bhāvam", "state"],
               ["āśritāḥ", "having taken to"],
           ]),
        _v([
            "caturvidhā bhajante māṃ janāḥ sukṛtino'rjuna |",
            "ārto jijñāsurarthārthī jñānī ca bharatarṣabha",
        ], "|| 16 ||",
           "Four kinds of virtuous people worship me, Arjuna: the distressed, the seeker of knowledge, the seeker of gain, and the one who knows, O best of the Bhāratas.",
           bhashya=[
               {"text": "ye punaḥ narottamāḥ puṇyakarmāṇaḥ", "intro": True, "tr": "But those best of men, doers of good deeds —"},
               {"text": "caturvidhā iti. caturvidhāḥ catuḥ prakārāḥ bhajante sevante māṃ janāḥ sukṛtinaḥ puṇyakarmāṇaḥ. he arjuna, ārtaḥ ārtiparigṛhītaḥ taskaravyāghrarogādinā abhibhūtaḥ āpannaḥ, jijñāsuḥ bhagavattattvaṃ jñātuṃ icchanti yaḥ. arthārthī dhanakāmaḥ, jñānī viṣṇoḥ tattvavit, ca he bharatarṣabha.", "tr": "'Four kinds of men worship me…' Four kinds, four sorts, of men who do good, whose deeds are meritorious, worship, serve, me, Arjuna: the distressed — seized by distress, overcome by thieves, tigers, disease and the like, fallen into trouble; the seeker of knowledge, who wishes to know the reality of the Lord; the seeker of wealth, who desires riches; and the man of knowledge, who knows the reality of Viṣṇu, bull of the Bharatas."},
           ],
           words=[
               ["catur-vidhāḥ", "four kinds"],
               ["bhajante", "worship"],
               ["mām", "me"],
               ["janāḥ", "of men"],
               ["sukṛtinaḥ", "who do good"],
               ["arjuna", "O Arjuna"],
               ["ārtaḥ", "the distressed"],
               ["jijñāsuḥ", "the seeker of knowledge"],
               ["artha-arthī", "the seeker of wealth"],
               ["jñānī", "the man of knowledge"],
               ["ca", "and"],
               ["bharata-ṛṣabha", "O bull of the Bharatas"],
           ]),
        _v([
            "teṣāṃ jñānī nityayukta ekabhaktirviśiṣyate |",
            "priyo hi jñānino'tyarthamahaṃ sa ca mama priyaḥ",
        ], "|| 17 ||",
           "Of these the knower, ever disciplined and devoted to the One, excels; for I am exceedingly dear to the knower, and he is dear to me.",
           bhashya=[
               {"text": "teṣāṃ iti. teṣāṃ caturṇāṃ madhye jñānī tattvavit tattvavittvāt nityayuktaḥ bhavati ekabhaktiśca, anyasya bhajanīyasya adarśanāt, ataḥ saḥ ekabhaktiḥ viśiṣyate viśeṣaṃ ādhikyaṃ āpadyate, atiricyate ityarthaḥ (18.55 bhāṣye). priyaḥ hi yasmāt ahaṃ ātmā jñāninaḥ, ataḥ tasya ahaṃ atyarthaṃ priyaḥ, prasiddhaṃ hi loke “ātmā priyaḥ bhavati” iti. tasmāt jñāninaḥ ātmattvāt vāsudevaḥ priyaḥ bhavatītyarthaḥ. sa ca jñānī mama vāsudevasya ātmā eva iti mama atyarthaṃ priyaḥ.", "tr": "'Of them the man of knowledge…' Of them, among the four, the man of knowledge, the knower of the truth, being a knower of the truth, is ever disciplined, and has single devotion, since he sees nothing else to be worshipped. So he, with single devotion, excels — gains distinction, superiority, surpasses the rest, that is (see the commentary on 18.55). For I am the Self of the man of knowledge, so I am exceedingly dear to him; for it is well known in the world that one's self is dear. So, being the Self of the man of knowledge, Vāsudeva is dear to him — that is the meaning. And that man of knowledge is the very Self of me, Vāsudeva, and so exceedingly dear to me."},
           ],
           words=[
               ["teṣām", "of them"],
               ["jñānī", "the man of knowledge"],
               ["nitya-yuktaḥ", "ever disciplined"],
               ["eka-bhaktiḥ", "of single devotion"],
               ["viśiṣyate", "excels"],
               ["priyaḥ", "dear"],
               ["hi", "for"],
               ["jñāninaḥ", "to the man of knowledge"],
               ["atyartham", "exceedingly"],
               ["aham", "I"],
               ["saḥ", "he"],
               ["ca", "and"],
               ["mama", "to me"],
               ["priyaḥ", "dear"],
           ]),
        _v([
            "udārāḥ sarva evaite jñānī tvātmaiva me matam |",
            "āsthitaḥ sa hi yuktātmā māmevānuttamāṃ gatim",
        ], "|| 18 ||",
           "All these are noble; but the knower I regard as my very Self. For, with disciplined self, he abides in me alone as the highest goal.",
           bhashya=[
               {"text": "na tarhi ārtādayaḥ trayaḥ vāsudevasya priyāḥ? na, kiṃ tarhi?", "intro": True, "tr": "Are the three, the distressed and the rest, then not dear to Vāsudeva? No; then what?"},
               {"text": "udārāḥ iti. udārāḥ utkṛṣṭāḥ sarva eva ete, trayo'pi mama priyāḥ evetyarthaḥ na hi kaścit madbhaktaḥ mama vāsudevasya apriyaḥ bhavati. jñānī tu atyarthaṃ priyaḥ bhavatīti viśeṣaḥ. tat kasmāt iti? ataḥ āha– jñānī tu ātmā eva, na anyaḥ mattaḥ iti me mama mataṃ niścayaḥ. āsthitaḥ āroḍhuṃ pravṛttaḥ saḥ jñānī hi yasmāt “ahameva bhagavān vāsudevaḥ na anyaḥ asmi” ityevaṃ yuktātmā samāhitacittaḥ san mām eva paraṃ brahma gantavyaṃ anuttamāṃ gatiṃ gantuṃ pravṛttaḥ ityarthaḥ.", "tr": "'All these are noble…' All these are noble, excellent; all three are dear to me, that is; for no devotee of mine is not dear to me, Vāsudeva. But the man of knowledge is exceedingly dear — that is the difference. Why? So he says: but the man of knowledge is my very Self, not other than me — that is my view, my certainty. For he, the man of knowledge, has set out to ascend — with the thought 'I am the Blessed Lord Vāsudeva himself, and no other', self-disciplined, with collected mind — to me alone, the supreme Brahman, the goal to be reached, the unsurpassed goal: he has set out to reach it, that is."},
           ],
           words=[
               ["udārāḥ", "noble"],
               ["sarve", "all"],
               ["eva", "indeed"],
               ["ete", "these"],
               ["jñānī", "the man of knowledge"],
               ["tu", "but"],
               ["ātmā", "my Self"],
               ["eva", "very"],
               ["me", "my"],
               ["matam", "view"],
               ["āsthitaḥ", "has resorted to"],
               ["saḥ", "he"],
               ["hi", "for"],
               ["yukta-ātmā", "self-disciplined"],
               ["mām", "me"],
               ["eva", "alone"],
               ["anuttamām", "unsurpassed"],
               ["gatim", "goal"],
           ]),
        _v([
            "bahūnāṃ janmanāmante jñānavānmāṃ prapadyate |",
            "vāsudevaḥ sarvamiti sa mahātmā sudurlabhaḥ",
        ], "|| 19 ||",
           "At the end of many births the man of knowledge takes refuge in me, knowing 'Vāsudeva is all'. Such a great soul is very rare.",
           bhashya=[
               {"text": "jñānī punarapi stūyate–", "intro": True, "tr": "The man of knowledge is praised yet again:"},
               {"text": "bahūnāṃ iti. bahūnāṃ janmanāṃ jñānārthasaṃskārāśrayāṇāṃ ante samāptau jñānavān prāptaparipākajñānaḥ māṃ vāsudeva pratyagātmānaṃ pratyakṣataḥ prapadyate – katham? vāsudevaḥ sarvaṃ iti. ya evaṃ sarvātmānaṃ māṃ nārāyaṇaṃ pratipadyate, saḥ mahātmā, na tatsamaḥ anyaḥ asti, adhikaḥ vā. ataḥ sudurlabhaḥ, manuṣyāṇāṃ sahasreṣu (7.3) iti hi uktam.", "tr": "'At the end of many births…' At the end, the close, of many births, which have been the ground for accumulating impressions conducive to knowledge, the man of knowledge, whose knowledge has come to maturity, takes refuge in me, Vāsudeva, the inmost Self, directly. How? 'Vāsudeva is all.' He who thus attains me, Nārāyaṇa, the Self of all, is a great soul; no one is equal to him or greater. So he is very hard to find; for it has been said, 'among thousands of men' (7.3)."},
           ],
           words=[
               ["bahūnām", "of many"],
               ["janmanām", "births"],
               ["ante", "at the end"],
               ["jñānavān", "the man of knowledge"],
               ["mām", "in me"],
               ["prapadyate", "takes refuge"],
               ["vāsudevaḥ", "Vāsudeva"],
               ["sarvam", "is all"],
               ["iti", "thus"],
               ["saḥ", "that"],
               ["mahā-ātmā", "great soul"],
               ["su-durlabhaḥ", "is very hard to find"],
           ]),
        _v([
            "kāmaistaistairhṛtajñānāḥ prapadyante'nyadevatāḥ |",
            "taṃ taṃ niyamamāsthāya prakṛtyā niyatāḥ svayā",
        ], "|| 20 ||",
           "Those whose knowledge is carried away by this desire or that resort to other gods, observing this rule or that, constrained by their own nature.",
           bhashya=[
               {"text": "ātmaiva sarvaḥ vāsudevaḥ ityevaṃ apratipattau kāraṇaṃ ucyate–", "intro": True, "tr": "The reason for not realising 'the Self, Vāsudeva, is all' is told:"},
               {"text": "kāmaiḥ iti. kāmaiḥ taiḥ taiḥ putrapaśusvargādi viṣayaiḥ hṛtajñānāḥ apahṛtavivekavijñānāḥ prapadyante anyadevatāḥ prāpnuvanti vāsudevāt ātmanaḥ anyāḥ devatāḥ, taṃ taṃ niyamaṃ devatārādhane prasiddhaḥ yaḥ yaḥ niyamaḥ taṃ taṃ āsthāya āśritya prakṛtyā svabhāvena janmāntarārjita saṃskāraviśeṣeṇa niyatāḥ niyamitāḥ svayā ātmīyayā.", "tr": "'Robbed of knowledge by this or that desire…' Robbed of knowledge — of discriminating understanding — by this or that desire, for sons, cattle, heaven and other objects, they take refuge in other deities — go to deities other than Vāsudeva, the Self — following this or that rule, whatever rule is well known for the worship of each deity, constrained by their own nature, by the particular impressions acquired in other births."},
           ],
           words=[
               ["kāmaiḥ", "by desires"],
               ["taiḥ taiḥ", "this or that"],
               ["hṛta-jñānāḥ", "robbed of knowledge"],
               ["prapadyante", "they resort to"],
               ["anya-devatāḥ", "other deities"],
               ["tam tam", "this or that"],
               ["niyamam", "rule"],
               ["āsthāya", "following"],
               ["prakṛtyā", "by nature"],
               ["niyatāḥ", "constrained"],
               ["svayā", "their own"],
           ]),
        _v([
            "yo yo yāṃ yāṃ tanuṃ bhaktaḥ śraddhayā'rcitumicchati |",
            "tasya tasyācalāṃ śraddhāṃ tāmeva vidadhāmyaham",
        ], "|| 21 ||",
           "Whatever form any devotee wishes to worship with faith, that same faith of his I make steady.",
           bhashya=[
               {"text": "teṣāṃ ca kāminām–", "intro": True, "tr": "And of those who desire —"},
               {"text": "yo yaḥ iti. yaḥ yaḥ kāmī yāṃ yāṃ devatātanuṃ śraddhayā saṃyuktaḥ bhaktaḥ ca san arcituṃ pūjayituṃ icchati, tasya tasya kāminaḥ acalāṃ sthirāṃ śraddhāṃ tām eva vidadhāmi sthirīkaromi (yayaiva pūrvaṃ pravṛttaḥ). svabhāvataḥ yaḥ yaḥ yāṃ yāṃ devatātanuṃ śraddhayā arcituṃ icchati–", "tr": "'Whatever form any devotee…' Whatever form of a deity any man of desire, endowed with faith and devoted, wishes to worship, to honour — for each such man of desire I make that very faith firm, unshakeable (the faith with which he first set out). Whoever by his nature wishes to worship with faith whatever form of a deity —"},
           ],
           words=[
               ["yaḥ yaḥ", "whoever"],
               ["yām yām", "whatever"],
               ["tanum", "form"],
               ["bhaktaḥ", "devotee"],
               ["śraddhayā", "with faith"],
               ["arcitum", "to worship"],
               ["icchati", "wishes"],
               ["tasya tasya", "of that one"],
               ["acalām", "unshakeable"],
               ["śraddhām", "faith"],
               ["tām", "that"],
               ["eva", "very"],
               ["vidadhāmi", "make"],
               ["aham", "I"],
           ]),
        _v([
            "sa tayā śraddhayā yuktastasyārādhanamīhate |",
            "labhate ca tataḥ kāmān mayaiva vihitān hitān",
        ], "|| 22 ||",
           "Endowed with that faith, he seeks to worship that form, and from it he obtains his desires — granted in truth by me alone.",
           bhashya=[
               {"text": "sa tayā iti. saḥ tayā madvihitayā śraddhayā yuktaḥ san tasyāḥ devatātanvāḥrādhanaṃ ārādhanaṃ īhate ceṣṭate. labhate ca tataḥ tasyāḥ ārādhitāyāḥ devatātanvāḥ kāmān īpsitān mayā eva parameśvareṇa sarvajñena karmaphalavibhāgajñatayā vihitān nirmitān, tān hi yasmāt te bhagavatā vihitāḥ kāmāḥ tasmāt tān avaśyaṃ labhate ityarthaḥ. “hitān” iti padacchede hitattvaṃ kāmānāṃ upacaritaṃ kalpyam, na hi kāmāḥ hitāḥ kasyacit.", "tr": "'Endowed with that faith…' He, endowed with that faith ordained by me, seeks, strives for, the worship of that form of the deity; and from that form of the deity, worshipped, he obtains his desires, the things he wishes for, ordained, fashioned, by me alone, the supreme Lord, all-knowing, since I know the apportioning of the fruits of action. Since those desires are ordained by the Lord, he certainly obtains them — that is the meaning. If one divides the words to read 'beneficial', their being beneficial must be taken as figurative, for desires are not beneficial to anyone."},
           ],
           words=[
               ["saḥ", "he"],
               ["tayā", "with that"],
               ["śraddhayā", "faith"],
               ["yuktaḥ", "endowed"],
               ["tasya", "of that form"],
               ["ārādhanam", "the worship"],
               ["īhate", "seeks"],
               ["labhate", "obtains"],
               ["ca", "and"],
               ["tataḥ", "from it"],
               ["kāmān", "desires"],
               ["mayā", "by me"],
               ["eva", "alone"],
               ["vihitān", "ordained"],
               ["hi", "for"],
               ["tān", "them"],
           ]),
        _v([
            "antavattu phalaṃ teṣāṃ tadbhavatyalpamedhasām |",
            "devān devayajo yānti madbhaktā yānti māmapi",
        ], "|| 23 ||",
           "But finite is the fruit that comes to those of little understanding. Worshippers of the gods go to the gods; my devotees come to me.",
           bhashya=[
               {"text": "yasmāt antavatsādhanavyāpārāḥ avivekinaḥ kāminaścate, ataḥ–", "intro": True, "tr": "Since these men of desire, without discrimination, are occupied with means that have an end, therefore —"},
               {"text": "antavat iti. antavat vināśi tu phalaṃ teṣāṃ tat bhavati alpamedhasāṃ alpaprajñānām. devān devayajaḥ yānti devān yajante iti devayajaḥ, te devān yānti, madbhaktāḥ yānti māṃ api. evaṃ samāne api āyāse mām eva na prapadyante anantaphalāya, aho khalu kaṣṭataraṃ vartate, ityanukrośaṃ darśayati bhagavān.", "tr": "'But finite is the fruit…' But finite, perishable, is that fruit of those of small understanding, of little wisdom. Worshippers of the gods go to the gods — those who sacrifice to the gods are worshippers of the gods, and they go to the gods; my devotees come to me. Even though the effort is the same, they do not take refuge in me alone for an endless fruit — alas, how grievous it is! — thus the Blessed Lord shows his compassion."},
           ],
           words=[
               ["anta-vat", "finite"],
               ["tu", "but"],
               ["phalam", "fruit"],
               ["teṣām", "of those"],
               ["tat", "that"],
               ["bhavati", "is"],
               ["alpa-medhasām", "of small understanding"],
               ["devān", "to the gods"],
               ["deva-yajaḥ", "worshippers of the gods"],
               ["yānti", "go"],
               ["mat-bhaktāḥ", "my devotees"],
               ["yānti", "come"],
               ["mām", "to me"],
               ["api", "indeed"],
           ]),
        _v([
            "avyaktaṃ vyaktimāpannaṃ manyante māmabuddhayaḥ |",
            "paraṃ bhāvamajānanto mamāvyayamanuttamam",
        ], "|| 24 ||",
           "The undiscerning think of me, the unmanifest, as having become manifest, not knowing my higher being, imperishable and supreme.",
           bhashya=[
               {"text": "kiṃ nimittaṃ eva na prapadyante iti? ucyate–", "intro": True, "tr": "For what reason do they not take refuge in me alone? It is said:"},
               {"text": "avyaktaṃ iti. avyaktaṃ aprakāśaṃ vyaktiṃ āpannaṃ prakāśaṃ gataṃ idānīṃ manyante māṃ nityaprasiddhaṃ īśvaraṃ api santaṃ abuddhayaḥ avivekinaḥ parambhāvaṃ paramātmasvarūpaṃ ajānantaḥ avivekinaḥ mama avyayaṃ vyayarahitaṃ anuttamaṃ niratiśayaṃ, madīyaṃ bhāvaṃ ajānantaḥ manyante ityarthaḥ.", "tr": "'The unintelligent think of me, the unmanifest, as come into manifestation…' The unintelligent, the undiscriminating, think of me — though I am the eternally established Lord — as unmanifest, not shining forth before, and now come into manifestation, become visible; not knowing my supreme state, the nature of the supreme Self — imperishable, without decay, unsurpassed, beyond all excelling. Not knowing my state, they think so — that is the meaning."},
           ],
           words=[
               ["avyaktam", "unmanifest"],
               ["vyaktim", "to manifestation"],
               ["āpannam", "come"],
               ["manyante", "think"],
               ["mām", "me"],
               ["abuddhayaḥ", "the unintelligent"],
               ["param", "supreme"],
               ["bhāvam", "state"],
               ["ajānantaḥ", "not knowing"],
               ["mama", "my"],
               ["avyayam", "imperishable"],
               ["anuttamam", "unsurpassed"],
           ]),
        _v([
            "nāhaṃ prakāśaḥ sarvasya yogamāyāsamāvṛtaḥ |",
            "mūḍho'yaṃ nābhijānāti loko māmajamavyayam",
        ], "|| 25 ||",
           "Veiled by my yogamāyā, I am not manifest to all. This deluded world does not know me, the unborn and imperishable.",
           bhashya=[
               {"text": "tadajñānaṃ kiṃ nimittaṃ iti? ucyate–", "intro": True, "tr": "What is the cause of that ignorance? It is said:"},
               {"text": "nāhaṃ iti. na ahaṃ prakāśaḥ sarvasya lokasya, keṣāñcit eva madbhaktānāṃ prakāśaḥ ahaṃ ityabhiprāyaḥ. yogamāyāsamāvṛtaḥ yogaḥ guṇānāṃ yuktiḥ ghaṭanaṃ, saiva māyā yogamāyā – athavā, bhagavataḥ cittasamādhānayogaḥ, tatkṛtā māyā yogamāyā tayā yogamāyayā samāvṛtaḥ, sañcchannaḥ ityarthaḥ. ata eva mūḍhaḥ lokaḥ ayaṃ na abhijānāti māṃ ajaṃ avyayam.", "tr": "'I am not manifest to all…' I am not manifest to all the world; I am manifest only to some, my devotees — that is the purport. Veiled by yogamāyā: yoga is the combining, the joining, of the guṇas, and that itself is māyā — yogamāyā; or else, yoga is the Lord's collectedness of mind, and the māyā produced by it is yogamāyā; veiled, covered, by that yogamāyā, that is. Therefore this deluded world does not know me, the unborn, the imperishable."},
           ],
           words=[
               ["na", "not"],
               ["aham", "I"],
               ["prakāśaḥ", "manifest"],
               ["sarvasya", "to all"],
               ["yoga-māyā-samāvṛtaḥ", "veiled by yogamāyā"],
               ["mūḍhaḥ", "deluded"],
               ["ayam", "this"],
               ["na", "not"],
               ["abhijānāti", "knows"],
               ["lokaḥ", "world"],
               ["mām", "me"],
               ["ajam", "unborn"],
               ["avyayam", "imperishable"],
           ]),
        _v([
            "vedāhaṃ samatītāni vartamānāni cārjuna |",
            "bhaviṣyāṇi ca bhūtāni māṃ tu veda na kaścana",
        ], "|| 26 ||",
           "I know the beings that are past, that are present, and that are yet to come, Arjuna; but no one knows me.",
           bhashya=[
               {"text": "yayā yogamāyayā samāvṛtaṃ māṃ lokaḥ nābhijānāti, na asau yogamāyā madīyā satī mama īśvarasya māyāvinaḥ jñānaṃ pratibadhnāti yathā anyasyāpi māyāvinaḥ māyājñānaṃ tadvat. yataḥ evaṃ ataḥ–", "intro": True, "tr": "The yogamāyā veiled by which the world does not know me, being my own, does not obstruct the knowledge of me, the Lord, the possessor of māyā — just as the māyā of any other magician does not obstruct his own knowledge. Since this is so, therefore —"},
               {"text": "veda iti. ahaṃ tu veda jāne samatītāni samatikrāntāni bhūtāni, tathā vartamānāni ca arjuna bhaviṣyāṇi ca bhūtāni veda ahaṃ, māṃ tu veda na kaścana madbhaktaṃ maccharaṇaṃ ekaṃ muktvā, mattattva vedanābhāvādeva na māṃ bhajate.", "tr": "'I know the beings that are past…' But I know, am aware of, beings that are past, gone by, and those present, Arjuna, and those to come; but no one knows me, except the one devotee who has taken refuge in me. It is just because they do not know my reality that they do not worship me."},
           ],
           words=[
               ["veda", "know"],
               ["aham", "I"],
               ["samatītāni", "the past"],
               ["vartamānāni", "the present"],
               ["ca", "and"],
               ["arjuna", "O Arjuna"],
               ["bhaviṣyāṇi", "those to come"],
               ["ca", "and"],
               ["bhūtāni", "beings"],
               ["mām", "me"],
               ["tu", "but"],
               ["veda", "knows"],
               ["na", "not"],
               ["kaścana", "anyone"],
           ]),
        _v([
            "icchādveṣasamutthena dvandvamohena bhārata |",
            "sarvabhūtāni sammohaṃ sarge yānti parantapa",
        ], "|| 27 ||",
           "Through the delusion of the pairs of opposites, arising from desire and aversion, O Bhārata, all beings fall into bewilderment at birth, O scorcher of foes.",
           bhashya=[
               {"text": "kena punaḥ mattattva vedanapratibandhane pratibaddhāni santi jāyamānāni sarvabhūtāni māṃ na vidanti ityapekṣāyāṃ idaṃ āha–", "intro": True, "tr": "By what obstacle to the knowledge of my reality are all beings, as they are born, obstructed, so that they do not know me? In answer to this he says:"},
               {"text": "icchā iti. icchādveṣasamutthena icchā ca dveṣaśca icchādveṣau tābhyāṃ samuttiṣṭhatīti icchādveṣasamutthaḥ. keneti viśeṣāpekṣāyāṃ idaṃ āha– dvandvamohena iti. dvandvanimittaḥ mohaḥ dvandvamohaḥ tena. tau eva icchādveṣau śītoṣṇavat parasparaviruddhau sukhaduḥkhataddhetu viṣayau yathākālaṃ sarvabhūtaiḥ sambadhyamānau dvandvaśabdena abhidhīyete. tatra yadā icchādveṣau sukhaduḥkhataddhetusamprāptau labdhātmakau bhavataḥ, tadā tau sarvabhūtānāṃ prajñāyāḥ svavaśāpādanadvāreṇa paramārthatattvaviṣayajñānotpatti pratibandhakāraṇaṃ mohaṃ janayataḥ. na hi icchādveṣadoṣaparavaśīkṛtacittasya yathābhūtārthaviṣayajñānaṃ utpadyate bahirapi, kimu vaktavyaṃ tābhyāṃ āviṣṭabuddheḥ sammūḍhasya pratyagātmani bahupratibandhe jñānaṃ notpadyate iti. ataḥ tena icchādveṣasamutthena dvandvamohena, bhārata bharatānvayaja, sarvabhūtāni sammohitāni santi sammohaṃ sammūḍhatāṃ sarge janmani utpattikāle ityetat yānti gacchanti he parantapa. mohavaśāni eva sarvabhūtāni jāyamānāni jāyante ityabhiprāyaḥ. yataḥ evaṃ ataḥ tena dvandvamohena pratibaddhaprajñānāni sarvabhūtāni sammohitāni māṃ ātmabhūtaṃ na jānanti, ataḥ evaṃ ātmabhāvena māṃ na bhajante.", "tr": "'By the delusion of the pairs arising from desire and aversion…' Arising from desire and aversion: that which arises from desire and aversion. To the question, which in particular, he says: by the delusion of the pairs — the delusion caused by the pairs. Desire and aversion themselves, mutually opposed like cold and heat, having pleasure, pain and their causes as objects, and coming into relation with all beings at their due times, are called by the word 'pairs'. When desire and aversion take shape on the attainment of pleasure, pain and their causes, they produce in all beings delusion, which obstructs the arising of knowledge of the supreme reality by bringing their understanding under their own power. For in one whose mind has been subjected to the faults of desire and aversion, knowledge of things as they are does not arise even regarding outer things; how much less need it be said that knowledge does not arise regarding the inmost Self, beset by many obstacles, in the utterly deluded whose understanding is possessed by those two. Therefore, by that delusion of the pairs arising from desire and aversion, O Bhārata, born of the line of Bharata, all beings, deluded, go to utter delusion at creation, at birth, at the time of their arising, scorcher of foes. All beings are born already in the power of delusion — that is the purport. Since this is so, all beings, their understanding obstructed by that delusion of the pairs, deluded, do not know me as their Self, and so do not worship me as their Self."},
           ],
           words=[
               ["icchā-dveṣa-samutthena", "arising from desire and aversion"],
               ["dvandva-mohena", "by the delusion of the pairs"],
               ["bhārata", "O Bhārata"],
               ["sarva-bhūtāni", "all beings"],
               ["sammoham", "to delusion"],
               ["sarge", "at birth"],
               ["yānti", "go"],
               ["parantapa", "O scorcher of foes"],
           ]),
        _v([
            "yeṣāṃ tvantagataṃ pāpaṃ janānāṃ puṇyakarmaṇām |",
            "te dvandvamohanirmuktā bhajante māṃ dṛḍhavratāḥ",
        ], "|| 28 ||",
           "But those people of pure deeds whose sin has come to an end, freed from the delusion of opposites, worship me, firm in their vows.",
           bhashya=[
               {"text": "ke punaḥ anena dvandva mohena nirmuktāḥ santaḥ tvāṃ viditvā yathāśāstraṃ ātmabhāvena bhajante ityapekṣitaṃ arthaṃ darśayituṃ āha.", "intro": True, "tr": "To show what was asked — who, freed from this delusion of the pairs, know you and worship you as their Self, according to the scriptures — he says:"},
               {"text": "yeṣāṃ iti. yeṣāṃ tu punaḥ antagataṃ samāptaprāyaṃ kṣīṇaṃ pāpaṃ janānāṃ puṇyakarmaṇāṃ puṇyaṃ karma yeṣāṃ sattvaśuddhikāraṇaṃ vidyate te puṇyakarmāṇaḥ teṣāṃ puṇyakarmaṇāṃ te dvandvamohanirmuktāḥ yathoktena dvandvamohena nirmuktāḥ bhajante māṃ paramātmānaṃ dṛḍhavratāḥ. “evameva paramārthatattvaṃ, nānyathā” ityevaṃ sarvaparityāgavratena niścitavijñānāḥ dṛḍhavratāḥ ucyante.", "tr": "'But those men of meritorious deeds whose sin has come to an end…' But those men of meritorious deeds — who have meritorious deeds that bring about purity of mind — in whom sin has come to an end, is almost finished, has dwindled away — they, freed from the delusion of the pairs as described, worship me, the supreme Self, firm in their vows. Those whose understanding is settled — 'such alone is the supreme reality, not otherwise' — by the vow of giving up everything are called firm in their vows."},
           ],
           words=[
               ["yeṣām", "of whom"],
               ["tu", "but"],
               ["anta-gatam", "has come to an end"],
               ["pāpam", "sin"],
               ["janānām", "of men"],
               ["puṇya-karmaṇām", "of meritorious deeds"],
               ["te", "they"],
               ["dvandva-moha-nirmuktāḥ", "freed from the delusion of the pairs"],
               ["bhajante", "worship"],
               ["mām", "me"],
               ["dṛḍha-vratāḥ", "firm in their vows"],
           ]),
        _v([
            "jarāmaraṇamokṣāya māmāśritya yatanti ye |",
            "te brahma tadviduḥ kṛtsnamadhyātmaṃ karma cākhilam",
        ], "|| 29 ||",
           "Those who strive for release from old age and death, taking refuge in me, know that Brahman, the whole of the inner Self, and all action.",
           bhashya=[
               {"text": "te kimarthaṃ bhajante iti? ucyate.", "intro": True, "tr": "For what purpose do they worship? It is said:"},
               {"text": "jarā iti. jarāmaraṇamokṣāya jarāmaraṇayoḥ mokṣārthaṃ māṃ parameśvaraṃ āśritya matsamāhitacittāḥ santaḥ yatanti prayatante ye, te yat brahma paraṃ tat viduḥ kṛtsnaṃ samastaṃ, adhyātmaṃ pratyagātmaviṣayaṃ vastu tat viduḥ, karma ca akhilaṃ samastaṃ viduḥ.", "tr": "'For release from old age and death…' Those who, for release from old age and death, take refuge in me, the supreme Lord, with minds collected in me, and strive, make effort — they know that which is the supreme Brahman, entire, complete; they know the adhyātma, the reality whose object is the inmost Self; and they know action in its entirety, completely."},
           ],
           words=[
               ["jarā-maraṇa-mokṣāya", "for release from old age and death"],
               ["mām", "in me"],
               ["āśritya", "taking refuge"],
               ["yatanti", "strive"],
               ["ye", "who"],
               ["te", "they"],
               ["brahma", "Brahman"],
               ["tat", "that"],
               ["viduḥ", "know"],
               ["kṛtsnam", "entire"],
               ["adhyātmam", "what concerns the Self"],
               ["karma", "action"],
               ["ca", "and"],
               ["akhilam", "in its entirety"],
           ]),
        _v([
            "sādhibhūtādhidaivaṃ māṃ sādhiyajñaṃ ca ye viduḥ |",
            "prayāṇakāle'pi ca māṃ te viduryuktacetasaḥ",
        ], "|| 30 ||",
           "Those who know me together with the elemental, the divine and the sacrificial, with disciplined minds, know me even at the hour of death.",
           bhashya=[
               {"text": "sādhi iti sādhibhūtādhidaivaṃ adhibhūtaṃ ca adhidaivaṃ ca adhibhūtādhidaivaṃ saha adhibhūtādhidaivena vartate iti sādhibhūtādhidaivaṃ ca māṃ ye viduḥ, sādhiyajñaṃ ca saha adhiyajñena sādhiyajñaṃ ye viduḥ, prayāṇakāle maraṇakāle api ca māṃ te viduḥ. yuktacetasaḥ samāhitacittāḥ iti.", "tr": "'Those who know me together with the adhibhūta and the adhidaiva…' Those who know me together with the adhibhūta and the adhidaiva, and together with the adhiyajña — they know me even at the time of departure, at the time of death, their minds disciplined, collected."},
           ],
           words=[
               ["sa-adhibhūta-adhidaivam", "together with the adhibhūta and the adhidaiva"],
               ["mām", "me"],
               ["sa-adhiyajñam", "together with the adhiyajña"],
               ["ca", "and"],
               ["ye", "who"],
               ["viduḥ", "know"],
               ["prayāṇa-kāle", "at the time of departure"],
               ["api", "even"],
               ["ca", "and"],
               ["mām", "me"],
               ["te", "they"],
               ["viduḥ", "know"],
               ["yukta-cetasaḥ", "with disciplined minds"],
           ]),
        "ornament",
        {"colophon": "iti śrīmahābhārate śatasāhasryāṃ saṃhitāyāṃ vaiyāsikyāṃ bhīṣmaparvaṇi śrīmadbhagavadgītāsūpaniṣatsu brahmavidyāyāṃ yogaśāstre śrīkṛṣṇārjuna saṃvāde jñānavijñānayogo nāma saptamo'dhyāyaḥ", "gloss": "Thus, in the Bhagavad Gītā — the Upaniṣad, the knowledge of Brahman, the scripture of yoga, the dialogue of Śrī Kṛṣṇa and Arjuna — within the Bhīṣma Parva of the Mahābhārata, the collection of a hundred thousand verses by Vyāsa, ends the seventh chapter, Jñānavijñāna Yoga."},
        {"colophon": "iti śrī matparamahaṃsa parivrājakācāryagovindabhagavatpūjyapādaśiṣya śrīmacchaṅkarabhagavataḥ kṛtau, śrīmadbhagavadgītābhāṣye jñānavijñānayogo nāma saptamo'dhyāyaḥ", "gloss": "Thus ends the seventh chapter, Jñānavijñāna Yoga, of the commentary on the Bhagavad Gītā composed by Śrī Śaṅkara Bhagavat, wandering ascetic of the highest order and disciple of Śrī Govinda Bhagavatpāda."},
    ],
}
