# -*- coding: utf-8 -*-
# Copyright 2026 Pradyumna Revur — CC BY 4.0 (see LICENSE)
# Bhagavad Gītā, chapter 14 (Guṇatrayavibhāga Yoga), with Śaṅkara's bhāṣya. The Sanskrit
# (mūla and bhāṣya, both public domain) is converted from the text layer of
# the Ramakrishna Math, Hyderabad edition (2013), whose legacy Telugu font was
# mapped to Unicode glyph by glyph; its Telugu translation is not used. Collated
# against Sanskrit Wikisource and the Pullela Śrīrāmacandruḍu edition; every
# correction is logged in SOURCES §7.4. The English of the verses and of the
# bhāṣya is original, made from the Sanskrit. Generated from the collated text — edit here, not
# upstream.


def _v(padas, num, gloss, bhashya=None, words=None):
    d = {"padas": padas, "num": num, "gloss": gloss}
    if bhashya:
        d["bhashya"] = bhashya
    if words:
        d["words"] = words
    return d


STOTRA = {
    "deity": "gita",
    "doc_title": "Bhagavad Gītā 14 · Guṇatrayavibhāga Yoga · Śaṅkara Bhāṣya",
    "app_title": "Gītā 14",
    "h1": "Bhagavad Gītā · Chapter 14",
    "subtitle": "Guṇatrayavibhāga Yoga · the three guṇas · with Śaṅkara's bhāṣya",
    "note": "The three guṇas of prakṛti — sattva, rajas and tamas — how each binds, how each shows itself, and what follows from each; and the marks of one who has gone beyond them.",
    "footer": "Source: Śrīmad Bhagavadgītā Śaṅkarabhāṣyamu (Ramakrishna Math, Hyderabad, 2013), Sanskrit mūla and bhāṣya only, collated with Sanskrit Wikisource and the Pullela Śrīrāmacandruḍu edition; translations original. See SOURCES §7.4.",
    "nav": [('‹ chapter 13', 'gita-bhashya-13-iast.html'), ('all chapters', '../../index.html#gita'), ('chapter 15 ›', 'gita-bhashya-15-iast.html')],
    "sections": [
        {"bhashya": [
            {"text": "sarvam utpadyamānaṃ kṣetrakṣetrajñasaṃyogāt utpadyate ityuktam. tat katham iti pradarśanārthaṃ “paraṃ bhūyaḥ” ityādi adhyāyaḥ ārabhyate. athavā “īśvaraparatantrayoḥ kṣetrakṣetrajñayoḥ jagatkāraṇatvam na tu sāṅkhyānām iva svatantrayoḥ” ityemavarthaṃ prakṛtisthatvaṃ, guṇeṣu ca saṅgaḥ saṃsārakāraṇam ityuktam. (13.21) kasmin guṇe kathaṃ saṅgaḥ? ke vā guṇāḥ? kathaṃ vā te badhnanti? iti, guṇebhyaḥ ca mokṣaṇaṃ kathaṃ syāt? muktasya ca lakṣaṇaṃ vaktavyam. ityevamarthaṃ ca.", "tr": "It was said that everything that arises arises from the union of the field and the knower of the field. To show how, the chapter beginning 'once more, the supreme' starts. Or else: to show that the field and the knower of the field, dependent on the Lord, are the cause of the world, not independent as the Sāṅkhyas hold. And it was said that abiding in nature and attachment to the guṇas are the cause of saṃsāra (13.21). Attachment to which guṇa, and how? What are the guṇas? How do they bind? How can there be release from the guṇas? And the marks of the one released are to be told. For this purpose too [the chapter begins]."},
        ], "summary": "bhāṣya · the chapter's opening"},
        {"speaker": "śrī bhagavānuvāca"},
        _v([
            "paraṃ bhūyaḥ pravakṣyāmi jñānānāṃ jñānamuttamam |",
            "yad jñātvā munayassarve parāṃ siddhimito gatāḥ",
        ], "|| 1 ||",
           "The Blessed Lord said: I will declare again the supreme knowledge, the best of all knowledge, knowing which all the sages have gone from here to the highest perfection.",
           bhashya=[
               {"text": "paraṃ “jñānam” iti vyavahitena sambandhaḥ. bhūyaḥ punaḥ, pūrveṣu sarveṣu adhyāyeṣu asakṛt uktam api, pravakṣyāmi, tacca, paraṃ paravastuviṣayatvāt. kiṃ tat? jñānam sarveṣāṃ jñānānām uttamam, uttamaphalatvāt. “jñānānām” iti na amānitvādīnam, (13.7'20) kiṃ tarhi? yajñādijñeyavastuviṣayāṇām iti. tāni na mokṣāya. idaṃ tu mokṣāya iti parottamaśabdābhyāṃ stauti śrotṛbuddhirucyutpādanārtham. yad jñātvā, yad jñānaṃ jñātvā prāpya munayaḥ sannyāsinaḥ mananaśīlāḥ sarve parāṃ siddhiṃ mokṣākhyām itaḥ asmāt dehabandhanāt ūrdhvaṃ gatāḥ prāptāḥ.", "tr": "'Supreme' is connected with the distant word 'knowledge'. Once more, again — though it was said repeatedly in all the earlier chapters — I will declare it; and it is supreme because its object is the supreme reality. What is it? The knowledge highest among all knowledges, because it has the highest fruit. 'Among knowledges' does not mean humility and the rest (13.7–11), but knowledges whose objects are knowable things such as sacrifices. Those are not for liberation; this is for liberation — so he praises it with the words 'supreme' and 'highest', to awaken the hearer's interest. Knowing which, having gained which knowledge, all the munis — renouncers given to reflection — have gone, reached, from here, above this bondage of the body, to the supreme perfection called liberation."},
           ],
           words=[
               ["param", "the supreme"],
               ["bhūyaḥ", "once more"],
               ["pravakṣyāmi", "I will declare"],
               ["jñānānām", "of knowledges"],
               ["jñānam", "knowledge"],
               ["uttamam", "the highest"],
               ["yat", "which"],
               ["jñātvā", "knowing"],
               ["munayaḥ", "the sages"],
               ["sarve", "all"],
               ["parām", "to supreme"],
               ["siddhim", "perfection"],
               ["itaḥ", "from here"],
               ["gatāḥ", "have gone"],
           ]),
        _v([
            "idaṃ jñānamupāśritya mama sādharmyamāgatāḥ |",
            "sarge'pi nopajāyante pralaye na vyathanti ca",
        ], "|| 2 ||",
           "Resorting to this knowledge and attaining my nature, they are not born at the creation, nor are they troubled at the dissolution.",
           bhashya=[
               {"text": "asyāḥ ca siddheḥ aikāntikatvaṃ ucyate.", "intro": True, "tr": "The certainty of this perfection is told:"},
               {"text": "idaṃ jñānaṃ yathoktam, upāśritya jñānasādhanam anuṣṭhāya ityetat. mama parameśvarasya, sādharmyaṃ matsvarūpatām, āgatāḥ prāptāḥ ityarthaḥ. na tu samānadharmatā sādharmyam, kṣetrajñeśvarayoḥ bhedānabhyupagamāt gītāśāstre. phalavādaścāyaṃ stutyartham ucyate. sarge'pi sṛṣṭikāle'pi na upajāyante na utpadyante. pralaye brahmaṇaḥ api vināśakāle, na vyathanti ca vyathāṃ nāpadyante. na cyavanti ityarthaḥ.", "tr": "Resorting to this knowledge as described — practising the means of knowledge, that is — they have come to, attained, likeness with me, the supreme Lord: my very nature, that is. Not sameness of attributes, since the teaching of the Gītā does not admit a difference between the knower of the field and the Lord. This statement of the fruit is made for praise. Even at creation, at the time of emanation, they are not born, do not arise; and at the dissolution, the time of the destruction even of Brahmā, they do not suffer, do not come to distress; they do not fall, that is."},
           ],
           words=[
               ["idam", "this"],
               ["jñānam", "knowledge"],
               ["upāśritya", "resorting to"],
               ["mama", "my"],
               ["sādharmyam", "likeness"],
               ["āgatāḥ", "having attained"],
               ["sarge", "at creation"],
               ["api", "even"],
               ["na", "not"],
               ["upajāyante", "are they born"],
               ["pralaye", "at the dissolution"],
               ["na", "not"],
               ["vyathanti", "do they suffer"],
               ["ca", "and"],
           ]),
        _v([
            "mama yonirmahadbrahma tasmin garbhaṃ dadhāmyaham |",
            "sambhavaḥ sarvabhūtānāṃ tato bhavati bhārata",
        ], "|| 3 ||",
           "The great Brahman is my womb; in it I place the seed. From that, O Bhārata, comes the birth of all beings.",
           bhashya=[
               {"text": "kṣetrakṣetrajñasaṃyogaḥ īdṛśaḥ bhūtakāraṇam ityāha –", "intro": True, "tr": "He says what kind of union of the field and the knower of the field is the cause of beings:"},
               {"text": "mama svabhūtā madīyā māyā triguṇātmikā prakṛtiḥ yoniḥ, sarvabhūtānāṃ, kāraṇam. sarvakāryebhyaḥ mahattvattāt kāraṇatvāt bṛṃhaṇatvāt ca svavikārāṇāṃ mahat brahma iti yoniḥ eva viśiṣyate. tasmin mahati brahmaṇi yonau, garbhaṃ hiraṇyagarbhasya janmano bījaṃ, sarvabhūtajanmakāraṇaṃ bījaṃ, dadhāmi nikṣipāmi. kṣetrakṣetrajñaprakṛtidvayaśaktimān īśvaraḥ aham avidyākāmakarmopādhisvarūpānuvidhāyinaṃ kṣetrajñaṃ kṣetreṇa saṃyojayāmītyarthaḥ. sambhavaḥ utpattiḥ sarvabhūtānāṃ hiraṇyagarbhotpattidvāreṇa, tataḥ tasmāt garbhanidhānāt, bhavati he bhārata.", "tr": "My womb: my own māyā, nature made of the three guṇas, is the womb, the cause, of all beings. Being greater than all effects, being their cause, and causing its own modifications to grow, it is called the great Brahman; so the womb is specified. In that great Brahman, the womb, I place, deposit, the germ — the seed of the birth of Hiraṇyagarbha, the seed that is the cause of the birth of all beings. I, the Lord, possessing the power of the two natures, the field and the knower of the field, join the knower of the field, conforming to the adjuncts of ignorance, desire and action, with the field — that is the meaning. From that, from that placing of the germ, comes the birth, the arising, of all beings, through the arising of Hiraṇyagarbha, O Bhārata."},
           ],
           words=[
               ["mama", "my"],
               ["yoniḥ", "womb"],
               ["mahat", "the great"],
               ["brahma", "Brahman"],
               ["tasmin", "in it"],
               ["garbham", "the germ"],
               ["dadhāmi", "place"],
               ["aham", "I"],
               ["sambhavaḥ", "the birth"],
               ["sarva-bhūtānām", "of all beings"],
               ["tataḥ", "from that"],
               ["bhavati", "comes"],
               ["bhārata", "O Bhārata"],
           ]),
        _v([
            "sarvayoniṣu kaunteya mūrtayaḥ sambhavanti yāḥ |",
            "tāsāṃ brahma mahadyonirahaṃ bījapradaḥ pitā",
        ], "|| 4 ||",
           "Whatever forms are born in any womb, son of Kuntī, the great Brahman is their womb, and I am the seed-giving father.",
           bhashya=[
               {"text": "sarvayoniṣviti : devapitṛmanuṣyapaśumṛgādi sarvayoniṣu, kaunteya, mūrtayaḥ dehasaṃsthānalakṣaṇāḥ mūrchitāṅgāvayavāḥ mūrtayaḥ sambhavanti yāḥ tāsāṃ mūrtīnāṃ brahma mahat sarvāvasthaṃ yoniḥ kāraṇam. aham īśaḥ bījapradaḥ garbhādhānasya kartā pitā.", "tr": "'In all wombs…' In all wombs — of gods, ancestors, men, cattle, beasts and the rest — Kaunteya, whatever forms arise — forms consisting in bodily shapes, with limbs and parts developed — of those forms the great Brahman, in all its states, is the womb, the cause; I, the Lord, am the seed-giving father, the one who deposits the germ."},
           ],
           words=[
               ["sarva-yoniṣu", "in all wombs"],
               ["kaunteya", "O son of Kuntī"],
               ["mūrtayaḥ", "forms"],
               ["sambhavanti", "arise"],
               ["yāḥ", "whatever"],
               ["tāsām", "of them"],
               ["brahma", "Brahman"],
               ["mahat", "the great"],
               ["yoniḥ", "the womb"],
               ["aham", "I"],
               ["bīja-pradaḥ", "the seed-giving"],
               ["pitā", "father"],
           ]),
        _v([
            "sattvaṃ rajastama iti guṇāḥ prakṛtisambhavāḥ |",
            "nibadhnanti mahābāho dehe dehinamavyayam",
        ], "|| 5 ||",
           "Sattva, rajas and tamas — these guṇas born of prakṛti bind the imperishable embodied one in the body, mighty-armed one.",
           bhashya=[
               {"text": "ke guṇāḥ kathaṃ badhnanti ityucyate", "intro": True, "tr": "What are the guṇas, and how do they bind? It is said:"},
               {"text": "sattvaṃ rajaḥ tamaḥ ityevaṃ nāmānaḥ, “guṇāḥ” iti pāribhāṣikaḥ śabdaḥ, na rūpādivat dravyāśritāḥ. na ca guṇaguṇinoḥ anyatvam atra vivakṣitam, tasmād guṇāḥ iva nityaparatantrāḥ kṣetrajñaṃ prati, avidyātmakatvāt kṣetrajñaṃ nibadhnantīva. tam āspadīkṛtya ātmānaṃ pratilabhante iti nibadhnanti ityucyate. te ca prakṛtisambhavāḥ bhagavanmāyāsambhavāḥ, nibadhnanti iva, mahābāho mahāntau samarthatarau ājānupralambau bāhū yasya saḥ mahābāhuḥ. he mahābāho, dehe śarīre, dehinaṃ dehavantam, avyayam avyayatvaṃ ca uktam “anāditvāt” (13.31) ityādiślokena. nanu “dehī na lipyate” (13.31) ityuktam. tat katham iha nibadhnanti iti anyathā ucyate? parihṛtam asmābhiḥ ivaśabdena “nibadhnantīva” iti.", "tr": "Named sattva, rajas and tamas: 'guṇas' is a technical term; they are not qualities resting in substances like colour and the rest. Nor is a difference between quality and its possessor meant here. So, being like qualities, ever dependent on the knower of the field, and being of the nature of ignorance, they seem to bind the knower of the field; taking him as their ground, they come into being — hence it is said they bind. Born of nature, born of the Lord's māyā, they bind, as it were, O mighty-armed — he whose arms are great, very capable, reaching to the knees, is mighty-armed — in the body, the embodied one, who is imperishable, as was stated in the verse 'being beginningless' (13.31). Objection: it was said 'the embodied one is not tainted' (13.31); how is it said otherwise here, that they bind? We have answered with the word 'as it were': 'they bind, as it were'."},
           ],
           words=[
               ["sattvam", "sattva"],
               ["rajaḥ", "rajas"],
               ["tamaḥ", "tamas"],
               ["iti", "thus"],
               ["guṇāḥ", "the guṇas"],
               ["prakṛti-sambhavāḥ", "born of nature"],
               ["nibadhnanti", "bind"],
               ["mahā-bāho", "O mighty-armed"],
               ["dehe", "in the body"],
               ["dehinam", "the embodied one"],
               ["avyayam", "imperishable"],
           ]),
        _v([
            "tatra sattvaṃ nirmalatvāt prakāśakamanāmayam |",
            "sukhasaṅgena badhnāti jñānasaṅgena cā'nagha",
        ], "|| 6 ||",
           "Of these, sattva, being stainless, is luminous and free from affliction; it binds by attachment to happiness and attachment to knowledge, sinless one.",
           bhashya=[
               {"text": "tatra sattvādīnāṃ sattvasyaiva tāvat lakṣaṇam ucyate –", "intro": True, "tr": "Of these, the marks of sattva are told first:"},
               {"text": "tatra sattvamiti : nirmalatvāt sphaṭikamaṇiḥ iva prakāśakam anāmayaṃ nirupadravaṃ sattvaṃ tat badhnāti. katham? sukhasaṅgena. “sukhī aham” iti viṣayabhūtasya sukhasya viṣayiṇi ātmani saṃśleṣāpādanaṃ mṛṣaiva sukhe sañjanam iti. sā eṣā avidyā, na hi viṣayadharmaḥ viṣayiṇaḥ bhavati. icchādi ca dhṛtyantaṃ kṣetrasyaiva viṣayasya dharmaḥ iti uktaṃ bhagavatā. ataḥ avidyayaiva svakīyadharmabhūtayā viṣayaviṣayya vivekalakṣaṇayā asvātmabhūte sukhe sañjayatīva āsaktamiva karoti asaṅgaṃ saktamiva karoti, asukhinaṃ sukhinamiva. tathā jñānasaṅgena ca. jñānamiti sukhasāhacaryāt kṣetrasya viṣayasya antaḥ karaṇasyaiva dharmaḥ, na ātmanaḥ. ātmadharmatve saṅgānupapatteḥ bandhānupapatteśca. sukhe iva jñānādau saṅgaḥ mantavyaḥ he anagha avyasana.", "tr": "'Of these, sattva, being stainless…' Being stainless, like a crystal, sattva is illuminating and free from ill, free from trouble; it binds. How? By attachment to happiness. Bringing about, in the subject, the Self, the connection with happiness, which is an object, as in 'I am happy', is a false attachment to happiness. This is ignorance; for an attribute of the object does not belong to the subject. And the Lord has said that desire and the rest, up to steadfastness, are attributes of the field alone, the object. So, through ignorance alone — its own attribute, consisting in failure to discriminate object and subject — it attaches him, as it were, to happiness, which is not his own; it makes the unattached seem attached, the one without happiness seem happy. Likewise by attachment to knowledge. Knowledge, because it goes along with happiness, is an attribute of the field, the object, the inner organ, not of the Self; if it were an attribute of the Self, attachment and bondage would be impossible. Attachment to knowledge and the rest is to be understood as with happiness, O sinless one, free of vice."},
           ],
           words=[
               ["tatra", "of these"],
               ["sattvam", "sattva"],
               ["nirmalatvāt", "being stainless"],
               ["prakāśakam", "illuminating"],
               ["anāmayam", "free from ill"],
               ["sukha-saṅgena", "by attachment to happiness"],
               ["badhnāti", "binds"],
               ["jñāna-saṅgena", "by attachment to knowledge"],
               ["ca", "and"],
               ["anagha", "O sinless one"],
           ]),
        _v([
            "rajo rāgātmakaṃ viddhi tṛṣṇā''saṅgasamudbhavam |",
            "tannibadhnāti kaunteya karmasaṅgena dehinam",
        ], "|| 7 ||",
           "Know rajas to be of the nature of passion, the source of craving and attachment; it binds the embodied one by attachment to action, son of Kuntī.",
           bhashya=[
               {"text": "rajaḥ rāgātmakaṃ – rañjanāt rāgaḥ gairikādivadrāgātmakaṃ viddhi jānīhi. tṛṣṇā''saṅga samudbhavaṃ tṛṣṇā aprāptābhilāṣaḥ, āsaṅgaḥ prāpte viṣaye manasaḥ prītilakṣaṇaḥ saṃśleṣaḥ, tṛṣṇā''saṅgayoḥ samudbhavaṃ tṛṣṇā''saṅgasamudbhavam. tat rajaḥ nibadhnāti kaunteya! karmasaṅgena, dṛṣṭādṛṣṭārtheṣu karmasu(raṃ)sañjanaṃ tatparatā karmasaṅgaḥ, tena nibadhnāti rajaḥ dehinam.", "tr": "Know that rajas is of the nature of passion — passion, from colouring, like red ochre — arising from thirst and attachment: thirst is longing for what one has not got; attachment is the mind's clinging, consisting in fondness, to an object obtained; that from which thirst and attachment arise. That rajas binds the embodied one, Kaunteya, by attachment to action — attachment to action is being bound up in, intent on, actions aimed at seen and unseen ends; by that rajas binds the embodied one."},
           ],
           words=[
               ["rajaḥ", "rajas"],
               ["rāga-ātmakam", "of the nature of passion"],
               ["viddhi", "know"],
               ["tṛṣṇā-āsaṅga-samudbhavam", "arising from thirst and attachment"],
               ["tat", "that"],
               ["nibadhnāti", "binds"],
               ["kaunteya", "O son of Kuntī"],
               ["karma-saṅgena", "by attachment to action"],
               ["dehinam", "the embodied one"],
           ]),
        _v([
            "tamastvajñānajaṃ viddhi mohanaṃ sarvadehinām |",
            "pramādālasyanidrābhistannibadhnāti bhārata",
        ], "|| 8 ||",
           "But know tamas to be born of ignorance, deluding all embodied beings; it binds by heedlessness, sloth and sleep, O Bhārata.",
           bhashya=[
               {"text": "tamastviti : tamaḥ tṛtīyaḥ guṇaḥ, ajñānajam ajñānāt jātam ajñānajaṃ, viddhi mohanaṃ mohakaram avivekakaraṃ, sarvadehināṃ sarveṣāṃ dehavatāṃ, pramādālasyanidrābhiḥ pramādaśca ālasyaṃ ca nidrā ca pramādālasyanidrāḥ, tābhiḥ tat tamaḥ nibadhnāti bhārata.", "tr": "'But know tamas…' Tamas, the third guṇa, know to be born of ignorance, arising from ignorance; deluding, causing delusion, non-discrimination, in all embodied beings, all who have bodies. By heedlessness, sloth and sleep that tamas binds, Bhārata."},
           ],
           words=[
               ["tamaḥ", "tamas"],
               ["tu", "but"],
               ["ajñāna-jam", "born of ignorance"],
               ["viddhi", "know"],
               ["mohanam", "deluding"],
               ["sarva-dehinām", "all embodied beings"],
               ["pramāda-ālasya-nidrābhiḥ", "by heedlessness, sloth and sleep"],
               ["tat", "that"],
               ["nibadhnāti", "binds"],
               ["bhārata", "O Bhārata"],
           ]),
        _v([
            "sattvaṃ sukhe sañjayati rajaḥ karmaṇi bhārata |",
            "jñānamāvṛtya tu tamaḥ pramāde sañjayatyuta",
        ], "|| 9 ||",
           "Sattva attaches one to happiness, rajas to action, O Bhārata; but tamas, veiling knowledge, attaches one to heedlessness.",
           bhashya=[
               {"text": "punaḥ guṇānāṃ vyāpāraḥ saṅkṣepataḥ ucyate –", "intro": True, "tr": "The work of the guṇas is told again in brief:"},
               {"text": "sattvaṃ, sukhe sañjayati saṃśleṣayati. rajaḥ karmaṇi, he bhārata, “sañjayati” iti anuvartate. jñānaṃ sattvakṛtaṃ vivekam āvṛtya ācchādya tu tamaḥ, svena āvaraṇātmanā pramāde sañjayati, uta pramādaḥ prāptakartavyākaraṇam.", "tr": "Sattva attaches, binds, to happiness; rajas to action, Bhārata — 'attaches' carries over. But tamas, veiling knowledge — the discrimination produced by sattva — covering it with its own veiling nature, attaches to heedlessness. Heedlessness is not doing what one has to do."},
           ],
           words=[
               ["sattvam", "sattva"],
               ["sukhe", "to happiness"],
               ["sañjayati", "attaches"],
               ["rajaḥ", "rajas"],
               ["karmaṇi", "to action"],
               ["bhārata", "O Bhārata"],
               ["jñānam", "knowledge"],
               ["āvṛtya", "veiling"],
               ["tu", "but"],
               ["tamaḥ", "tamas"],
               ["pramāde", "to heedlessness"],
               ["sañjayati", "attaches"],
               ["uta", "indeed"],
           ]),
        _v([
            "rajastamaścābhibhūya sattvaṃ bhavati bhārata |",
            "rajassattvaṃ tamaścaiva tamassattvaṃ rajastathā",
        ], "|| 10 ||",
           "Sattva prevails by overpowering rajas and tamas, O Bhārata; rajas by overpowering sattva and tamas; and tamas likewise by overpowering sattva and rajas.",
           bhashya=[
               {"text": "uktaṃ kāryaṃ kadā kurvanti guṇāḥ iti ucyate –", "intro": True, "tr": "When do the guṇas do the work described? It is said:"},
               {"text": "rajaḥ tamaḥ ca ubhau api abhibhūya sattvaṃ, bhavati udbhavati vardhate yadā tadā labdhātmakaṃ sattvaṃ svakāryaṃ jñānasukhādi ārabhate, he bhārata! tathā rajoguṇaḥ sattvaṃ tamaḥ ca api abhibhūya vardhate yadā tadā karma tṛṣṇādi svakāryam ārabhate. tama ākhyaḥ guṇaḥ sattvaṃ rajaśca ubhāvapi abhibhūya tathaiva vardhate yadā tadā jñānāvaraṇādi svakāryam ārabhate.", "tr": "When sattva, overpowering both rajas and tamas, arises, increases, then, having come into its own, sattva begins its own work, knowledge, happiness and the rest, Bhārata. Likewise when the guṇa rajas, overpowering both sattva and tamas, increases, then it begins its own work, action, thirst and the rest. Likewise when the guṇa called tamas, overpowering both sattva and rajas, increases, then it begins its own work, the veiling of knowledge and the rest."},
           ],
           words=[
               ["rajaḥ", "rajas"],
               ["tamaḥ", "tamas"],
               ["ca", "and"],
               ["abhibhūya", "overpowering"],
               ["sattvam", "sattva"],
               ["bhavati", "arises"],
               ["bhārata", "O Bhārata"],
               ["rajaḥ", "rajas"],
               ["sattvam", "sattva"],
               ["tamaḥ", "tamas"],
               ["ca", "and"],
               ["eva", "likewise"],
               ["tamaḥ", "tamas"],
               ["sattvam", "sattva"],
               ["rajaḥ", "rajas"],
               ["tathā", "so"],
           ]),
        _v([
            "sarvadvāreṣu dehe'smin prakāśa upajāyate |",
            "jñānaṃ yadā tadā vidyāt vivṛddhaṃ sattvamityuta",
        ], "|| 11 ||",
           "When the light of knowledge shines through all the gates of this body, then one should know that sattva has increased.",
           bhashya=[
               {"text": "yadā yaḥ guṇa udbhūtaḥ bhavati tadā tasya kiṃ liṅgam iti ucyate–", "intro": True, "tr": "When a guṇa has arisen, what is its mark? It is said:"},
               {"text": "sarvadvāreṣu ātmanaḥ upalabdhidvārāṇi śrotrādīni sarvāṇi karaṇāni teṣu sarvadvāreṣu, antaḥkaraṇasya buddheḥ vṛttiḥ prakāśaḥ dehe asmin upajāyate, tadeva jñānaṃ, yadā evaṃ prakāśaḥ jñānākhyaḥ upajāyate tadā jñānaprakāśena liṅgena vidyāt, vivṛddham udbhūtaṃ, sattvam iti, uta api.", "tr": "When in all the gates — the gates through which the Self perceives, hearing and all the other instruments — in all these gates in this body there arises light, a function of the inner organ, the understanding, which is itself knowledge — when such light called knowledge arises, then by the mark of the light of knowledge one should know that sattva has increased, has arisen."},
           ],
           words=[
               ["sarva-dvāreṣu", "in all the gates"],
               ["dehe", "in body"],
               ["asmin", "this"],
               ["prakāśaḥ", "light"],
               ["upajāyate", "arises"],
               ["jñānam", "knowledge"],
               ["yadā", "when"],
               ["tadā", "then"],
               ["vidyāt", "one should know"],
               ["vivṛddham", "has increased"],
               ["sattvam", "sattva"],
               ["iti", "that"],
               ["uta", "indeed"],
           ]),
        _v([
            "lobhaḥ pravṛttirārambhaḥ karmaṇāmaśamaḥ spṛhā |",
            "rajasyetāni jāyante vivṛddhe bharatarṣabha",
        ], "|| 12 ||",
           "Greed, activity, the undertaking of actions, restlessness and longing — these arise when rajas increases, O best of the Bhāratas.",
           bhashya=[
               {"text": "rajasaḥ udbhūtasya idaṃ cihnam –", "intro": True, "tr": "This is the sign of rajas when it has arisen:"},
               {"text": "lobhaḥ paradravyāditsā, pravṛttiḥ pravartanaṃ sāmānyaceṣṭā, ārambhaḥ, kasya? karmaṇām. aśamaḥ anupaśamaḥ, harṣarāgādipravṛttiḥ, spṛhā sarvasāmānyavastuviṣayā tṛṣṇā, rajasi guṇe vivṛddhe etāni liṅgāni, jāyante he bharatarṣabha.", "tr": "Greed, the wish to take another's property; activity, general exertion; undertaking — of what? Of actions; restlessness, lack of calm, the play of elation, passion and the like; longing, thirst for all things in general — these marks arise when the guṇa rajas has increased, bull of the Bharatas."},
           ],
           words=[
               ["lobhaḥ", "greed"],
               ["pravṛttiḥ", "activity"],
               ["ārambhaḥ", "the undertaking"],
               ["karmaṇām", "of actions"],
               ["aśamaḥ", "restlessness"],
               ["spṛhā", "longing"],
               ["rajasi", "when rajas"],
               ["etāni", "these"],
               ["jāyante", "arise"],
               ["vivṛddhe", "has increased"],
               ["bharata-ṛṣabha", "O bull of the Bharatas"],
           ]),
        _v([
            "aprakāśo'pravṛttiśca pramādo moha eva ca |",
            "tamasyetāni jāyante vivṛddhe kurunandana",
        ], "|| 13 ||",
           "Darkness, inertness, heedlessness and delusion — these arise when tamas increases, O joy of the Kurus.",
           bhashya=[
               {"text": "aprakāśa iti : aprakāśaḥ avivekaḥ atyantam, apravṛttiḥ ca pravṛttyabhāvaḥ tatkāryaṃ pramādaḥ, mohaḥ eva ca avivekaḥ, mūḍhatā ityarthaḥ. tamasi guṇe vivṛddhe etāni liṅgāni jāyante, he kurunandana.", "tr": "'Darkness…' Darkness, utter lack of discrimination; inertia, absence of activity; its effect, heedlessness; and delusion, lack of discrimination, stupidity, that is — these marks arise when the guṇa tamas has increased, joy of the Kurus."},
           ],
           words=[
               ["aprakāśaḥ", "darkness"],
               ["apravṛttiḥ", "inertia"],
               ["ca", "and"],
               ["pramādaḥ", "heedlessness"],
               ["mohaḥ", "delusion"],
               ["eva ca", "and also"],
               ["tamasi", "when tamas"],
               ["etāni", "these"],
               ["jāyante", "arise"],
               ["vivṛddhe", "has increased"],
               ["kuru-nandana", "O joy of the Kurus"],
           ]),
        _v([
            "yadā sattve pravṛddhe tu pralayaṃ yāti dehabhṛt |",
            "tadottamavidāṃ lokānamalān pratipadyate",
        ], "|| 14 ||",
           "If the embodied one meets dissolution when sattva is increased, he goes to the pure worlds of those who know the highest.",
           bhashya=[
               {"text": "maraṇadvāreṇāpi yat phalaṃ prāpyate tadapi saṅgarāgahetukaṃ sarvaṃ gauṇam eva iti darśayannāha –", "intro": True, "tr": "Showing that whatever fruit is gained even through death is all secondary, caused by attachment and passion, he says:"},
               {"text": "yadā sattve, pravṛddhe udbhūte, tu, pralayaṃ maraṇaṃ, yāti pratipadyate, dehabhṛt ātmā, tadā uttamavidāṃ mahadāditattvavidām ityetat. lokān amalān malarahitān, pratipadyate, prāpnoti ityetat.", "tr": "But when the embodied one, the Self, goes to dissolution, meets death, while sattva is increased, has arisen, then he reaches, attains, the stainless worlds, free from stain, of those who know the highest — of those who know the principles such as mahat, that is."},
           ],
           words=[
               ["yadā", "when"],
               ["sattve", "sattva"],
               ["pravṛddhe", "has increased"],
               ["tu", "but"],
               ["pralayam", "to dissolution"],
               ["yāti", "goes"],
               ["deha-bhṛt", "the embodied one"],
               ["tadā", "then"],
               ["uttama-vidām", "of those who know the highest"],
               ["lokān", "the worlds"],
               ["amalān", "stainless"],
               ["pratipadyate", "he reaches"],
           ]),
        _v([
            "rajasi pralayaṃ gatvā karmasaṅgiṣu jāyate |",
            "tathā pralīnastamasi mūḍhayoniṣu jāyate",
        ], "|| 15 ||",
           "Meeting dissolution in rajas, he is born among those attached to action; dying in tamas, he is born in the wombs of the deluded.",
           bhashya=[
               {"text": "rajasi guṇe pravṛddhe, pralayaṃ maraṇaṃ, gatvā prāpya, karmasaṅgiṣu karmāsaktiyukteṣu manuṣyeṣu jāyate. tathā tadvadeva, pralīnaḥ mṛtaḥ, tamasi pravṛddhe, mūḍhayoniṣu paśvādiyoniṣu jāyate.", "tr": "Meeting dissolution, death, when the guṇa rajas has increased, one is born among those attached to action, among men given to clinging to action. Likewise, dying when tamas has increased, one is born in the wombs of the deluded, the wombs of animals and the like."},
           ],
           words=[
               ["rajasi", "in rajas"],
               ["pralayam", "dissolution"],
               ["gatvā", "meeting"],
               ["karma-saṅgiṣu", "among those attached to action"],
               ["jāyate", "one is born"],
               ["tathā", "likewise"],
               ["pralīnaḥ", "dying"],
               ["tamasi", "in tamas"],
               ["mūḍha-yoniṣu", "in the wombs of the deluded"],
               ["jāyate", "one is born"],
           ]),
        _v([
            "karmaṇaḥ sukṛtasyāhuḥ sāttvikaṃ nirmalaṃ phalam |",
            "rajasastu phalaṃ duḥkhamajñānaṃ tamasaḥ phalam",
        ], "|| 16 ||",
           "The fruit of good action, they say, is sāttvika and pure; the fruit of rajas is pain; and the fruit of tamas is ignorance.",
           bhashya=[
               {"text": "atītaślokārthasyaiva saṅkṣepaḥ ucyate –", "intro": True, "tr": "The meaning of the preceding verse is told in brief:"},
               {"text": "karmaṇaḥ sukṛtasya sāttvikasyetyarthaḥ. āhuḥ śiṣṭāḥ sāttvikam eva nirmalaṃ phalam iti. rajasaḥ tu phalaṃ duḥkhaṃ rājasasya karmaṇaḥ ityarthaḥ – karmādhikārāt. phalamapi duḥkhameva kāraṇānurūpyāt rājasameva. tathā ajñānaṃ tamasaḥ tāmasasya karmaṇaḥ adharmasya phalaṃ pūrvavat. kiñca guṇebhyaḥ bhavati '?", "tr": "Of good action — sāttvika action, that is — the wise say the fruit is sāttvika and stainless. But the fruit of rajas — of rājasa action, that is, since action is the topic — is pain: the fruit too is rājasa, being like its cause. Likewise ignorance is the fruit of tamas — of tāmasa action, of adharma — as before. And what comes from the guṇas?"},
           ],
           words=[
               ["karmaṇaḥ", "of action"],
               ["su-kṛtasya", "well done"],
               ["āhuḥ", "they say"],
               ["sāttvikam", "sāttvika"],
               ["nirmalam", "stainless"],
               ["phalam", "the fruit"],
               ["rajasaḥ", "of rajas"],
               ["tu", "but"],
               ["phalam", "the fruit"],
               ["duḥkham", "pain"],
               ["ajñānam", "ignorance"],
               ["tamasaḥ", "of tamas"],
               ["phalam", "the fruit"],
           ]),
        _v([
            "sattvātsañjāyate jñānaṃ rajaso lobha eva ca |",
            "pramādamohau tamaso bhavato'jñānameva ca",
        ], "|| 17 ||",
           "From sattva arises knowledge, from rajas greed; from tamas arise heedlessness and delusion, and ignorance too.",
           bhashya=[
               {"text": "sattvāt labdhātmakāt, sañjāyate samutpadyate, jñānaṃ, rajasaḥ lobhaḥ eva ca, pramādamohau ca ubhau tamasaḥ guṇāt bhavataḥ, ajñānam eva ca.", "tr": "From sattva, having come into its own, knowledge arises, is born; from rajas, greed; heedlessness and delusion, both, come from the guṇa tamas, and ignorance too."},
           ],
           words=[
               ["sattvāt", "from sattva"],
               ["sañjāyate", "arises"],
               ["jñānam", "knowledge"],
               ["rajasaḥ", "from rajas"],
               ["lobhaḥ", "greed"],
               ["eva ca", "indeed"],
               ["pramāda-mohau", "heedlessness and delusion"],
               ["tamasaḥ", "from tamas"],
               ["bhavataḥ", "come"],
               ["ajñānam", "ignorance"],
               ["eva ca", "and also"],
           ]),
        _v([
            "ūrdhvaṃ gacchanti sattvasthā madhye tiṣṭhanti rājasāḥ |",
            "jaghanyaguṇavṛttasthā adho gacchanti tāmasāḥ",
        ], "|| 18 ||",
           "Those abiding in sattva go upward; the rājasa stay in the middle; the tāmasa, abiding in the lowest workings of the guṇas, go downward.",
           bhashya=[
               {"text": "ūrdhvaṃ gacchanti devalokādiṣu utpadyante, sattvasthāḥ sattvaguṇavṛttasthāḥ. madhye tiṣṭhanti manuṣyeṣu utpadyante rājasāḥ. jaghanyaguṇavṛttasthāḥ – jaghanyaḥ ca asau guṇaḥ ca jaghanyaguṇaḥ, tamaḥ tasya vṛttaṃ nidrālasyādi. tasmin sthitāḥ jaghanyaguṇavṛttasthāḥ mūḍhāḥ, adhaḥ gacchanti, paśvādiyoniṣu utpadyante tāmasāḥ.", "tr": "Those abiding in sattva — in the ways of the guṇa sattva — go upward, are born in the world of the gods and the like. The rājasa remain in the middle, are born among men. Those abiding in the ways of the lowest guṇa — the lowest guṇa is tamas, and its ways are sleep, sloth and the like; those abiding in them, the deluded, the tāmasa — go downward, are born in the wombs of animals and the like."},
           ],
           words=[
               ["ūrdhvam", "upward"],
               ["gacchanti", "go"],
               ["sattva-sthāḥ", "those abiding in sattva"],
               ["madhye", "in the middle"],
               ["tiṣṭhanti", "remain"],
               ["rājasāḥ", "the rājasa"],
               ["jaghanya-guṇa-vṛtta-sthāḥ", "abiding in the ways of the lowest guṇa"],
               ["adhaḥ", "downward"],
               ["gacchanti", "go"],
               ["tāmasāḥ", "the tāmasa"],
           ]),
        _v([
            "nānyaṃ guṇebhyaḥ kartāraṃ yadā draṣṭā'nupaśyati |",
            "guṇebhyaśca paraṃ vetti madbhāvaṃ so'dhigacchati",
        ], "|| 19 ||",
           "When the seer sees no doer other than the guṇas, and knows what is beyond the guṇas, he attains my being.",
           bhashya=[
               {"text": "“puruṣasya prakṛtisthatvarūpeṇa mithyājñānena yuktasya bhogyeṣu guṇeṣu sukhaduḥkhamohātmakeṣu, “sukhī duḥkhī mūḍhaḥ aham asmi” ityevaṃ rūpaḥ yaḥ saṅgaḥ tat kāraṇaṃ puruṣasya sadasadyonijanmaprāptilakṣaṇasya saṃsārasya” iti pūrvādhyāye samāsena yat uktaṃ tat iha “sattvaṃ rajastama iti guṇāḥ prakṛtisambhavāḥ” (14.5) ityārabhya guṇasvarūpaṃ guṇavṛttaṃ svavṛttena ca guṇānāṃ bandhakatvaṃ guṇavṛttanibaddhasya ca puruṣasya yā gatiḥ ityetat sarvaṃ mithyājñānam ajñānamūlaṃ bandhakāraṇaṃ vistareṇa uktvā adhunā samyagdarśanāt mokṣaḥ vaktavyaḥ ityāha bhagavān –", "intro": True, "tr": "In the previous chapter it was told briefly that 'for the puruṣa possessed of false knowledge, in the form of abiding in nature, the attachment to the guṇas to be enjoyed, consisting of pleasure, pain and delusion — \"I am happy, unhappy, deluded\" — is the cause of the puruṣa's saṃsāra, consisting in births in good and evil wombs'. Here, beginning with 'sattva, rajas and tamas, the guṇas born of nature' (14.5), he has told at length the nature of the guṇas, their workings, how the guṇas bind by their workings, and the course of the puruṣa bound by their workings — all this false knowledge, rooted in ignorance, the cause of bondage. Now liberation through right vision is to be told; so the Blessed Lord says:"},
               {"text": "na anyaṃ kāryakaraṇaviṣayākārapariṇatebhyaḥ guṇebhyaḥ kartāram anyaṃ yadā draṣṭā vidvān san na anupaśyati. guṇāḥ eva sarvāvasthāḥ sarvakarmaṇāṃ kartāraḥ ityevaṃ paśyati. guṇebhyaḥ ca paraṃ guṇavyāpārasākṣibhūtaṃ vetti madbhāvaṃ mama bhāvaṃ vāsudevatvaṃ “vāsudevaḥ sarvaṃ” (7.19) ityevaṃ paśyan san saḥ draṣṭā adhigacchati.", "tr": "When the seer, having become wise, sees no agent other than the guṇas transformed into the forms of effects, instruments and objects — sees that the guṇas alone, in all their states, are the agents of all actions — and knows what is beyond the guṇas, the witness of their activity, he attains my state, my being Vāsudeva, seeing 'Vāsudeva is all' (7.19)."},
           ],
           words=[
               ["na", "no"],
               ["anyam", "other"],
               ["guṇebhyaḥ", "than the guṇas"],
               ["kartāram", "agent"],
               ["yadā", "when"],
               ["draṣṭā", "the seer"],
               ["anupaśyati", "sees"],
               ["guṇebhyaḥ", "than the guṇas"],
               ["ca", "and"],
               ["param", "what is beyond"],
               ["vetti", "knows"],
               ["mat-bhāvam", "my state"],
               ["saḥ", "he"],
               ["adhigacchati", "attains"],
           ]),
        _v([
            "guṇānetānatītya trīn dehī dehasamudbhavān |",
            "janmamṛtyujarāduḥkhairvimukto'mṛtamaśnute",
        ], "|| 20 ||",
           "Having passed beyond these three guṇas, from which the body arises, the embodied one, freed from birth, death, old age and sorrow, attains immortality.",
           bhashya=[
               {"text": "kathamadhigacchatītyucyate –", "intro": True, "tr": "How he attains it is told:"},
               {"text": "guṇānetān yathoktān atītya jīvanneva atikramya, māyopādhibhūtān trīn dehī, deha samudbhavān dehotpattibījabhūtān janmamṛtyujarāduḥkhaiḥ janma ca mṛtyuḥ ca jarā ca duḥkhāni ca taiḥ jīvanneva vimuktaḥ san vidvān amṛtam aśnute. evaṃ madbhāvaṃ adhigacchatītyarthaḥ.", "tr": "Going beyond these three guṇas as described — passing beyond them while still living — which are the adjuncts of māyā and the seed of the body's arising, the embodied one, freed while still living from birth, death, old age and sorrows, the knower attains immortality. In this way he attains my state — that is the meaning."},
           ],
           words=[
               ["guṇān", "guṇas"],
               ["etān", "these"],
               ["atītya", "going beyond"],
               ["trīn", "three"],
               ["dehī", "the embodied one"],
               ["deha-samudbhavān", "from which the body arises"],
               ["janma-mṛtyu-jarā-duḥkhaiḥ", "from birth, death, old age and sorrow"],
               ["vimuktaḥ", "freed"],
               ["amṛtam", "immortality"],
               ["aśnute", "attains"],
           ]),
        {"speaker": "arjuna uvāca"},
        _v([
            "kairliṅgaiḥ trīnguṇānetānatīto bhavati prabho |",
            "kimācāraḥ kathaṃ caitāṃstrīnguṇānativartate",
        ], "|| 21 ||",
           "Arjuna said: By what marks is he known who has passed beyond these three guṇas, O Lord? What is his conduct, and how does he pass beyond the three guṇas?",
           bhashya=[
               {"text": "jīvanneva guṇānatītya amṛtam aśnute iti praśnabījaṃ pratilabhya–", "intro": True, "tr": "Taking up the seed of a question — 'going beyond the guṇas while still living, one attains immortality' — [Arjuna said]:"},
               {"text": "kaiḥ liṅgaiḥ cihnaiḥ trīn etān vyākhyātān guṇān atītaḥ atikrāntaḥ bhavati prabho. kimācāraḥ kaḥ asya ācāraḥ iti kimācāraḥ kathaṃ kena ca prakāreṇa etān trīn guṇān ativartate, atītya vartate.", "tr": "By what marks, signs, is one who has gone beyond, passed over, these three guṇas as explained known, O Lord? What is his conduct? And how, in what way, does he go beyond these three guṇas, live having passed beyond them?"},
           ],
           words=[
               ["kaiḥ", "by what"],
               ["liṅgaiḥ", "marks"],
               ["trīn", "three"],
               ["guṇān", "guṇas"],
               ["etān", "these"],
               ["atītaḥ", "gone beyond"],
               ["bhavati", "is one"],
               ["prabho", "O Lord"],
               ["kim-ācāraḥ", "what is his conduct"],
               ["katham", "how"],
               ["ca", "and"],
               ["etān", "these"],
               ["trīn", "three"],
               ["guṇān", "guṇas"],
               ["ativartate", "does he go beyond"],
           ]),
        {"speaker": "śrī bhagavānuvāca"},
        _v([
            "prakāśaṃ ca pravṛttiṃ ca mohameva ca pāṇḍava |",
            "na dveṣṭi sampravṛttāni na nivṛttāni kāṅkṣati",
        ], "|| 22 ||",
           "The Blessed Lord said: He who does not hate light, activity and delusion when they arise, Pāṇḍava, nor long for them when they cease;",
           bhashya=[
               {"text": "guṇātītasya lakṣaṇaṃ guṇātītatvopāyaṃ ca arjunena pṛṣṭaḥ asmin śloke praśnadvayārthaṃ prativacanam –", "intro": True, "tr": "Asked by Arjuna about the marks of one beyond the guṇas and the means to go beyond them, he answers both questions in this verse:"},
               {"text": "prakāśaṃ ca sattvakāryaṃ, pravṛttiṃ ca rajaḥkāryaṃ, moham eva ca tamaḥ kāryam ityetāni na dveṣṭi sampravṛttāni, samyak viṣayabhāvena udbhūtāni. mama tāmasaḥ pratyayaḥ jātaḥ, tena ahaṃ mūḍhaḥ tathā rājasī pravṛttiḥ mama utpannā duḥkhātmikā, tenāhaṃ rajasā pravartitaḥ pracalitaḥ svarūpāt, kaṣṭaṃ mama vartate yaḥ ayaṃ matsvarūpāvasthānāt bhraṃśaḥ. tathā sāttvika guṇaḥ prakāśātmā māṃ vivekitvam āpādayan sukhena ca sañjayan badhnāti iti tāni dveṣṭi asamyagdarśitvena. tadevaṃ guṇātītaḥ na dveṣṭi sampravṛttāni. yathā ca sāttvikādi puruṣaḥ sattvādi kāryāṇi ātmānaṃ prati prakāśya nivṛttāni kāṅkṣati na tathā guṇātītaḥ nivṛttāni kāṅkṣati ityarthaḥ. etat na parapratyakṣaṃ liṅgaṃ, kiṃ tarhi svātmapratyakṣatvāt ātmaviṣayameva etat lakṣaṇam. na hi svātmaviṣayaṃ dveṣam ākāṅkṣāṃ vā paraḥ paśyati.", "tr": "He does not hate illumination, the effect of sattva, activity, the effect of rajas, and delusion, the effect of tamas, when they arise, appear fully as objects. [The ordinary man hates them, thinking:] 'A tāmasa notion has arisen in me, by which I am deluded; likewise rājasa activity, painful by nature, has arisen in me, and impelled by that rajas I am stirred from my own nature — how wretched for me is this fall from abiding in my own nature; likewise the sāttvika guṇa, luminous in nature, binds me by giving me discrimination and attaching me to happiness' — so he hates them, for lack of right vision. But one beyond the guṇas does not hate them when they arise. And as the sāttvika man and the others, when the effects of sattva and the rest have shown themselves to him and then ceased, long for them, so the one beyond the guṇas does not long for them when they have ceased — that is the meaning. This is not a mark perceptible to another; rather, being perceptible to oneself, it is a mark concerning oneself; for another does not see the hatred or longing within one's own self."},
           ],
           words=[
               ["prakāśam", "illumination"],
               ["ca", "and"],
               ["pravṛttim", "activity"],
               ["ca", "and"],
               ["moham", "delusion"],
               ["eva ca", "and also"],
               ["pāṇḍava", "O Pāṇḍava"],
               ["na", "not"],
               ["dveṣṭi", "he hates"],
               ["sampravṛttāni", "when they arise"],
               ["na", "nor"],
               ["nivṛttāni", "when they cease"],
               ["kāṅkṣati", "longs for"],
           ]),
        _v([
            "udāsīnavadāsīno guṇairyo na vicālyate |",
            "guṇā vartanta ityeva yo'vatiṣṭhati neṅgate",
        ], "|| 23 ||",
           "who sits as one indifferent, unshaken by the guṇas, who stays firm and does not waver, knowing that it is only the guṇas that are at work;",
           bhashya=[
               {"text": "atha idānīṃ “guṇātītaḥ kimācāraḥ” iti praśnasya prativacanam āha–", "intro": True, "tr": "Now he answers the question 'what is the conduct of one beyond the guṇas?':"},
               {"text": "udāsīnavat yathā udāsīnaḥ na kasyacit pakṣaṃ bhajate tathā ayaṃ guṇātītatvopāyamārge avasthitaḥ āsīnaḥ ātmavit guṇaiḥ yaḥ sannyāsī na vicālyate vivekadarśanāvasthātaḥ. tat etat sphuṭīkaroti – guṇāḥ kāryakaraṇaviṣayākārapariṇatāḥ anyonyasmin vartante iti yaḥ avatiṣṭhati. chandobhaṅgabhayāt parasmaipadaprayogaḥ. “yo'nutiṣṭhati” iti vā pāṭhāntaram. na iṅgate na calati, svarūpāvasthaḥ eva bhavatītyarthaḥ. kiñca", "tr": "Sitting as one indifferent — as an indifferent man takes no one's side, so this knower of the Self, the renouncer established on the path that leads beyond the guṇas, sitting thus, is not moved by the guṇas from his state of discriminating vision. He makes this clear: who stands firm thinking 'the guṇas, transformed into effects, instruments and objects, act upon one another'. The active form of the verb is used for fear of breaking the metre; 'yo'nutiṣṭhati' is another reading. He does not waver, does not move; he remains in his own nature, that is. Moreover —"},
           ],
           words=[
               ["udāsīna-vat", "as one indifferent"],
               ["āsīnaḥ", "sitting"],
               ["guṇaiḥ", "by the guṇas"],
               ["yaḥ", "who"],
               ["na", "not"],
               ["vicālyate", "is moved"],
               ["guṇāḥ", "the guṇas"],
               ["vartante", "act"],
               ["iti", "thus"],
               ["eva", "only"],
               ["yaḥ", "who"],
               ["avatiṣṭhati", "stands firm"],
               ["na", "not"],
               ["iṅgate", "wavers"],
           ]),
        _v([
            "samaduḥkhasukhaḥ svasthaḥ samaloṣṭāśmakāñcanaḥ |",
            "tulyapriyāpriyo dhīrastulyanindātmasaṃstutiḥ",
        ], "|| 24 ||",
           "who is the same in pleasure and pain, self-reliant, to whom a clod, a stone and gold are alike, who is the same towards the dear and the unwelcome, steadfast, the same in blame and praise of himself;",
           bhashya=[
               {"text": "samaduḥkhasukhaḥ – same duḥkhasukhe yasya saḥ samaduḥkhasukhaḥ svasthaḥ sve ātmani sthitaḥ prasannaḥ, samaloṣṭāśmakāñcanaḥ – loṣṭaṃ ca aśmā ca kāñcanaṃ ca loṣṭāśmakāñcanāni samāni yasya saḥ samaloṣṭāśmakāñcanaḥ. tulyapriyāpriyaḥ – priyaṃ ca apriyaṃ ca priyāpriye tulye same yasya saḥ ayaṃ tulyapriyāpriyaḥ. dhīraḥ dhīmān tulyanindātma saṃstutiḥ nindā ca ātmasaṃstutiśca nindātmasaṃstutī, tulye nindātmasaṃstutī yasya yateḥ saḥ tulyanindātmasaṃstutiḥ.", "tr": "The same in pain and pleasure — to whom pain and pleasure are the same; self-abiding, abiding in his own Self, serene; to whom a clod, a stone and gold are the same; to whom the dear and the not-dear are equal; steadfast, wise; to whom blame and praise of himself are equal — the ascetic to whom blame and self-praise are alike."},
           ],
           words=[
               ["sama-duḥkha-sukhaḥ", "the same in pain and pleasure"],
               ["sva-sthaḥ", "self-abiding"],
               ["sama-loṣṭa-aśma-kāñcanaḥ", "to whom a clod, a stone and gold are the same"],
               ["tulya-priya-apriyaḥ", "to whom the dear and the not-dear are equal"],
               ["dhīraḥ", "steadfast"],
               ["tulya-nindā-ātma-saṃstutiḥ", "to whom blame and praise of himself are equal"],
           ]),
        _v([
            "mānāpamānayostulyastulyo mitrāripakṣayoḥ |",
            "sarvārambhaparityāgī guṇātītaḥ sa ucyate",
        ], "|| 25 ||",
           "who is the same in honour and dishonour, the same to friend and foe, and who has renounced all undertakings — he is said to have passed beyond the guṇas.",
           bhashya=[
               {"text": "mānāpamānayoḥ tulyaḥ samaḥ nirvikāraḥ, tulyaḥ mitrāripakṣayoḥ. yadyapi udāsīnāḥ bhavanti kecit svābhiprāyeṇa, tathāpi parābhiprāyeṇa mitrāripakṣayoḥ iva bhavanti iti. ayaṃ tu tulyaḥ mitrāripakṣayoḥ ityāha. sarvārambhaparityāgī dṛṣṭādṛṣṭārthāni karmāṇi ārabhyante iti ārambhāḥ, sarvān ārambhān parityaktuṃ śīlam asya iti sarvārambhaparityāgī. dehadhāraṇamātranimittavyatirekeṇa sarvakarma parityāgī ityarthaḥ. guṇātītaḥ saḥ ucyate.", "tr": "The same in honour and dishonour, equal, unchanged; the same towards friend and foe. Though some are indifferent by their own intention, in others' eyes they seem to take the side of friend or foe; but this one, he says, is the same towards friend and foe. Renouncing all undertakings — undertakings are actions begun for seen and unseen ends; one whose nature is to renounce all undertakings — renouncing all action except what serves merely to sustain the body, that is: he is said to have gone beyond the guṇas."},
           ],
           words=[
               ["māna-apamānayoḥ", "in honour and dishonour"],
               ["tulyaḥ", "the same"],
               ["tulyaḥ", "the same"],
               ["mitra-ari-pakṣayoḥ", "towards the sides of friend and foe"],
               ["sarva-ārambha-parityāgī", "renouncing all undertakings"],
               ["guṇa-atītaḥ", "gone beyond the guṇas"],
               ["saḥ", "he"],
               ["ucyate", "is said to be"],
           ]),
        _v([
            "māṃ ca yo'vyabhicāreṇa bhaktiyogena sevate |",
            "sa guṇān samatītyaitānbrahmabhūyāya kalpate",
        ], "|| 26 ||",
           "And he who serves me with the unfailing yoga of devotion, passing beyond these guṇas, becomes fit to become Brahman.",
           bhashya=[
               {"text": "“udāsīnavat” ityādi “guṇātītaḥ sa ucyate” (23.25) ityetadantam uktaṃ yāvat yatnasādhyaṃ tāvat sannyāsinaḥ anuṣṭheyaṃ guṇātītatvasādhanaṃ mumukṣoḥ. sthirībhūtaṃ tu svasaṃvedyaṃ sat guṇātītasya yateḥ lakṣaṇaṃ bhavati iti. “adhunā kathaṃ ca trīn guṇān ativartate” iti praśnasya prativacanam āha –", "intro": True, "tr": "What was said from 'sitting as one indifferent' to 'he is said to have gone beyond the guṇas' (14.23–25) is, so long as it requires effort, the means of going beyond the guṇas, to be practised by the renouncer seeking liberation; when it has become firm and is known within oneself, it is the mark of the ascetic who has gone beyond the guṇas. Now he answers the question 'how does one go beyond the three guṇas?':"},
               {"text": "māṃ ca īśvaraṃ nārāyaṇaṃ sarvabhūtahṛdayāśritaṃ yaḥ yatiḥ karmī vā avyabhicāreṇa na kadācit yaḥ vyabhicarati, bhaktiyogena – bhajanaṃ bhaktiḥ, saiva yogaḥ tena bhaktiyogena, sevate, saḥ guṇān samatītya, etān yathoktān, brahmabhūyāya bhavanaṃ bhūyaḥ, brahmabhūyāya brahmabhavanāya mokṣāya, kalpate samarthaḥ bhavati ityarthaḥ.", "tr": "And he who — whether ascetic or man of action — serves me, the Lord Nārāyaṇa, dwelling in the hearts of all beings, with unswerving — never swerving — yoga of devotion — devotion is worship, and that is the yoga — he, going beyond these guṇas as described, becomes fit, capable, for becoming Brahman — for liberation, that is."},
           ],
           words=[
               ["mām", "me"],
               ["ca", "and"],
               ["yaḥ", "who"],
               ["avyabhicāreṇa", "unswerving"],
               ["bhakti-yogena", "with the yoga of devotion"],
               ["sevate", "serves"],
               ["saḥ", "he"],
               ["guṇān", "guṇas"],
               ["samatītya", "going beyond"],
               ["etān", "these"],
               ["brahma-bhūyāya", "for becoming Brahman"],
               ["kalpate", "is fit"],
           ]),
        _v([
            "brahmaṇo hi pratiṣṭhā'hamamṛtasyāvyayasya ca |",
            "śāśvatasya ca dharmasya sukhasyaikāntikasya ca",
        ], "|| 27 ||",
           "For I am the abode of Brahman, the immortal and imperishable, of eternal dharma, and of absolute happiness.",
           bhashya=[
               {"text": "kutaḥ etat iti ucyate –", "intro": True, "tr": "Why is this so? It is said:"},
               {"text": "brahmaṇaḥ paramātmanaḥ, hi yasmāt, pratiṣṭhā ahaṃ, pratitiṣṭhati asminniti pratiṣṭhā, ahaṃ pratyagātmā. kīdṛśasya brahmaṇaḥ? amṛtasya avināśinaḥ avyayasya avikāriṇaḥ, śāśvatasya ca nityasya, dharmasya dharmajñānasya jñānayogadharmaprāpyasya, sukhasya ānandarūpasya, aikāntikasya avyabhicāriṇaḥ. amṛtādisvabhāvasya paramānandarūpasya parabrahmaṇaḥ pratyagātmā pratiṣṭhā. samyagjñānena paramātmatayā niścīyate, tadetat “brahmabhūyāya kalpate” ityuktam. yayā ca īśvaraśaktyā bhaktānugrahādi prayojanāya brahma pratitiṣṭhate pravartate sā śaktiḥ brahmaiva aham, śakti śaktimatoḥ ananyatvāt ityabhiprāyaḥ.", "tr": "For I am the abode of Brahman, the supreme Self — an abode is that in which something rests; I, the inmost Self. Of what kind of Brahman? Immortal, indestructible; imperishable, changeless; eternal, everlasting; of dharma — the dharma attained by the dharma of the yoga of knowledge; of happiness, of the nature of bliss; absolute, unfailing. The inmost Self is the abode of the supreme Brahman, whose nature is immortality and the rest, of the nature of supreme bliss; through right knowledge it is ascertained as the supreme Self; this is what was said in 'becomes fit for becoming Brahman'. And the power of the Lord by which Brahman comes forth and acts for the purpose of favouring devotees and the like — that power is Brahman itself, I myself, since the power and its possessor are not different — that is the purport."},
               {"text": "athavā brahmaśabdavācyatvāt savikalpakaṃ brahma. tasya brahmaṇaḥ nirvikalpakaḥ ahameva, na anyaḥ, pratiṣṭhā āśrayaḥ. kiṃviśiṣṭasya? amṛtasya amaraṇadharmasya, avyayasya vyayarahitasya. kiṃ ca śāśvatasya nityasya dharmasya jñānaniṣṭhālakṣaṇasya, sukhasya tajjanitasya aikāntikasya ekāntaniyatasya ca “pratiṣṭhā aham” iti anuvartate.", "tr": "Or else: Brahman with distinctions, since it is denoted by the word 'Brahman'; of that Brahman I alone, without distinctions, and no other, am the abode, the support. Of what kind? Immortal, not subject to death; imperishable, without decay; and of eternal, everlasting dharma, consisting in steadfastness in knowledge; and of the absolute, invariable, happiness born of it — 'I am the abode' carries over."},
           ],
           words=[
               ["brahmaṇaḥ", "of Brahman"],
               ["hi", "for"],
               ["pratiṣṭhā", "the abode"],
               ["aham", "I"],
               ["amṛtasya", "immortal"],
               ["avyayasya", "imperishable"],
               ["ca", "and"],
               ["śāśvatasya", "of eternal"],
               ["ca", "and"],
               ["dharmasya", "dharma"],
               ["sukhasya", "of happiness"],
               ["aikāntikasya", "absolute"],
               ["ca", "and"],
           ]),
        "ornament",
        {"colophon": "iti śrīmahābhārate śatasāhasryāṃ saṃhitāyāṃ vaiyāsikyāṃ bhīṣmaparvaṇi śrīmadbhagavadgītā – sūpaniṣatsu brahmavidyāyāṃ yogaśāstre śrīkṛṣṇārjuna saṃvāde guṇatrayavibhāgayogonāma caturdaśo'dhyāyaḥ.", "gloss": "Thus, in the Bhagavad Gītā — the Upaniṣad, the knowledge of Brahman, the scripture of yoga, the dialogue of Śrī Kṛṣṇa and Arjuna — within the Bhīṣma Parva of the Mahābhārata, the collection of a hundred thousand verses by Vyāsa, ends the fourteenth chapter, Guṇatrayavibhāga Yoga."},
        {"colophon": "iti śrīmatparamahaṃsaparivrājakācāryagovindabhagavatpūjyapādaśiṣyaśrīmacchaṅkarabhagavataḥ kṛtauśrīmadbhagavadgītābhāṣye guṇatrayavibhāgayogo nāma caturdaśo'dhyāyaḥ", "gloss": "Thus ends the fourteenth chapter, Guṇatrayavibhāga Yoga, of the commentary on the Bhagavad Gītā composed by Śrī Śaṅkara Bhagavat, wandering ascetic of the highest order and disciple of Śrī Govinda Bhagavatpāda."},
    ],
}
